### ISSUE TITLE
"unified diff" style merge, as well as side-by-side

### ISSUE THREAD

**Issue by slippycheeze** [bcssov/IronyModManager#100]
Sometimes it is easier to see what is going on with changes when they are presented in "unified" format, rather than side-by-side: https://www.gnu.org/software/diffutils/manual/html_node/Example-Unified.html#Example-Unified

be nice to have that as an option in the conflict resolver.

**Comment by bcssov** [comment]
Maybe in the future, at the same time as this: #66

**Comment by bcssov** [comment]
Going to follow git approach and allow you to just configure external diff tool which Irony will pass on the relevant info and launch it.
