### ISSUE TITLE
Irony fails to launch

### ISSUE THREAD

**Issue by Artikae** [bcssov/IronyModManager#101]
I am using **Windows 10 Home version 1903**, **Stellaris 2.7.2 (60bf)**, **Launcher v. 2020.10**, and **Irony Mod Manager 1.4.58**.

**Steps:**
I downloaded the file "win-x64.7z" and extracted the contents to an empty folder using 7zip. Then, I ran the executable "IronyModManager.exe". Nothing seemed to happen, and the following error log appeared in the folder, "logs".
[2020-08-16_Error.log](https://github.com/bcssov/IronyModManager/files/5081465/2020-08-16_Error.log)
I have done this three times and nothing appeared to change.

**Additional Information:**
I also have a previous version of Irony, version 1.0.86. This version does in fact launch and function, but will not work with the latest Stellaris Launcher since it predates the launcher changes.

Thank you for your help

**Comment by bcssov** [comment]
OK, what seems to be crashing is migration of settings from v1.0 to v1.4. I initially thought I might have a bug in case where you're migrating from v1.0 > v1.4 but tested in dev and all seems well in my case.

Now we gotta dig deeper. 
1. First I'd like more info about your culture settings. 
- Are you using English localization in windows?
- Is irony in v1.0 set to English locale in Irony?

2. Next, I need you to go to start menu and type run and enter the following into **run** "**%appdata%\mario\ironyModManager**"  (without the quotes) this will open the folder where irony stores its settings. I'd like you to take a screenshot of that folder and paste here.

**Comment by Artikae** [comment]
I am indeed using english localization. Irony v1.0 is also set to english.

There's one file in the folder you specified.
![database](https://user-images.githubusercontent.com/6912917/90348018-8043d000-dff9-11ea-8e60-964a8575e9a2.PNG)

Additionally, I tested Irony v1.4 with that folder empty and it launched normally and generated a new file, "Database_1.4.json", in that folder.

I don't need any additional help here. I don't need my old settings anyway. If you want to see the database file, I can post it here. If you need anything else, I'll be here.

**Comment by bcssov** [comment]
Yeah, I want to see that old db. Might be something in it crashing Irony...

**Comment by Artikae** [comment]
[Database.zip](https://github.com/bcssov/IronyModManager/files/5081709/Database.zip)

**Comment by bcssov** [comment]
Can't reproduce, regardless will push an updated version so that the app doesn't crash on such instances.
