### ISSUE TITLE
Unable to save conflict issue

### ISSUE THREAD

**Issue by yggdrasil75** [bcssov/IronyModManager#105]
[2020-08-28_Error.log](https://github.com/bcssov/IronyModManager/files/5144066/2020-08-28_Error.log)

for irony manager 1.4.68 and 1.4.69 when I click "resolve conflicts" I get the error that it can not write to the mods directory. I have found a new "mod" in the stellaris mod folder for irony manager though.

**Comment by bcssov** [comment]
Well your mods_registry or game_data.json has an item which contains an invalid Guid datatype. It's something which contains the value of "alpha", I don't know which piece of software previously generated such an id but for sure I know it wasn't irony or the pdx launcher. 

From v1.4 and and onwards I've changed the datatype from string to Guid to reflect this better given the fact that pdx also switched to using a sqllite database and I want to use a unified model for both json and sqlite providers using the same primary key datatypes.

**Comment by bcssov** [comment]
I am closing this issue, feel free to open it if you have any additional comments.
