### ISSUE TITLE
Wishlist: Update existing merged collection

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#107]
Right now Irony will make another merged collection with a suffix (for example (1)). Would be nice if I could update an existing merge. Right now I remove the collection from irony, delete the merged mod in the mods folder, restart irony, perform basic merge again.

**Comment by bcssov** [comment]
I suppose I could ask you in a yes\no prompt whether you wanted to overwrite a mod or create a new one. But the effect to the mod would be the same, the folder would be purged and everything done from scratch.
