### ISSUE TITLE
Missing tables identified as Playsets

### ISSUE THREAD

**Issue by GraveKeeper916** [bcssov/IronyModManager#110]
I am currently going through and updating my Stellaris mod list to remove outdated mods and add new ones. Currently, I am at the point where I need to resolve conflicts and apply the list to the game but i get this error line. 
[2020-09-05_Error.log](https://github.com/bcssov/IronyModManager/files/5178509/2020-09-05_Error.log)

**Comment by GraveKeeper916** [comment]
I even checked with a friend that does programming development and we manually entered values into the playset table but it still gives the same error.

**Comment by bcssov** [comment]
Congratulations you've borked up your paradox launcher database file somehow. 
Neither Irony or pdx launcher will probably operate (Irony will still work though it just won't be able to update the sqlite database). 
I recommend that you delete the sqlite database and either allow irony to create a new valid one or pdx launcher. Both are capable of creating a new fresh valid database.
Note: 
- Irony will recreate it when you try to resolve a conflict or try to apply the mod collection
- Paradox launcher will recreate it when you run it next time

**Comment by bcssov** [comment]
Hope you managed to save data you might have had in that sqlite db. Please be careful in the future. Going to close this. Feel free to open a new issue or reactivate this issue in case of further problems.
