### ISSUE TITLE
Load order export/import

### ISSUE THREAD

**Issue by OldEnt** [bcssov/IronyModManager#111]
It could be beneficial to add options for export/import load order.

Exported Irony patch without conflict resolver ran even once will produce a zip with exported.json only. Such zip acts as a perfect load order, ready to be imported.

[LOAD_ORDER.zip](https://github.com/bcssov/IronyModManager/files/5178905/LOAD_ORDER.zip)

**Comment by bcssov** [comment]
Note: Just add export load order option. There really is no valid use case to import a load order only from zip. Mod collection should be imported as was exported at all times.
