### ISSUE TITLE
[suggestion] document what mod order means

### ISSUE THREAD

**Issue by barcharcraz** [bcssov/IronyModManager#112]
Since paradox themselves have change the meaning of mod order multiple times you should probably document what mod order means. That is: does the mod with order 1 override the one with order 7 or is it the other way round.

**Comment by bcssov** [comment]
The FAQ does state which mod order irony follows so that should cover that I think: https://github.com/bcssov/IronyModManager/wiki/FAQ

**Comment by bcssov** [comment]
FAQ updated a bit for clarity but pointing towards the official v2 docs and meanings.
