### ISSUE TITLE
Fatal Error on load after updating to 1.5.48

### ISSUE THREAD

**Issue by SephirothWS** [bcssov/IronyModManager#113]
Fatal Error, Unhandled exception occurred. App will close automatically.

Every, single, time, I load the app. I cannot figure out what is causing this.

Edit: This happened after I unsubscribed from a workshop mod on Steam.

**Comment by bcssov** [comment]
Well I'd like to see the logs to prevent any future crashes such as this though.

**Comment by SephirothWS** [comment]
Should this ever happen again, how/where can I find/get logs for this?

**Comment by OldEnt** [comment]
Installation folder **Irony Mod Manager\logs\**
