### ISSUE TITLE
Wishlist: Ignore individual localisation items (or files) with language tag.

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#114]
Would be nice to be able to ignore localisation items and/or files with language tags.

For example, I'm only interested in English text so I'd like to be able to ignore everything that isn't tagged as l_english. A Spanish person might want to only see l_spanish, etc.

**Comment by bcssov** [comment]
Add support for the following wildcard syntax for ex;
```
localisation\*l_chinese.yml
localisation\*l_russian.yml
localisation\*l_french.yml
localisation\*l_spanish.yml
```
