### ISSUE TITLE
Wishlist: Indicate which file an object definition was loaded from.

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#115]
This might help where a mod has an object definition in multiple files (the events folder of ECA (https://steamcommunity.com/sharedfiles/filedetails/?id=1790861374) for example. 

Would be helpful to see filename as well as just the fact it came from ECA so I can choose the correct object to patch from.

**Comment by bcssov** [comment]
Gonna need to use alternate means to show path since with all the info it can get crowded in the listbox. Possibly maybe open in asset folder can be a replacement #62

**Comment by LordOfLA** [comment]
Maybe tooltip on hover?

**Comment by bcssov** [comment]
That works, though you'll also have the option of directly opening the asset via context menu in the selector.
