### ISSUE TITLE
Option to disable closing Irony after clicking launch

### ISSUE THREAD

**Issue by Nightliss** [bcssov/IronyModManager#117]
Hey there o/

I'd like to request an option (maybe checkbox in options?) to disable closing Irony when launching the game. It's kinda annoying when trying out mods and switching load order. Thanks!

**Comment by bcssov** [comment]
From what I can tell it behaves the same way paradox launcher would and I think paradoxos even. Putting this on vNext.

**Comment by Nightliss** [comment]
Well Paradox Launcher does indeed close but it's a launcher, not mod manager :). Neither NMM, Vortex, Mod Organizer for Bethesda Games, nor Rimpy for Rimwold or DivnityModManger behave that way. Anyway thanks for consideration.

**Comment by bcssov** [comment]
Honestly I wouldn't know never used either of these programs.
