### ISSUE TITLE
Mod manager not detecting most steam workshop mods.

### ISSUE THREAD

**Issue by nickg11** [bcssov/IronyModManager#121]
When I launch the mod manager it only detects 12 out of my 60 mods I have installed via steam workshop, the 12 that are detected are also from the workshop. All the mods are saved in the same directory as well. I am unsure why most aren't being detected and I cannot find a way to make the mod manager detect them.

**Comment by nickg11** [comment]
I reinstalled my stellaris and all the workshop mods and now it has detected them correctly. The issue might be related to the fact that I had a secondary installation of stellaris and it was pulling the mods from that instead of my current one.

**Comment by bcssov** [comment]
Irony will detect mods and games that are written in the steam registry and by this logic it will look for mods in %steamlibrary%\Steam\steamapps\workshop\content\281990. It will not detect anything else that you might have manually hacked around from the sound of it. This sounds like one of the acf paths that steam generates pointed towards that other installation. Closing.
