### ISSUE TITLE
Unpacking software fails to open RAR file on linux

### ISSUE THREAD

**Issue by Womble** [bcssov/IronyModManager#125]
When unzipping the linux release file (1.7.30) each file is inflated until the entire hard drive is consumed

Seen using Ubuntu (gnome) 20.04 with the current release.

**Comment by bcssov** [comment]
Have you tried using another archiver to unpack the release? There really is nothing out of the ordinary in the rar itself

**Comment by Womble** [comment]
just tried Downloading a separate CLI package from unpacking rar files (unrar-free) and it fails with the following error (though at least doesnt start filling the hard drive.

$ unrar linux-x64.rar

unrar 0.0.1  Copyright (C) 2004  Ben Asselstine, Jeroen Dekkers


Extracting from /media/7a65f7a6-09a3-45a9-b53b-3f166fe5d452/Downloads/linux-x64.rar

unknown archive type, only plain RAR 2.0 supported(normal and solid archives), SFX and Volumes are NOT supported!
All OK

**Comment by bcssov** [comment]
Unfortunately it's your archive software filling the disk not Irony.

**Comment by Womble** [comment]
Well yes obviously, but a well formatted rar file should not do this, none have before.

**Comment by bcssov** [comment]
Well the rar was made using WinRAR.

**Comment by bcssov** [comment]
Could it be possibly confused with the compression level?

**Comment by Womble** [comment]
Hmm, with further testing it does appear that unrar-free seems to be the issue. Trying another unrar program seems to work fine, I've never seen this happen before with a rar file, are you using any unusual options in the creation of it?

**Comment by bcssov** [comment]
Not to my knowledge, autodeploy packaging script:
```rar a -ep1 -m5 -r linux-x64.rar linux-x64```

-ep1: https://documentation.help/WinRAR/HELPSwEP1.htm
-m5 compression level (being the highest)

**Comment by Womble** [comment]
Very strange, I'm at a loss to why it fails in various ways with different rar backends then. But that's not really anything you can do much about.

**Comment by bcssov** [comment]
Easier yes; but I don't have too much spare time to find proper tools for windows to pack a tar.gz and edit my deployment skills. I will switch to zip however for Linux.
