### ISSUE TITLE
IMM appears to ignore older version mods or doesn't correctly recognize zipped files with a different format (Europa Universalis IV)

### ISSUE THREAD

**Issue by notNSANE** [bcssov/IronyModManager#126]
**Describe the bug**
Apparently, an outdated "non-compatible" mod gets ignored when merging them.

**To Reproduce**
1. Add this mod to EUVI via Workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=677258950
2. And also any other compatible mod with EUVI v 1.30.
3. Open Irony Mod Manager and merge them, Apply changes.
4. Launch EU IV normally in Steam, via the 'IronyModManager' playlist that includes merged mods in 1 file.

**Expected behavior**
Mod works correctly.

**Version:**
 - OS: Windows 10
 - Irony Version 1.7.34

**Additional context**
Please note that the mod is very particular and it only has a compressed masked zip file called "943965591832000099_legacy.bin". It works correctly when launched non-merged with the Paradox Launcher v2.

**Comment by bcssov** [comment]
Um, I kinda don't own EUIV so can't really test. Can you upload this legacy bin whatever here so I can take a look and test?

**Comment by notNSANE** [comment]
[943965591832000099_legacy.zip](https://github.com/bcssov/IronyModManager/files/5331182/943965591832000099_legacy.zip)

hope this is enough, it's just that file.

And this is how the file it's called (ugc_677258950.mod) on My Documents/Paradox Interactive/mod:

`name="A Rev. Font Mod - Theatrum Orbis Terrarum Gold"
tags={
	"map"
	"graphics"
	"Map Font"
}
picture="image.PNG"
supported_version="1.28.*.*"
archive="Steam/steamapps/workshop/content/236850/677258950/943965591832000099_legacy.bin"`

(full path edited)

**Comment by bcssov** [comment]
Added support (need to publish release)
