### ISSUE TITLE
Irony crashed when creating first collection 

### ISSUE THREAD

**Issue by epq1176** [bcssov/IronyModManager#127]
Irony crashed when creating first collection without changing any default setting, and keeping crashing when trying restart Irony

[2020-10-08_Error.log](https://github.com/bcssov/IronyModManager/files/5349114/2020-10-08_Error.log)

**Version:**
 - OS: Windows 10 education 2004 
 - Irony Version 1.7.37

**Additional context**
running in chinese localization and Irony is set to chinese

**Comment by bcssov** [comment]
Irony is crashing trying to parse mod files found in these locations (to see whether it needs to install a mod):
1. {SteamLibrary}\steamapps\workshop\content\281990
2. Documents\Paradox Interactive\Stellaris\mod
One of the archives found in these locations appears to be password protected (an occurrence which does not happen when using steam or creating mod files via paradox launcher). Which indicates this might be a file you created perhaps or some other software. To fix the issue please find that zip file and move it to another location.

**Comment by epq1176** [comment]
some of my hoi4 mods are using zip to store mod files and that seems to be the reason why Irony crash

**Comment by bcssov** [comment]
Irony supports opening zip files but something regarding these zips makes the third party component think they are either password protected or encrypted thus preventing Irony from opening and parsing them.

Zipped stellaris mods are very much supported as well, bin files from EUIV. This is something down on your system.
