### ISSUE TITLE
Save error

### ISSUE THREAD

**Issue by epq1176** [bcssov/IronyModManager#128]
unable to write to mod files
[2020-10-09_Error.log](https://github.com/bcssov/IronyModManager/files/5353240/2020-10-09_Error.log)

**Comment by bcssov** [comment]
Your 'launcher-v2.sqlite' is corrupt. I don't know the reason. Did you edit it manually or something? Under normal circuimstances this should not happen, during normal usage of the paradox launcher and Irony.

```There are no database fields found for table 'playsets'.```
You can try to re-create the table schema or simply delete 'launcher-v2.sqlite' and Irony will re-create the whole file. Irony will not recreate the whole table schema though.

**Comment by epq1176** [comment]
thx, it works

**Comment by bcssov** [comment]
Ok, closing the ticket then.
