### ISSUE TITLE
Irony unable to write files when clicking "resolve"

### ISSUE THREAD

**Issue by Germanboy4u** [bcssov/IronyModManager#129]
Version: Irony 1.7.37

Everytime I press Apply I get the error message, that something is blocking Irony.

Same problem like: https://github.com/bcssov/IronyModManager/issues/120

Tried to disable AV and using admin rights. No success.

Log attachted
[error.log](https://github.com/bcssov/IronyModManager/files/5353813/error.log)

launcher-v2.sqlite in user Profile is empty.

**Comment by bcssov** [comment]
This is the wrong error log, I do not require game error log but the Irony error log. But it is most certainly not related to issue 120 as that was a reproducible bug which was resolved. 

It could possibly more related to issue #128. Though to be sure I'd need the actual Irony logs.

**Comment by Germanboy4u** [comment]
Thank you for your answer. 
Problem: C:\Program Files\Irony Mod Manager\logs is empty. Or is there an other folder for logs?

**Comment by bcssov** [comment]
In general Irony will write to the logs folder where you were looking, but in your case the program runs under virtualization in Windows which means it doesn't have write permissions to program files directory. Instead the output is redirected to 
%localappdata%\Program Files\Irony Mod Manager\logs most likely. 
So you can look there; or only for this instance run once Irony as admin and recreate the issue so Irony will write the log in the actual Program Files directory.

**Comment by Germanboy4u** [comment]
So I reinstalled Irony. Now I got a error log

[2020-10-09_Error.log](https://github.com/bcssov/IronyModManager/files/5355177/2020-10-09_Error.log)

**Comment by bcssov** [comment]
Same as #128. See solution there.

Though I don't understand how a whole table is missing from a database. Have you used anything other than Irony or Paradox Launcher on this database? Dropped the table somehow?

**Comment by Germanboy4u** [comment]
No I didn't. I reinstalled yesterday my computer. I will reinstall stellaris. may be it will solve the problem

**Comment by bcssov** [comment]
Just delete 'launcher-v2.sqlite' and you're all good. Irony will recreate the database on its own. But before you do upload this  'launcher-v2.sqlite' here so I can take a look. The database is corrupt and I don't know why.

**Comment by Germanboy4u** [comment]
To late. :-) I reinstalled Irony and Stellaris. Now it working. 

Thank you for your assistance
