### ISSUE TITLE
Crash when selecting Stellaris game directory

### ISSUE THREAD

**Issue by blargh2015** [bcssov/IronyModManager#137]
Whenever I try to select my Stellaris game directory or pick the executable, the application crashes with an unhandled exception.

Error log attached.
[2020-10-30_Error.log](https://github.com/bcssov/IronyModManager/files/5468140/2020-10-30_Error.log)

**Comment by bcssov** [comment]
Irony should definitely not crash like this so gotta fix that, but you are doing something wrong however. First ensure that you select a game before you try to set game specific options:
![Image2](https://user-images.githubusercontent.com/5864390/97765715-74a17900-1b13-11eb-832c-6d021dcef837.jpg)
Refer to this on what to do as a first time user:
https://github.com/bcssov/IronyModManager/wiki/New-User-Checklist

**Comment by blargh2015** [comment]
Okay, doing that did make it work (and it auto-found Stellaris), so my tinkering can resume :)

**Comment by bcssov** [comment]
Pushing a new release which fixes this. Closing.
