### ISSUE TITLE
Feedback/Not an issue: DX11 (Merged) decreased loading times around 75% in my case. What about you?

### ISSUE THREAD

**Issue by notNSANE** [bcssov/IronyModManager#139]
Again, not an issue, just curious about other people's numbers. These are my numbers in minutes:

DX9: 5+ minutes
DX9 (Merged): around 2 minutes
DX11: 2.5 minutes
DX11 (Merged): 0.5 minutes (!!)

So happy about this! Using a Ryzen 1600.

**Comment by bcssov** [comment]
Going to put a label on it so that stale bot doesn't close this issue.

**Comment by bcssov** [comment]
DX11 Basic Merge Load 1 38:73s
DX11 Basic Merge Load 2 37:77s
DX11 Advanced Merge Load 1 36:97s
DX 11Advanced Merge Load 2 35:89s

Using i7-8700
