### ISSUE TITLE
[Suggestion][UI] Show a warning when importing a collection

### ISSUE THREAD

**Issue by ThibautSF** [bcssov/IronyModManager#14]
Importing a collection which has the same name than an existing one erases the existing collection by the imported one.

Step to reproduce:
- Export a collection A
- Add mod X to collection A (A2)
- Import previous export
- Collection A2 is erased and replaced by A

Suggestion:
- Warning dialog window -> ie "This collection already exists"
- Choice: "Cancel import", "Import and Replace", "Import to a new name" (user enter a name)

Note:
In Paradox Mod Manager I made the choice to add a unique info in the name (the timestamp) which user would be able to remove when renaming the collection.

**Comment by bcssov** [comment]
That's actually by design to replace existing collections: https://github.com/bcssov/IronyModManager/wiki/Collection-Mods

I will schedule this for a future release in vNext to revisit and see if it is necessary after an additional round of alpha testing and UAT.

**Comment by bcssov** [comment]
After giving it another thought I'm moving for 1.1 target release. Depends on #16
