### ISSUE TITLE
Documentation Request - how to apply patch with resolved conflicts

### ISSUE THREAD

**Issue by etmoonshade** [bcssov/IronyModManager#141]
Part of the issue here is that I'm not all that familiar with Stellaris modding, but I went through and (hopefully) reconciled all the issues between my mods manually.

The only problem is, I have no clue where the patch is now - I don't see a way to export it from the "Resolve Conflicts" window, and it's not selectable in the main mod view.

halp :(

**Comment by LordOfLA** [comment]
Ah, it's already applied, just hit apply and Irony will add the patch to the launcher/game load order in the right place for when you launch the game.

**Comment by etmoonshade** [comment]
hah, well crap. That means that I must've messed up merging the various patches. I admit, I'm not keen on having to do them all over again, but it is what it is. I'll update the wiki if I'm able to, to state this explicitly - I wasted quite a bit of time trying to find it. :)

**Comment by etmoonshade** [comment]
... unfortunately, the wiki isn't openly editable, so I guess I'll have to wait for someone else to add it. Oh well. Thanks for the info all the same.

**Comment by bcssov** [comment]
Allowing just about anyone to edit the wiki is a bad idea. Fork the wiki make your changes and push them on your own forked repo. Let me know when you're done and I'll merge them myself.

**Comment by OldEnt** [comment]
Your patch is visible as a new mod in \Documents\Paradox Interactive\Stellaris\mod . Paradox Launcher shows it, Irony Mod Manager does not as it has a file which idicates to which Irony mod collection it is tied to.
