### ISSUE TITLE
Mod manager is saying that it is locked out of writing to the mod files

### ISSUE THREAD

**Issue by omnidave4204** [bcssov/IronyModManager#142]
Tried to apply mods to Stellaris but keeps saying that its locked out of writing to the mod files, tried it with several mods at first and then reduced it to just one mod but it says the same thing. Probably me not doing something right so I'm hoping that its something that can be fixed.

[
[2020-11-02_Error.log](https://github.com/bcssov/IronyModManager/files/5472135/2020-11-02_Error.log)
](url)

**Comment by bcssov** [comment]
I can't help you other than tell you that something on your computer is denying irony permission to delete\overwrite files in the mod folder. Could be some permissions, or could be a very aggressive antivirus setting. 

Not an Irony issue but probably an aggressive AV or some other security suite issue.

**Comment by ExoFage** [comment]
I have the same issue. Antivirus is off, irony is launched with Administrator privileges
[2020-11-04_Error.log](https://github.com/bcssov/IronyModManager/files/5489660/2020-11-04_Error.log)

**Comment by bcssov** [comment]
It's not the same, for your case just delete 'launcher-v2.sqlite'  as it became corrupt. Reason: unknown.
