### ISSUE TITLE
-dx11 in Gamer Args messes game up

### ISSUE THREAD

**Issue by ChaplainNirwana** [bcssov/IronyModManager#144]
Adding -dx11 to game arg in Options runs game in lower resolution however, no changes in resolution can be seen in Actual Settings > Resolution in the game itself. Also causes an offset of the Actual position of cursor from the visual cursor.
Am I supposed to use -dx11 in Steam>Stellaris>Set Launch options?
Alt Tabbing fixes the issue but thought it better to inform, game loads way faster than ever before though
![IronyModManager_nbv7trSwxT](https://user-images.githubusercontent.com/46634746/98280799-eec57800-1fc1-11eb-9bb3-d8cae6dae63e.png)
![Offset+Reso](https://user-images.githubusercontent.com/46634746/98280803-f127d200-1fc1-11eb-9820-c4993d255f99.png)

**Comment by bcssov** [comment]
You can set -dx11 arg in both Irony or Steam (depending on what you use to launch the game with). 

Having said that sorry but this is not an Irony issue; but a game issue please take it up with Paradox. As far as I know many similar issues such as yours have been reported.

**Comment by ChaplainNirwana** [comment]
> You can set -dx11 args in both Irony or Steam (depending on what you use to launch the game with).
> 
> Having said that sorry but this is not an Irony issue; but a game issue please take it up with Paradox. As far as I know many similar issues such as yours have been reported.

Understood, Thank you.
