### ISSUE TITLE
Mod Manager Displays incorrect Stellaris mod version

### ISSUE THREAD

**Issue by fastgar** [bcssov/IronyModManager#146]
Affected for me is "Beautiful Universe v2.0".

In the Mod Manager it shows this mod is version 2.5.*.
But then opening the Mod Location an looking into the descriptor.mod file i see the following content:
name="Colored Map Icons"
tags={
	"Graphics"
}
picture="thumbnail.png"
supported_version="2.8.*"
remote_file_id="1381214767"

Also then adding Beautiful Universe 2.0 with the Stellaris internal Mod Manager everything is fine, but if i apply via irony mod manager than i get a warning in the stellaris launcher about incompatible mod version.

Are the mods and there infos cached somewhere that i can delete and refresh the cache or is this a bug?

Mod Manager Version 1.8.52

**Comment by bcssov** [comment]
Paradox Launcher uses sqlite database while Irony reads what's in mod directory.

https://github.com/bcssov/IronyModManager/wiki/Installed-Mods 
Look for Delete and Reload option to rebuild descriptor info.

**Comment by fastgar** [comment]
Trying "Delete and Reload"

Gives me a Fatal Error and closes the Application.
![image](https://user-images.githubusercontent.com/12036024/98465622-7382e280-21ca-11eb-9fa0-16a12db4b881.png)

**Comment by bcssov** [comment]
Logs.

**Comment by fastgar** [comment]
[2020-06-27_Error.log](https://github.com/bcssov/IronyModManager/files/5506367/2020-06-27_Error.log)

**Comment by bcssov** [comment]
Date of the log is wrong, that's a 4 month old log. I need the up to date logs. 

But judging by these entries I'm going to guess it's a permission issue. Something on your computer could be denying irony permission to delete\overwrite files in the mod folder. Could be some permissions, or could be a very aggressive antivirus setting.

**Comment by fastgar** [comment]
Okay, with deactivated antivurs it does not crash, and this was the latest log, probably the antivirus also prevented the creation of log files.

But now with successfull delete and reload the shown version number of Beautiful Universe v2.0 is still 2.5

**Comment by bcssov** [comment]
Take the time to read what each of the context menu action does. There are 2. One deletes currently hovered descriptor while the other one regenerates all of them.

**Comment by fastgar** [comment]
Yes i read about both in the linked github wiki, but still the version is sadly not refreshed.

I will just accept that i can't use said mod and close this ticket, thanks for your help on a sunday.

**Comment by bcssov** [comment]
Data still needs to be now synced with pdx launcher by applying a collection from Irony. Regardless version just is for info purposes.
