### ISSUE TITLE
Merge Item List

### ISSUE THREAD

**Issue by TrueGuardian32** [bcssov/IronyModManager#147]
**Is your feature request related to a problem? Please describe.**

I'm working on a pack for myself where I will merge different files to form separate core files for my pack, such as a Shipset Pack or Tradition Pack, or Patch Pack, it is difficult for me with my bad short term memory to remember what I added. 

**Describe the solution you'd like**

A text list that prints the names of the files that were merged in load order. In a notepad or something in the merged file.

**Describe alternatives you've considered**
I haven't considered any alternatives. 

**Additional context**

**Comment by bcssov** [comment]
Let's see if I understand this correctly, you want a feature to list all files (not mod names) in a given merged mod?

For this you don't need any feature in Irony just use ```dir /s /b``` cmd command to list. If you want to save the output to disk somewhere just use ```dir /s /b > out.txt```.

If you meant mod names, then you could use multiple collections for this purpose.

**Comment by TrueGuardian32** [comment]
> Let's see if I understand this correctly, you want a feature to list all files (not mod names) in a given merged mod?
> 
> For this you don't need any feature in Irony just use `dir /s /b` cmd command to list. If you want to save the output to disk somewhere just use `dir /s /b > out.txt`.
> 
> If you meant mod names, then you could use multiple collections for this purpose.

I'll try it out later to see if that's what I mean, I've gotten too tired to work on it now.
