### ISSUE TITLE
Feature Request: an option to reload all mod descriptors.

### ISSUE THREAD

**Issue by DonCardamon** [bcssov/IronyModManager#148]
**Is your feature request related to a problem? Please describe.**
The name/supported version of a mod often don't update - a mod might change to a new version (which can be seen in the mod's "descriptor.mod" file), but the name/supported version in the mod manager remain the same.

**Describe the solution you'd like**
A button to refresh the mods' description data in the mod manager. In addition, would be nice to have an option to refresh description for an individual mod in the right click menu.

**Describe alternatives you've considered**
Alternatively, the mod manager can automatically refresh all mod descriptions on start, but that might be too much - especially if using several games with many mods each.

**Additional context**
Example:
![image](https://user-images.githubusercontent.com/31593063/98681564-8b459c80-236b-11eb-97cc-5c89dac97aef.png)

**Comment by bcssov** [comment]
All of the features already exist in a certain capacity. Please take the time to review the wiki docs for these:
https://github.com/bcssov/IronyModManager/wiki/Installed-Mods#context-actions
https://github.com/bcssov/IronyModManager/wiki/Options#game-options

![1](https://user-images.githubusercontent.com/5864390/98698387-3fe4bb80-2376-11eb-81b0-7a5698d69f63.jpg)
![2](https://user-images.githubusercontent.com/5864390/98698394-42471580-2376-11eb-9292-2c807b16da6d.jpg)
