### ISSUE TITLE
Treat random_names as file conflicts

### ISSUE THREAD

**Issue by littleraskol** [bcssov/IronyModManager#149]
**Describe the bug**
I'm getting conflicts in the conflict solver where it shows two different uses of the same format in different empire_name_format blocks, although I don't think these are actual conflicts.

**To Reproduce**
1. Run the conflict solver in advanced mode on my mod Government Variety Pack. (Located here: https://steamcommunity.com/sharedfiles/filedetails/?id=901988941 )

**Expected behavior**
I did not expect there to be a conflict between two different empire_name_format blocks using the same format. 

**Screenshots**
Below is an example of "conflicted" empire_name_format blocks. They are in different files and reflect name formats for different governments with different weightings. 

![2020-11-10 09_47_14-Irony Mod Manager_ v1 8 52](https://user-images.githubusercontent.com/21014733/98689282-c4fdaf80-2339-11eb-872b-1f043f1333bd.png)

This shows what one of the "conflicted" empire_name_format block looks like in one file.

![2020-11-10 09_48_55-lrsk_gov_var_empire_names_base_game_overrides txt - lrsk-gov-var - Visual Studio](https://user-images.githubusercontent.com/21014733/98689504-ffffe300-2339-11eb-9c94-c3acecc2848e.png)

This shows what the other "conflicted" empire_name_format block looks like in an entirely different file.

![2020-11-10 09_49_06-lrsk_gov_var_empire_names_other txt - lrsk-gov-var - Visual Studio Code](https://user-images.githubusercontent.com/21014733/98689654-232a9280-233a-11eb-8b87-f96c539f64dd.png)

**Logs**
No crash, no log.

**Version:**
 - OS: Windows 10
 - Irony Version 1.8.52

**Additional context**
It's possible I am wrong and you can't have two different empire_name_format blocks using the same format. But I have been using empire_name_format blocks like this for actual years with no issues generating random names for the different empires using the same format.

**Comment by bcssov** [comment]
Well game overrides elements by using a certain unique key that is used as an identifier in PDX scripts. For empire name format I'm fairly certain that key would be the ```format``` key (I've seen no evidence to support otherwise).

For events that is the ```id``` key within the event "definition":
```
country_event = {
	id = my_event.1
}
```
And having 2 same ids means that one of these will be overwritten (only one element is used). The same goes for UI elements where most of them use the ```name``` key as a unique identifier. Same should apply for empire format names.

If if weren't the case then I'm sure that vanilla scripts would not care about incrementing the numbering such as this example:
```	format = "format.imp_mil.1"
	format = "format.imp_mil.2"
	format = "format.imp_mil.3"
	format = "format.imp_mil.4"
	format = "format.imp_mil.5"
```
	
Or this:
```
	format = "format.imp_spi.1"
	format = "format.imp_spi.2"
	...
```
And so on.

**Comment by littleraskol** [comment]
Thanks for getting back to me! I actually think that what you've described is not how it works. I say this because the changes in my mod that are being flagged as conflicts have been in the mod since December 2018. I tested the changes at the time and found that they were acting as I expected, which was for both base game governments and mod-added governments to use name formats that I added. This is despite their being defined separately in two different `empire_name_format` blocks. 

As for why the the base game uses incrementing format codes, each of those refers to a different empire name format in `localisation_synced/empire_formats.yml`.

So to take the `format.imp_mil` line of formats you referred to. These are defined in `empire_formats.yml` as follows:
```
 format.imp_mil.1: "<imperial_mil> of [This.Capital.System.GetName]"
 format.imp_mil.2: "<imperial_mil> of [This.Capital.GetName]"
 format.imp_mil.3: "[This.GetSpeciesName] <imperial_mil>"
 format.imp_mil.4: "<imperial_mil_desc> [This.GetSpeciesName] <imperial_mil>"
 format.imp_mil.5: "[This.GetSpeciesName] <imperial_mil_mid_desc> <imperial_mil>"
```

This defines five different formats for how an empire can be randomly named, based on species name, homeworld name, and home star name, and using random lists of text defined in `common/00_empire_names.txt`.

What's going on with the `empire_name_format` blocks has to do with (in my observation) two things, the `random_weight` and the governments it specifies. Take the first two blocks for militarist imperial government names.

```
# Imperial Militarist 1
empire_name_format = {
	random_weight = {
		factor = 0
		modifier = {
			add = 1
			OR = {
				has_government = "gov_star_empire"
				has_government = "gov_martial_empire"
			}
			is_pirate = no
			is_primitive = no
			NOT = { is_country_type = fallen_empire }
			NOT = { is_country_type = awakened_fallen_empire }
		}
	}
	format = "format.imp_mil.1"
	prefix_format = "[This.Capital.System.GetName] <imperial_mil>"
	noun = "[This.Capital.System.GetName]"
	# Empire of Sol
}

# Imperial Militarist 2
empire_name_format = {
	random_weight = {
		factor = 0
		modifier = {
			add = 1
			OR = {
				has_government = "gov_star_empire"
				has_government = "gov_martial_empire"
			}
			is_pirate = no
			is_primitive = no
			NOT = { is_country_type = fallen_empire }
			NOT = { is_country_type = awakened_fallen_empire }
		}
	}
	format = "format.imp_mil.2"
	prefix_format = "[This.Capital.GetName] <imperial_mil>"
	noun = "[This.Capital.GetName]"
	# Empire of Earth
}
```

Each block is saying: "There's no chance an empire can use the formatting I specify unless it's (among other things) a Martial Empire or a Star Empire, in which case it has some chance (given by adding 1 to my random weight)." It defines them separately to give a separate chance of these governments picking `format.imp_mil.2` or `format.imp_mil.1`. It also defines other formatting info: the `prefix_format` and the `noun`. This means that the format token is not a unique identifier but one of three results for formatting an empire name defined by the block.

In other words, those formats are not uniquely identifying the block, they are describing one outcome of a set of conditions defined by the block. `empire_name_format` blocks are not unique, each block tells the game to add to its "random name table" a different entry.

I had tested the expected result of the modification (that both base game and mod-added governments would use new name formats I added, even though they are defined in different blocks) back in 2018, and it worked then. For completion's sake, I tested it again just now and it's working as expected. The test involved rolling random names for a Criminal Syndicate (base game) and a Crime Family (mod-added, requires Merchant Guilds, Barbaric Despoilers, and Imperial authority) government, because that is the conflict I highlighted in my bug report. (However, as you can see from the first screenshot I shared by looking at the left side list of conflicts, this impacts many, many more mod-added name format blocks.) Both were able to use my new name format.

To explain this test and how to replicate it, I need to explain the background of this change. I added the following empire name formats in `localisation_synced/lrsk_gov_var_empire_formats.yml`:

```
 # Criminal Oganizations
 format.lrsk_crimeorg.1: "[This.GetSpeciesAdj] <lrsk_stellar_filler_desc><lrsk_criminal>"
 format.lrsk_crimeorg.2: "<lrsk_stellar_filler_desc><lrsk_criminal> of [This.Capital.System.GetName]"
 format.lrsk_crimeorg.3: "<lrsk_stellar_filler_desc><lrsk_criminal> of [This.Capital.GetName]"
```

This format has three variations for names based on the species name, the homeworld, and the home system star. They use the following tokens to define possible pieces of a name:

```
# Criminal Noun
empire_name_parts_list = {
	key = "lrsk_criminal"
	parts = {
		"Syndicate" = 3
		"Consortium" = 2
		"Cartel" = 3
		"Combine" = 2
		"Concern" = 1
		"Organization" = 1
		"Ring" = 1
		"Group" = 1
		"Gang" = 1
	}
}

# Stellar Filler (Optional)
empire_name_parts_list = {
	key = "lrsk_stellar_filler_desc"
	parts = {
		"Interstellar " = 1
		"Interplanetary " = 1
		"Galactic " = 1
		"Stellar " = 1
		"Star " = 1
		"" = 5
	}
}
```

A typical name for an applicable government would be "Human Galactic Cartel" or "Gang of Earth".

This differs from the base game which defines Criminal Syndicate names as follows:

```
### In localisation_synced/empire_formats.yml
 format.monopolistic_syndicate.1: "[This.GetSpeciesName] <monopolistic_syndicate>"
```
```
### In common/00_empire_names.txt
# Criminal Syndicate
empire_name_parts_list = {
	key = "monopolistic_syndicate"
	parts = {
		"Syndicate" = 6
		"Consortium" = 2
		"Cartel" = 4
		"Combine" = 2
		"Monopoly" = 3
		"Concern" = 1
	}
}

# Criminal Syndicate
empire_name_format = {
	random_weight = {
		factor = 0
		modifier = {
			add = 5
			has_government = "gov_criminal_syndicate"
			is_pirate = no
			is_primitive = no
			NOT = { is_country_type = fallen_empire }
			NOT = { is_country_type = awakened_fallen_empire }
		}
	}
	format = "format.monopolistic_syndicate.1"
	noun = "[This.GetSpeciesName]"
	prefix_format = "[This.GetSpeciesName] <monopolistic_syndicate>"
	# Human Empire
}
```

The base game name logic would never be able to generate one of the names I listed above because it only uses the species name as a basis, has no "stellar" adjective, and draws from a shorter list of nouns. 

I was able to generate names based on my mod-added name format for both a Criminal Syndicate and a Crime Family government, despite their potential being defined in two separate blocks.

To replicate:
1. Install Government Variety Pack
2. Load Stellaris with Government Variety Pack and no other mod loaded.
3. Create a Criminal Syndicate with a defined species, home planet, and home star name.
4. Go to the "Empire Name" section and hit the randomizer (dice) button until you see names conforming to my name format (i.e., uses something other than species name as a basis, has a "stellar" adjective, and/or uses one of the new nouns I added) and not the base game format.
4. Change government to a Crime Family (requires Merchant Guilds, Barbaric Despoilers, and Imperial authority).
6. Repeat step 4.

You should see the same results that I did. These results indicate that a "conflict" based on two `empire_name_format` blocks using the same `format` is not a real conflict and should not be flagged as such.
