### ISSUE TITLE
Change Merge suffix to prefix

### ISSUE THREAD

**Issue by Deliphin** [bcssov/IronyModManager#150]
**Is your feature request related to a problem? Please describe.**
Very minor issue. When you have merges in your left pane mod list, they can be anywhere when it's sorted by name.  
It's mildly annoying to try to search a massive list for a couple new mods, spotting a disabled mod, then realizing it's just the Merge from another mod list.

**Describe the solution you'd like**
Change the (Merged) suffix into a prefix. So basically change it from:  
Modpack (Merged)  
to:   
(Merged) Modpack

This would force all merged mods to be grouped together and therefore more organized.

**Describe alternatives you've considered**
Merges could be put in a separate pane below the mods, since the left pane isn't important for load order or anything.

**Comment by bcssov** [comment]
Sorry but no as Irony does not differentiate "Merged" mods with normal mods. There's nothing stopping you from renaming a mod in the <mod-descriptor>.mod manually to something else.

**Comment by Deliphin** [comment]
I'm not asking you to differentiate them, just to change the default name for merged mods. By alphabetical sorting, it'll sort itself. I know I can change it myself, but it'd be less annoying for me, and more importantly, less annoying for anyone else in the future running more than one stellaris mod list.

**Comment by bcssov** [comment]
Sorry my answer is still no. This is a matter of a personal preference really and I prefer to use suffix instead of prefix in this use case.
