### ISSUE TITLE
Table Columns - Standard Window Add Columns for Key Info

### ISSUE THREAD

**Issue by DiettingerX** [bcssov/IronyModManager#153]
Irony works really well. Thanks you.

I merge mods together for Stellaris, and periodically I get a message from Irony Mod Manager that some of the mods I have integrated have been updated. This is a problem because I do not know which mod was updated without looking it up... and I have merged 20+ mods.

It would be useful if the two tables had the standard windows thing of being able to select which columns they contain. Then I could add columns such as "last modified", author, or such.

One other thing... the move mods up and down. Drag and drop would be nice... or a drop down which would move the mod to a position number (cuz from the bottom can be an exercise) ... not necessary... but nice. Those up and down buttons are tiny and it is a bit of a click fest...

**Comment by bcssov** [comment]
> I merge mods together for Stellaris, and periodically I get a message from Irony Mod Manager that some of the mods I have integrated have been updated. This is a problem because I do not know which mod was updated without looking it up... and I have merged 20+ mods.
> It would be useful if the two tables had the standard windows thing of being able to select which columns they contain. Then I could add columns such as "last modified", author, or such.

This is a conflict solver message and it's a signal from it that you need to re-run and re-check it. This is not a message that a mod was updated which shows at all times. 
Conflict solver will only notify you in instances where you have a Irony patch mod active and you might need to check for new conflicts in cases where a mod was changed in some way. The mod patch I'm talking about is auto created and is invisible in Irony but you can confirm its existence by the naming convention in your mod directory following this scheme: IronyModManager_{name of your mod collection}.
Note: You should not run conflict solver on merged mod collections.

> One other thing... the move mods up and down. Drag and drop would be nice... or a drop down which would move the mod to a position number (cuz from the bottom can be an exercise) ... not necessary... but nice. Those up and down buttons are tiny and it is a bit of a click fest...

In collection mods area you can already drag and drop mods. As well as use the numeric textbox to enter a position directly by typing a number. Or use the buttons on the left side of the textbox which move a mod directly to top\bottom respectively.

**Comment by DiettingerX** [comment]
Thanks for the reply. You pointed out a number of features I had not identified yet. I watched a YouTube video... it may have been stale.
The point on not using the Conflict Solver on merged mods was very important.
I think it is a great tool!

Mark
