### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by RobAllen0** [bcssov/IronyModManager#154]
**Describe the bug**
Crash on launch:
Fatal Error
Unhandled error occurred.  App will close automatically.

**To Reproduce**
1. Launch Application
2. Error occurs.
3. 
4. 

**Expected behavior**
Successful launch

**Screenshots**
![crash](https://user-images.githubusercontent.com/74681367/99581781-733ed000-299e-11eb-942b-ffedaaaf4a67.png)

**Logs**
[2020-11-18_Error.log](https://github.com/bcssov/IronyModManager/files/5562469/2020-11-18_Error.log)

**Version:**
 - OS: Windows 10
 - Irony Version 1.8.60

**Additional context**

**Comment by bcssov** [comment]
One of the mods you have installed either in Docs\Paradox Interactive\Stellaris\mod or steam\steamapps\workshop\content\{stellaris appid} has a faulty zip archive and Irony crashes attempting to read it to see what kind of a mod it is.

Resolution: Find the offending archive and repackage it or something.

**Comment by RobAllen0** [comment]
Okay, thanks.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
