### ISSUE TITLE
Compress merge not working?

### ISSUE THREAD

**Issue by Az0na** [bcssov/IronyModManager#158]
**Describe the bug**
Selecting compressed with merge option Stellaris

**To Reproduce**
1. Merge with Compressed option.
2. apply merged thingy.
3. launche Stellaris
4. no mods loaded just base game.

**Expected behavior**
to load mods.

**Version:**
 - OS: Windows 10
 - Irony Version [V1.9.50]

if I do something wrong let me know. I found my almoste 10 GB mods down to almoste 3 GB a win if it worked.

**Comment by bcssov** [comment]
Works fine for me and many of my friends so it's probably something on your end. I can't say what you did wrong. 

1. Maybe you did not apply the Irony collection 
2. Maybe you launched paradox launcher and selected a different playset 
3. Maybe the game somehow decided to delete the generated descriptors.
4. Maybe descriptors need to be refreshed

In case of 3 lock the descriptors using Irony or set the readonly flag to all descriptor files. In case of 4 use Irony option to delete and reload all descriptors.

**Comment by Az0na** [comment]
All I did. installed my mods fresh as everytime I update my mods and it list I make sure its clean. this means Mod folder is empty before I subscripe to all my mods and wait for steam to do its thing. launched mod manager. put all mods in correct order for loading. and hit merge. chose compressed option, wait long ass time for it to be done, apply and launche game trough manager and launched as it had no mods.

when I use basic merge works fine but yeah merged file is 10GB. ill try again later as I just wanne play with my friend.

https://steamcommunity.com/workshop/filedetails/?id=1762505614 is my collection and also mod list to import

**Comment by bcssov** [comment]
Your problem lies in 3 or 4 then. Try one of these solutions, but this is a **game** problem not Irony problem. I'm publishing a new version which should automatically lock these types of descriptors by setting the readonly flag but this is ultimately a game (Stellaris) problem.

**Comment by Az0na** [comment]
Okey I tried again and now does work. dunno why suddenly it does. did the same thing as before.

Oh whel I just wanne say thank you very much for this tool. saves me and my friend lot of headache to play together and every time I add or remove mod :). this makes it so much better and easier and now also saves some disc space :)

keep up the good work.
