### ISSUE TITLE
Wildcard Ignore Rules issue

### ISSUE THREAD

**Issue by Dukko** [bcssov/IronyModManager#161]
**Describe the bug**
I tried to wildcard out a bunch of buildings with similar names (_building_ae__etc) by using building_ae_* but the wildcard is not hiding the files in conflict resolver. 
Easy to reproduce by adding Ancient Cache of Technologies, Acquisition of Technology, and running conflict checker (and try to wildcard out all the duplicate buildings).

**Expected behavior**
The wildcard hides the buildings. 

**Version:**
 - OS: Windows 10
 - Irony Version 1.9.58

**Comment by bcssov** [comment]
That's not the supported scenario for wild cards. It supports filtering filenames not object names.
