### ISSUE TITLE
Fatal Error Crash

### ISSUE THREAD

**Issue by ctsv4vendetta** [bcssov/IronyModManager#162]
**Describe the bug**
Maybe I'm dumb and messed something up but I get a "Fatal Error" when clicking "import" and it closes the app.

**To Reproduce**
1. Open Mod Manager
2. Click "Import"
3. 
4. 

**Expected behavior**
Allow me to import mod list

**Screenshots**
![Untitled-1](https://user-images.githubusercontent.com/64762655/101404000-a4266c80-389b-11eb-8173-a51ecc32fa10.jpg)

**Logs**
I'm not super savvy and don't know where to find these

**Version:**
 - OS: windows 10
 - Irony Version 1.9.58 and 1.9.63

**Additional context**
I got the same "fatal error" also when clicking "configure" in the options tab.

**Comment by bcssov** [comment]
No logs, no support.

**Comment by ctsv4vendetta** [comment]
Thanks for the snarky reply. I figured it out anyway. 👍🏼
