### ISSUE TITLE
Irony will not start

### ISSUE THREAD

**Issue by MichalSafar** [bcssov/IronyModManager#165]
**Describe the bug**
I downloaded the IronyModManager but it will not launch. I tried 1.9.63, 1.8.latest, 1.7.latest - portable version or intaller. I tried to start it as a admin or through cmd - nothing happens.

**Expected behavior**
When I double-click the exe file it should start but nothing.

**Version:**
 - OS: Windows 7 - x64
 - Irony Version 1.9.63, 1.8.latest, 1.7.latest

**Comment by bcssov** [comment]
Irony logs or windows event viewer otherwise I can't help you.

**Comment by MichalSafar** [comment]
Thank you so much. I did not know that event viewer even exist in win7. I had an issue win Microsoft C++ 2015. I reinstalled it and all is fine. I am sorry that I add the "bug" on Irony - I really thought it is an bug.
