### ISSUE TITLE
Manager crashes while starting up

### ISSUE THREAD

**Issue by dan3401** [bcssov/IronyModManager#168]
**Describe the bug**
When the mod manager is launching it gets to the "please wait while loading mod data" for 2 mins then it crashes

**To Reproduce**
1. Boot launcher 
2. wait
3. manager should crash 

**Expected behavior**
Should pass the loading mod data step and allow the manager to load

**Screenshots**
![image](https://user-images.githubusercontent.com/13206890/102927586-2794b000-448f-11eb-88d0-e495d755f1f1.png)

**Logs**
https://pastebin.com/ridDtgeW

**Version:**
 - OS: windows 10 ver 20H2
 - Irony Version Tested on ver 1.10.51 to 1.10.58

**Additional context**
While I have tested it on older versions this is a recent problem e.g. today.
The last thing i did was merge some mods together to upload as an unlisted mod. I edited the mods descriptors (and folder) to rename it. Initially the default launcher didn't "see" the mod after starting the mod manager.  after launching the game (i think it deleted a descriptor) though irony the normal launcher could "see" the mod but not upload it. After deleting the mod files to try to remerge it the launcher has this issue. 
I had a similar issue before (didn't check the logs tho) but i can't remember how i fixed it.

**Comment by bcssov** [comment]
You have an invalid zip somewhere where Irony is searching causing it to crash.

**Comment by dan3401** [comment]
Ah, i had a zipped file with the same name as the mod that i was trying to upload that was invalid which was causing the issue. fixed now thanks for the quick reply and the help
