### ISSUE TITLE
Won't load playset into Stellaris or Paradox Launcher

### ISSUE THREAD

**Issue by jabjoe123** [bcssov/IronyModManager#171]
I installed IMM for a friend and did exactly the same things I did for my setup, but it doesnt load the mods for him.
When he launches the game with the applied Modlist, it just starts the Vanilla game without mods.
No starting arguments, fresh install of Stellaris 2.8.1

**Comment by bcssov** [comment]
Watch the video tutorial. Aside from that don't modify anything in the paradox launcher before you launch the game. Ensure that Irony is not throwing any error messages as well when applying mod collection (AV can prevent Irony from applying the mod collection).

**Comment by jabjoe123** [comment]
We'll try to reinstall Stellaris and the Paradox launcher clean and disable the AV while applying the mods.
Thanks for your quick reply. Your Mod-Manager is awesome. I wish you a nice christmas eve ^^

**Comment by bcssov** [comment]
Reinstalling Stellaris will not help. It's dlc_load.json that's important. That's what holds the mod load order, check the error.log and maybe attempt to rebuild descriptors with Irony (Delete all and reload).
