### ISSUE TITLE
Mod Filter - Show only conflicts with a particular mod

### ISSUE THREAD

**Issue by zedr0n** [bcssov/IronyModManager#172]
**Describe the solution you'd like**
A relatively simple extension to mod filter where we could specify that it should only show conflicts with files which are present in a particular mod. This would allow checking how a particular mod changes an existing playset.

**Describe alternatives you've considered**
It's entirely possible to keep all the conflicts resolved then adding a new mod as this would only show the conflicts coming from the additional mod but with a large amount of mods I do tend to regenerate the playsets and just seeing particular mod conflicts is useful. 
At the moment I have the mod folder open to manually filter on the files present in the mod.

**Comment by bcssov** [comment]
If you select only a single mod that should mimic what you want no?

Mod filter works by showing intersecting conflicts. I believe I code this in the following manner:
> If you exclude Mod A but Mod B is not excluded it'll still show Mod A conflicts due to intersecting rule with Mod B conflicts being included.

**Comment by zedr0n** [comment]
ah, yes, my bad, ignore 👍
