### ISSUE TITLE
Problems with dependency loading on Arch Linux

### ISSUE THREAD

**Issue by Zetabite** [bcssov/IronyModManager#181]
**Describe the bug**
IMM crashes when opening

**To Reproduce**
1. Install package from AUR
2. Start
3. IMM opens

**Terminal Output**
```
Error:
  An assembly specified in the application dependencies manifest (IronyModManager.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.linux-x64', version: '5.0.1'
    path: 'libSystem.IO.Compression.Native.a'
```

**Version:**
 - OS: Arch Linux (5.10.7-zen1-1-zen)
 - Irony Version: 1.10.65

**Additional context**
Fixed by applying this diff: `https://aur.archlinux.org/cgit/aur.git/tree/fixed-jsons.diff?h=irony-mod-manager-bin`

**Comment by bcssov** [comment]
Tide to #119
