### ISSUE TITLE
Ignore mod self-conflicts

### ISSUE THREAD

**Issue by conchors** [bcssov/IronyModManager#182]
**Is your feature request related to a problem? Please describe.**
It's frustrating going through mods like ESC 3.0 which include both pngs and .dds versions of graphics for performance, and having to sift through any self conflicts
**Describe the solution you'd like**
I would like a toggle to ignore any conflict a mod has with itself, so as to just look for things that will cause issues between multiple mods
**Describe alternatives you've considered**
A dedicated ignore rule method for this would work too. So would a way to select multiple conflicts to ignore at once in the UI, a click and drag or shift-click
**Additional context**
![image](https://user-images.githubusercontent.com/27566384/104819370-09567180-57fb-11eb-9dd7-722bdfad5555.png)

**Comment by bcssov** [comment]
NOTE: Multiple conflict selection no.
