### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by nanozine** [bcssov/IronyModManager#184]
Add keyboard shortcuts

(May already exist but I don't see a tooltip for it)

**Comment by bcssov** [comment]
For which actions? What would be the suggested hotkeys?

**Comment by nanozine** [comment]
Sorry for being so vague in my original post. Here's some ideas:

Main Menu:
ctrl up/down: change the order of mods
ctrl shift up/down: move mod to top/bottom
(also as a sidenote I can't change mod order by typing a number into the order menu but IDK if that was meant to be a function or not. E.g I can't change the "1" to "92". This is on the Mac version)
<img width="448" alt="Screen Shot 2021-01-22 at 4 33 41 pm" src="https://user-images.githubusercontent.com/77813595/105450906-9869fa80-5ccf-11eb-99e7-916456bc919f.png">


Conflict solver:
(once again unrelated but would it be possible to cache the mod definitions when loading up the conflict manager somehow? It's kinda annoying having to wait for so long. The cache would only get used if there weren't any new/removed mods though)
Ctrl Z: undo
Ctrl up/down: jump to next/previous conflict
shift up/down: the shortcut that currently exists for ctrl up/down (jump to next/prev file)
Ctrl shift up/down: move line of code up/down
1, 2, 3, 4, 5, etc: change which file you're viewing on the left side 
<img width="427" alt="Screen Shot 2021-01-22 at 4 51 24 pm" src="https://user-images.githubusercontent.com/77813595/105452233-129b7e80-5cd2-11eb-80d5-49fbba158259.png">
(These) 
ctrl [ and ctrl ]: Move to next/previous mod folder
I or ctrl I: Ignore Conflict (Please)
R or Ctrl R: Resolve Conflict
E or Ctrl E: Edit
Ctrl A: Select all
Ctrl Shift A: Copy all (may be a bit unintuitive)
Ctrl C: Copy Text
Ctrl Shift C: Copy this
Ctrl Shift up C: Copy this before line (this may be a bit too convoluted)
Ctrl Shift down C: Copy this after line (this may be a bit too convoluted)

BTW thank you so much for making this manager. I can finally run my own modpack without getting overwhelmed by bugs!

**Comment by bcssov** [comment]
> (also as a sidenote I can't change mod order by typing a number into the order menu but IDK if that was meant to be a function or not. E.g I can't change the "1" to "92". This is on the Mac version)
Focus the textbox and then type in a number (this is a textbox control)

> (once again unrelated but would it be possible to cache the mod definitions when loading up the conflict manager somehow? It's kinda annoying having to wait for so long. The cache would only get used if there weren't any new/removed mods though)

Possible yes. Will I do it? No. Why? Too complex logic is needed to track when to invalidate when to not.
