### ISSUE TITLE
Decimal point changes count as conflicts

### ISSUE THREAD

**Issue by nanozine** [bcssov/IronyModManager#185]
**Is your feature request related to a problem? Please describe.**
Decimal point changes count as conflicts
<img width="784" alt="Screen Shot 2021-01-22 at 11 31 44 am" src="https://user-images.githubusercontent.com/77813595/105429373-69d72a00-5ca5-11eb-8c89-4e3323c645e6.png">

**Describe the solution you'd like**
Add a setting or something similar to ignore decimal points when they result in the same value

**Comment by bcssov** [comment]
Rejected, Irony does not understand the game code only syntax.
