### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by FITZ171** [bcssov/IronyModManager#186]
**Describe the bug**
crashes on startup. displays message: Fatal error app will close on its own.

**To Reproduce**
1. start program

**Additional context**
I've tried reinstalling several times it just says Fatal error and closes.

**Comment by bcssov** [comment]
Fatal error is a generic error so you must provide Irony error logs. Please see the homepage rules about reporting a crash report and for the location of the logs.

**Comment by FITZ171** [comment]
ive deleted all files and uninstalled about 10 times but it still tries to load up a non existant mod and crashes, there seems to be nothing i can do, i cant seem to find out how its reloading something after deleing and reinstalling?

**Comment by FITZ171** [comment]
all the error logs are deleted

**Comment by FITZ171** [comment]
any ideas?

**Comment by FITZ171** [comment]
[2021-01-26_Error.log](https://github.com/bcssov/IronyModManager/files/5874010/2021-01-26_Error.log)
