### ISSUE TITLE
Fatal Error Problem

### ISSUE THREAD

**Issue by FITZ171** [bcssov/IronyModManager#187]
**Describe the bug**
hi, i have not used your mod manger before but have used others such as the nexus mod manager. i installed IMM yesterday and immediately tried to merge two mods as a test to try and see what would happen, it got to 75% and then had a fatal error and closed. now every time i try to start the program up it, no matter how many times i delete all the data that i can find related to the mod manager, it just loads up this same configuration and crashes. would appreciate your help.

**Logs**
[2021-01-26_Error.log](https://github.com/bcssov/IronyModManager/files/5874017/2021-01-26_Error.log)

**Comment by bcssov** [comment]
Delete the offending failed mod collection folder in the stellaris mod directory. The directory should be prefixed with the "merged" keyword and contain the name of your collection that you use to attempt the merge.
