### ISSUE TITLE
Crash shortly after launch

### ISSUE THREAD

**Issue by APasz** [bcssov/IronyModManager#188]
Pretty simple.
Launch via './IronyModManager'.
Only window titlebar and two icons on taskbar.
Several seconds later CTD.

[2021-01-28_Error.log](https://github.com/bcssov/IronyModManager/files/5886821/2021-01-28_Error.log)
[https://pastebin.com/SMNKw9Tt]

Irony 1.10.70
Ubuntu 20.10
KDE 5.19.5
KDE Frameworks 5.74.0
Qt 5.14.2
Kernel 5.8.0-41
Nvidia 460.32

**Comment by bcssov** [comment]
Long ago I did a test of Irony on Ubuntu and it did work (in a VM). But anyway the exception is an upstream issue cause by either software or hardware or driver combo (maybe), there's not much I can do. You could try setting UseGPU option to false:
https://github.com/bcssov/IronyModManager/blob/16f7caa686fc0e532a6870f7dad86a3fa7f6a289/src/IronyModManager/appSettings.json#L6

There are also more Linux specific options available:
https://github.com/bcssov/IronyModManager/blob/16f7caa686fc0e532a6870f7dad86a3fa7f6a289/src/IronyModManager/appSettings.json#L6-L9

**Comment by APasz** [comment]
Ok I've tried various configurations of those settings.
Same behaviour and error.
Only deferredRendering has any effect. Being that a full white window is drawn however it's fake.
Also only with derredRendering, when the compositor is set to XRender mode, the renderer will lock up as well.
OGL2 and 3.1 have no difference.

**Comment by bcssov** [comment]
Try deleting any files found in .config/Mario/IronyModManager (if there are any). If not there is nothing I can do really.

For reference this would be a test VM I booted to verify whether Irony still works.

![1](https://user-images.githubusercontent.com/5864390/106169300-87b5fa80-618f-11eb-8af1-69dfcfd273b0.png)

**Comment by APasz** [comment]
Only file was 'Database_1.10.json'.
Tried a few configurations again, deleting the json file in between each test.
No change.

It could be a KDE specific issue.
I'll install GNOME DE and test again.

**Comment by APasz** [comment]
Nope. Same behaviour except it crashes the session.
¯\_(ツ)_/¯ dunno mate

**Comment by bcssov** [comment]
You're out of luck then sadly. Maybe bumping Avalonia dependency to 0.10 would fix the issue for you but that's a lengthy procedure at the moment and I'm really taking a break from Irony as well (burnout).
