### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by mc1790** [bcssov/IronyModManager#190]
Fresh install of latest version crashes on launch.

[2021-01-28_Error.log](https://github.com/bcssov/IronyModManager/files/5891592/2021-01-28_Error.log)

And I have no idea why. I've tried the installer version, as well as the portable, and even went back a version and still no dice. Not sure what the issue is, but maybe my pc is missing something? Log attached above.

Also, there are a boatload of mods installed via workshop, yet for the moment or two I do see the app up it only shows a handful before crashing.

**Comment by bcssov** [comment]
You have a mod which is an archive and is corrupt. When Irony attempts to scan this archive it crashes due to this reason.

Solution: 
Find the offending zip and delete it. Look in:
1. Stellaris mod directory
2. Steam workshop directory
Unfortunately the logs don't tell me which zip it is.

**Comment by mc1790** [comment]
Thank you, i'll start looking. There's around 100+ mods so this will be fun.

**Comment by bcssov** [comment]
Zip mods are rare so if you use a tool like [Everything](https://www.voidtools.com/) you could find only zip files in the mod directory location.

**Comment by mc1790** [comment]
you think extracting all the zips would be the best way to deal with it?
