### ISSUE TITLE
Unable to apply mods

### ISSUE THREAD

**Issue by kevinmulligan** [bcssov/IronyModManager#191]
Apply fails with the message: "Save Error: Something seems to be locking Irony's ability to write to mod files. Please report this on GitHub issue tracker and post the error log."

**To Reproduce**
Hit apply after selecting 1 or more mods.

**Expected behavior**
Mods should apply.

**Screenshots**
N/A

**Logs**
[2021-01-29_Error.log](https://github.com/bcssov/IronyModManager/files/5896936/2021-01-29_Error.log)

**Version:**
 - OS: Windows 10 (10.0.19041)
 - Irony Version: 1.11.27

**Additional context**
I just installed Irony, and have never used it before. I have tried running as admin, which did not work.

**Comment by bcssov** [comment]
As the error log states ` SQLite Error 8: 'attempt to write a readonly database` it would appear that your `launcher-v2.sqlite` file is set to readonly? Or you are not the owner of the said file. Basically something seems to prevent Irony from accessing it and writing to it.

**Comment by kevinmulligan** [comment]
Permissions were fine. Turns out it was Anti-Virus blocking it from modifying files. It didn't tell me that's what it was doing yesterday, but today when I tried again I got a popup that it was blocked. Added an exception and it seems to work fine now. Thanks for your help.
