### ISSUE TITLE
 "please wait while loading mod data"

### ISSUE THREAD

**Issue by FITZ171** [bcssov/IronyModManager#193]
**Describe the bug**
hi I finally got the mod manager to open, merged one mod, tried to play the game for 10 mins as a test, then returned and it is stuck on "please wait while loading mod data" it never showed this screen the other two times I managed to make it work. and now every time I reinstall it goes to the same screen, cant click off or make it stop "loading" the data.
**To Reproduce**
take any action,

**Comment by OldEnt** [comment]
Anyone stumbling on this: You can purge Irony settings and it usually unstucks.
Delete `C:\Users\%USERNAME%\AppData\Roaming\Mario\IronyModManager\` folder.

**Comment by bcssov** [comment]
Don't delete anything. You'll just reset your settings without further understanding the problem which might or more likely might not have anything to do with the underlying issue.
