### ISSUE TITLE
Automatic/Mass Conflict Resolution

### ISSUE THREAD

**Issue by Spodeian** [bcssov/IronyModManager#196]
**Is your feature request related to a problem? Please describe.**
2000+ conflicts is a lot and would take perhaps 30 minutes to click through.

**Describe the solution you'd like**
I would like a button that just resolves all conflicts, perhaps with the option to exclude some as specified.

**Describe alternatives you've considered**
Some method of reviewing conflicts more quickly and either marking them to be resolved or having it so that resolving them sends you on to the next conflict immediately and resolves in the background.

**Comment by bcssov** [comment]
Universal automatic conflict resolution is not possible. This is possibly n way merge and not a system where you pick "use x" to make all my problems go away. 
Having said that there are tickets here which will attempt to resolve vanilla conflicts therefore this ticket is in that sense a duplicate.
