### ISSUE TITLE
Highlight file conflicts

### ISSUE THREAD

**Issue by bcssov** [bcssov/IronyModManager#20]
Not a priority but apparently useful to some people.

**Comment by LordOfLA** [comment]
I would envisage this as when I click on a mod in the load order list, it highlights mods it conflicts with

**Comment by bcssov** [comment]
That doesn't potentially allow you to see all mods. It would be useful in combination with a window that opens and shows a full list.

**Comment by LordOfLA** [comment]
Not really, if it highlights the mods I can see where I want to do some basic positioning before heading into the conflict resolver.

The mod manager I use for Skyrim (Mod Organiser 2) will highlight every mod overwriting the mod I selected in red and all the mods that are being overwritten by my selected mod in green.

With that, I could place files as desired before heading into the conflict solver to patch definition conflicts.

**Comment by bcssov** [comment]
I'm not too fond of such an idea. More investigation and comparisons are necessary. This is only use use case that you described, it needs more viewpoints.

**Comment by LordOfLA** [comment]
Yeah, that's fine. It just occurred to me to expand on what I was thinking when I first suggested the idea.

**Comment by Hasselshoff** [comment]
I have expanded on this idea in #387. Have a look at my suggested implementations and offer any feedback please!
