### ISSUE TITLE
Unable to write mod file through manager

### ISSUE THREAD

**Issue by GraveKeeper916** [bcssov/IronyModManager#200]
Recently I have been having issues with the manager not being able to write mod files. It says that it is being blocked but I cannot see why.
[2021-02-22_Error.log](https://github.com/bcssov/IronyModManager/files/6026076/2021-02-22_Error.log)

**Comment by bcssov** [comment]
Corrupt json in the Stellaris docs folder either:
1. dlc_load.json
2. game_data.json
3. mods_registry.json
Solution: Delete the offending json or all of them.
