### ISSUE TITLE
Option to store merged data in steamapps\workshop folder instead of Windows my Documents folder.

### ISSUE THREAD

**Issue by Droiyan7** [bcssov/IronyModManager#201]
Reason: It causes serious problems with MS OneDrive sync (lots of unneeded traffic, out of the capacity of free account)

Suggestion: Add an option to use steamapps\workshop folder instead

like
path="c:/~~~/steam/steamapps/workshop/content/281990/(Merged)_ZOFE"
instead of
path="C:/Users/~~~~/OneDrive/Documents/Paradox Interactive/Stellaris/mod/(Merged)_ZOFE" (which is IronyModManager v1.12.93-rc currently using in Windows environment)

P.S: I have paid 1TB MS OneDrive account also, but it cannot be the answer.
 - It's Korean University account, not my personal own, syncing with it causes a full folder path like
C:\Users\~~~\OneDrive - kaist.ac.kr\Documents\Paradox Interactive\Stellaris

and I don't think a PDX game can read path like "OneDrive - kaist.ac.kr" without causing lots, lots of errors.

and even if it did, it cannot help lots of unneeded traffic and OneDrive capacity wasted.

**Comment by bcssov** [comment]
Sorry but no, Irony respects the PDX Launcher logic. Move your own documents folder outside of the mentioned drive.
