### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by halfwalk** [bcssov/IronyModManager#207]
The app crashes on attempting to launch, giving a dialog:

Fatal Error
Unhandled error occurred. App will close automatically.

Tried with v1.12.126, and have attached the log.
Trying with v1.13.80-alpha has the same crash, but does not generate a log at all.

I've tried with both the portable and the installed version, and the error log it generates (from 1.12.126) is identical for each.

Also curious about the `  at IronyModManager.Program.Main(String[] args) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 86` bit, as I don't even have a D drive.

[2021-03-17_Error.log](https://github.com/bcssov/IronyModManager/files/6159499/2021-03-17_Error.log)

Edit: Windows 10 x64 build 17763 (version 1809)

**Comment by bcssov** [comment]
Nothing curious about the D drive as that is where Jenkins is located on my virtual machine where the source was compiled and it's debug information meant for me.
1.13 has moved the log location to %appdata%\mario\ironymodmanager-logs check there and share 1.13 logs with me. The error is basically related to an upstream issue and it has very little in terms of diagnostics for me. 
Try the following to gather more data:
1. Open appSettings.json and set from 
```"EnableAvaloniaLogger": false```
to
```"EnableAvaloniaLogger": true```
Then run 1.13 and share the logs then with me.
2. Try deleting %appdata%\mario\ironymodmanager directory (back it up as this is where irony settings are located) and try to run irony then.
