### ISSUE TITLE
Conflict Solver Resolve save error

### ISSUE THREAD

**Issue by fondestgreetings** [bcssov/IronyModManager#208]
I don't really what is causing this issue, I turned off the AV, and I ran the Mod manager with Admin rights.
[2021-03-18_Error.log](https://github.com/bcssov/IronyModManager/files/6161655/2021-03-18_Error.log)

**Comment by bcssov** [comment]
launcher-v2.sqlite is corrupt delete it.

**Comment by fondestgreetings** [comment]
Ah.
