### ISSUE TITLE
Repeat mod entries (of same value) when viewing mod variable conflict

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#21]
https://i.imgur.com/OVkYkiE.png as an example.

Also, present on @rotationspeed

Narrowed it down to Amazing Ship Battles (https://steamcommunity.com/sharedfiles/filedetails/?id=1878473679) and Extra Ship Components 3.0 - Overwrites (https://steamcommunity.com/sharedfiles/filedetails/?id=1885791325)

**Comment by bcssov** [comment]
Should be resolved with #17
