### ISSUE TITLE
Feature Request: Maintain Reset Conflicts window position/possible multiple selections

### ISSUE THREAD

**Issue by i2amroy** [bcssov/IronyModManager#211]
So I'm absolutely loving the conflict solver, but there's been a few times while resolving where I've gotten into a groove and haven't noticed that some definitions needed extra attention until after I've clicked resolve on like 30 of a given hierarchy.

Unfortunately then to reset a whole bunch of conflicts at once the workflow ends up looking something like this:

1. Click "Reset Conflicts"
2. Click on the dropdown menu to select the hierarchy I want.
3. Scroll all of the way to the bottom to find the last one I was working on.
4. Scroll all of the way through 200+ merged definitions that I've already done to reach the first definition that I want to reset.
5. Click reset on a single definition, at which point it resets the "Reset Conflicts" window completely.
6. Repeat steps 2-5 complete with redoing all of the scrolling individually for each of the 30+ definitions I need to reset.

Having the ability to select multiple definitions to reset them at once, or at a minimum having the Reset Conflicts window remember where I am so I don't need to rescroll back through all the hierarchy options and all the already merged definitions 20+ times would be a _huge_ timesaver in cases like that.

**Comment by bcssov** [comment]
That would definitely improve the UX a bit. I'll try to squeeze it in 1.13 release window (which is currently in RC stage)
