### ISSUE TITLE
Irony Mod Manager will not start

### ISSUE THREAD

**Issue by balencedrago** [bcssov/IronyModManager#220]
Upon attempting to start the app, i receive a fatal error message and the app closes itself. I have uninstalled it and reinstalled it several times, tried out different versions, ect ect. I am on windows 10. I worked fine2 days ago, now it wont even open. 

**To Reproduce**

1.  Start irony mod manager on windows 10
2. 
3. 
4. 

**Expected behavior**
The mod manager opens

**Version:**
 - OS: Windows 10
![2021-03-26](https://user-images.githubusercontent.com/81403531/112585343-9f90b000-8dc7-11eb-821f-d0d88e6a6d19.png)

 - Irony Version: 1.13.116

**Additional context**

**Comment by bcssov** [comment]
Logs, homepage tells you everything you need to know about how to submit a bug report: https://bcssov.github.io/IronyModManager/

**Comment by balencedrago** [comment]
Typing %AppData%\Mario\IronyModManager into my search brings me to a JSON file. Im not very good at computers so im sorry if im not doing this correctly, but heres the json file contents. 

[{"Type":"IronyModManager.Models.AppState","Name":"AppState","Value":{"CollectionJumpOnPositionChange":false,"CollectionModsSearchTerm":null,"CollectionModsSelectedMod":null,"CollectionModsSortColumn":"modName","InstalledModsSearchTerm":null,"InstalledModsSortColumn":"modSelected","InstalledModsSortMode":1,"LastWritableCheck":"2021-03-24T17:12:35.7221309-05:00"}},{"Type":"IEnumerable<IronyModManager.Models.GameSettings>","Name":"GameSettings","Value":[{"CloseAppAfterGameLaunch":true,"CustomModDirectory":"","ExecutableLocation":"D:\\SteamLibrary\\steamapps\\common\\Stellaris\\stellaris.exe","LaunchArguments":"-gdpr-compliant","RefreshDescriptors":false,"Type":"Stellaris","UserDirectory":"C:\\Users\\balen\\OneDrive\\Documents\\Paradox Interactive\\Stellaris"}]},{"Type":"IEnumerable<IronyModManager.Models.ModCollection>","Name":"ModCollection","Value":[{"Game":"Stellaris","IsSelected":true,"MergedFolderName":null,"ModNames":[],"Mods":["mod/ugc_1595876588.mod","mod/ugc_1688887083.mod","mod/ugc_2407436476.mod","mod/ugc_1878473679.mod","mod/ugc_1993869579.mod","mod/ugc_1302897684.mod","mod/ugc_902204956.mod","mod/ugc_1227620643.mod","mod/ugc_1100284147.mod","mod/ugc_682090850.mod","mod/ugc_1067631798.mod","mod/ugc_946222466.mod","mod/ugc_681816257.mod","mod/ugc_1586639570.mod","mod/ugc_1885775216.mod","mod/ugc_2104538771.mod","mod/ugc_1121692237.mod","mod/ugc_865040033.mod","mod/ugc_1074841707.mod","mod/ugc_1872228567.mod","mod/ugc_1390963071.mod","mod/ugc_2077186491.mod","mod/ugc_1649338884.mod","mod/ugc_701432146.mod","mod/ugc_727000451.mod","mod/ugc_1407329031.mod","mod/ugc_1660102639.mod","mod/ugc_1867143071.mod","mod/ugc_819148835.mod","mod/ugc_1732437279.mod","mod/ugc_2284514368.mod","mod/ugc_1807850864.mod","mod/ugc_1740165239.mod","mod/ugc_1616934635.mod","mod/ugc_1311725711.mod","mod/ugc_1333526620.mod","mod/ugc_1588303618.mod","mod/ugc_937289339.mod","mod/ugc_684509615.mod","mod/ugc_819007550.mod"],"Name":"Stellaris","PatchModEnabled":true}]},{"Type":"IronyModManager.Models.Preferences","Name":"Preferences","Value":{"AutoUpdates":false,"CheckForPrerelease":false,"ExternalEditorLocation":null,"ExternalEditorParameters":null,"Game":"Stellaris","Locale":null,"NotificationPosition":0,"Theme":null}},{"Type":"IronyModManager.Models.WindowState","Name":"WindowState","Value":{"Height":null,"IsMaximized":true,"LocationX":null,"LocationY":null,"Width":null}}]

**Comment by balencedrago** [comment]
[2021-03-25_Error.log](https://github.com/bcssov/IronyModManager/files/6214596/2021-03-25_Error.log)
[2021-03-26_Error.log](https://github.com/bcssov/IronyModManager/files/6214597/2021-03-26_Error.log)
[2021-03-24_Error.log](https://github.com/bcssov/IronyModManager/files/6214598/2021-03-24_Error.log)

Or maybe you  meant these

**Comment by bcssov** [comment]
Okay, I'm going to need you to:
- Go to %appdata%\mario\ironymodmanager and post database_1.13.json file here for me
- Post your full system specs (CPU, Graphics card, disk and so on)

Then there are a few things you could try on your own to help me determine what could be it:
- Check whether Irony is blocked by some kind of antivirus or by sandbox software that you might have and add irony as an exclusion
- Try checking whether IronyModManager.exe needs to be unblocked (right click on it -> Properties and see whether you see an option stating unblock this program). It should state `this file has come from another computer and might be blocked...`
- Try deleting any files from %appdata%\mario\ironymodmanager directory

Do these troubleshooting steps one at a time and see if any has any effect.

**Comment by balencedrago** [comment]
Deleting the database_1.13json file from  %appdata%\mario\ironymodmanager directory Fixed the issue for me.  I have no idea how it broke in the first place, but that did the trick. Thank you.

**Comment by bcssov** [comment]
While that is all great, that won't help me fix the issue permanently. I asked that you post these files first so I could take a look at them and determine what went wrong and replicate the issue on my own computer so it doesn't happen again.

**Comment by balencedrago** [comment]
Oh i am so sorry, i had began to post them and then deleted the post when the issue was resolved because i didnt want to be a bother. If it happens again ill make sure to record the information
