### ISSUE TITLE
The new UI is much more difficult to parse.  Please revert to the previous UI.

### ISSUE THREAD

**Issue by GrocerOfDespair** [bcssov/IronyModManager#227]
Been away from Stellaris for a little while and I came back to find that the UI for Irony has changed, removing all the lines.  This UI is much more difficult to read and understand quickly, please consider reverting.  It makes for a large increase in the amount of time it takes to work through any mod changes in the conflict solver.

**Comment by bcssov** [comment]
Irony's main UI has not really changed all that much aside from adding new themes. Try some of the others, aside from that there are no plans to revert anything.

**Comment by GrocerOfDespair** [comment]
Ah, I missed the theme change.  User error on my part.  Thanks!
