### ISSUE TITLE
Toggle whether to jump to top/bottom of list when sending a mod there

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#23]
Would be useful to be able to disable having the mod list scroll when I click the send to top/bottom buttons.

**Comment by bcssov** [comment]
Not of critical importance, putting on vNext.

**Comment by LordOfLA** [comment]
Yeah, I figured  I'd put it in as a 'nice to have' feature request.

**Comment by bcssov** [comment]
👍 
I mostly put these comments as notes for myself as well
