### ISSUE TITLE
Dependency on CWTools.Irony-Private

### ISSUE THREAD

**Issue by i2amroy** [bcssov/IronyModManager#232]
Went to spin up a clone of the code to take a look if there was anything I could potentially help out with (can't hurt right) and your dependency appears to be pointing to a local spin off of CWTools rather than the main one, so nuget can't find it to pull down.

Wondering if there are any changes present there that would be necessary to run or if it's safe to just redirect that to the public CWTools package.

**Comment by bcssov** [comment]
I really should push that sometime to GitHub packages or somewhere... But anyway no changes just uhm compiled up to date version of CWTools. Existing nuget is not really up to date.

[CWTools.Irony-Private.0.4.0-alpha4.zip](https://github.com/bcssov/IronyModManager/files/6292686/CWTools.Irony-Private.0.4.0-alpha4.zip)

**Comment by zedr0n** [comment]
there's also some versioning issue with FSharp.Core, I had to include FSharp.Core 4.7.0 as a dependency to IronyModManager.Parser to make it build

**Comment by bcssov** [comment]
I use a local nuget server as well for nugets (makes maintaining consistent nuget versioning easier for me). So it's probably related to that.
