### ISSUE TITLE
Crash when trying to set game folder options

### ISSUE THREAD

**Issue by k3m0sabe** [bcssov/IronyModManager#236]
I have tried using the latest setup and non setup windows versions of the mod manager, and in both, after starting up, setting mods, i try to setup the game folder options before launching the game, and when i click the (...) icon to setup the folder, the program crashes. 

![stellaris 2](https://user-images.githubusercontent.com/83066415/115852511-b0a8fd00-a417-11eb-8e0d-37e10bd2a7c2.png)
![stellaris 1](https://user-images.githubusercontent.com/83066415/115852539-b7377480-a417-11eb-8eb9-02b2e55cfa49.png)
[2021-04-23_Error.log](https://github.com/bcssov/IronyModManager/files/6364354/2021-04-23_Error.log)

Thanks.

**Comment by bcssov** [comment]
Drive labeled B is causing a crash, it's either inaccessible or corrupt.
