### ISSUE TITLE
Add QOL code reading features

### ISSUE THREAD

**Issue by animusyosho** [bcssov/IronyModManager#238]
Is there a possibility of adding syntax highlighting, indentation marking, and such helpful code reading features? 

Perhaps pulling in some of this can be possible:
[tboby/paradox-syntax](https://github.com/tboby/paradox-syntax)
[cwtools/cwtools-vscode](https://github.com/cwtools/cwtools-vscode)

**Comment by bcssov** [comment]
No, the editor is a simple control and it would be very difficult and not worth my time.

**Comment by animusyosho** [comment]
Okay, thanks for considering!
