### ISSUE TITLE
Cannot reset conflicts in left pane

### ISSUE THREAD

**Issue by lxaphir** [bcssov/IronyModManager#239]
**Describe the bug**
Pulldown menus in left pane do not work; cannot select resolved conflicts or use any pulldown selection

**To Reproduce**
1. Attempt pulldown menu use under tumbleweed 20210316
2. 
3. 
4. 

**Expected behavior**
Pulldowns show selections

**Screenshots**

**Logs**
If the application crashed add error logs related to the crash.

**Version:**
 - OS: Tumbleweed 20210316
 - Irony Version 1.15.20

**Additional context**

**Comment by bcssov** [comment]
Yeah, I'm going to need more info...

![Image3](https://user-images.githubusercontent.com/5864390/116191504-b874e400-a72c-11eb-8490-8fd00feee22a.jpg)
