### ISSUE TITLE
Cannot import from Paradox Launcher

### ISSUE THREAD

**Issue by ebudai** [bcssov/IronyModManager#244]
**Describe the bug**
Attempting to import my mod collections from Paradox Launcher does nothing.

**To Reproduce**
1. Click the ... button beside Import on the right-hand pane
2. Click Paradox Launcher
3. Click v above "Patch Mod: not available"

**Expected behavior**
The collections from Paradox Launcher appear

**Version:**
 - OS: Windows 10 
 - Irony Version 1.16.14

edit: forgot reproduction step 2

**Comment by bcssov** [comment]
Per the docs: https://github.com/bcssov/IronyModManager/wiki/Collection-Mods#importing-other-collections
Only active playset from paradox launcher is imported.

**Comment by bcssov** [comment]
Launcher must not be running.

**Comment by ebudai** [comment]
Launcher was not running.  On giving up, I opened Stellaris to see that there was a new playset called IronyModManager which was empty.

**Comment by bcssov** [comment]
That's the reason why nothing was imported. You probably pressed apply or something. Set the playlist you want to import as active and hit import.

**Comment by ebudai** [comment]
This worked.  Thanks!

**Comment by bcssov** [comment]
> edit: on thinking some, would it not be better to throw an error rather than create a new playlist in the event the new user presses apply or something?

No. That's the whole point of apply button to apply the mod collection from Irony to the game and paradox launcher.
