### ISSUE TITLE
Enable compact view even when few subscribed mods

### ISSUE THREAD

**Issue by bestekov** [bcssov/IronyModManager#248]
**Describe the solution you'd like**
I recently started using Irony (great tool!) and the left pane with the list of subscribed mods required a lot of scrolling. But then after subscribing to a few more mods, it appears to have switched into a more compact single-line display of the subscribed mods.

I suggest making it possible to always use the more compact view even when subscribed to fewer mods.

**Comment by bcssov** [comment]
There isn't any switch here that I can turn on to turn it into a more compact view, nothing I can directly influence aside from maybe turning on horizontal scrollbar. The scenario you've seen is simply how the control drew the text.

**Comment by bestekov** [comment]
Oh interesting, so played around with it a bit more switching themes and it looks like Fluent and Material have spacing but "light" does not. I guess maybe it is just a theme thing and I must have been messing with themes and conflated that with number of mods.

**Comment by bcssov** [comment]
Ok, closing then.
