### ISSUE TITLE
Save Error

### ISSUE THREAD

**Issue by Mozziea** [bcssov/IronyModManager#249]
Save Error 
  
"something seems to be locking irony's ability to write to mid files"

I uninstalled and reinstalled and ran as admin. 
[2021-05-03_Error.log](https://github.com/bcssov/IronyModManager/files/6418854/2021-05-03_Error.log)

**Comment by bcssov** [comment]
This is a problem with your cloud provider or something: "The cloud file provider is not running.". Irony cannot access location where stellaris documents folder is located.

**Comment by Mozziea** [comment]
Do you know how i can figure out what cloud provider i use? I have the directory set up normal

**Comment by Mozziea** [comment]
OneDrive. I don't know how you do it, but you are an extraordinary guy.... Thank you thank you thank you
