### ISSUE TITLE
Mac Big Sur Gatekeeper preventing execution

### ISSUE THREAD

**Issue by madmotorcyclist** [bcssov/IronyModManager#250]
When attempting to execute Irony Mod Manager, Apple's Gatekeeper prevents it from running and stops it from loading any .dll file (pops up complaint for each one).

**To Reproduce**
1.   Just try to execute the application under Mac OS Big Sur (Intel version of course).
2. 
3. 
4. 

**Expected behavior**
Under Mojave had no issue.

**Screenshots**

**Logs**
If the application crashed add error logs related to the crash.

**Version:**
 - OS: Mac OS Big Sur (11.3.1)  
 - Irony Version 1.16.17
**Additional context**
Is there anyway of executing the application without turning gatekeeper off?

**Comment by bcssov** [comment]
See this: #119
To sign the app lots of $$$ is needed. So try to mimic the structure mentioned in the thread or turn off the gatekeeper.

**Comment by madmotorcyclist** [comment]
Thank you.  I decided to re-enable the third option in Security and Preferences that allows me to open up the mac for your app then disable it after executing your app to stay secure.  Was the easiest way.

In Big Sur when you do:   sudo spctl --master-disable

It pops up the “Anywhere” option in the Security and Preferences settings so you can then run your app (which I love and want to thank you for such a wonderful app).  You can then disable it and that option disappears.
