### ISSUE TITLE
Modding wiki seems to have updated FIOS/LIOS/Whole-file overwrite info

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#252]
https://stellaris.paradoxwikis.com/Modding#Overwriting_Specific_Elements

If I'm reading that right it seems the following sections also need to behave the same as districts and pop_jobs:

buildings
diplomatic_actions
species_archetypes
technology

possibly governments/authorities but it's not clear from the comment.

(PS would you prefer this sort of stuff under bug or feature?)

**Comment by bcssov** [comment]
In all honesty it's neither a bug or a feature.
