### ISSUE TITLE
Feature Request: Revert last patch

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#26]
For those times I derp...

**Comment by bcssov** [comment]
Though it is desired I won't make it for 1.0. Scheduling for 1.1.

**Comment by LordOfLA** [comment]
Hmm, maybe instead of "revert last patch" you have an option to show resolved conflicts so we can go and re-patch if we think we made a mistake.

**Comment by bcssov** [comment]
Yeah, that sounds better.

**Comment by bcssov** [comment]
Changed the feature request a bit, showing resolved conflicts a bit tricky to added reset conflicts instead. Allows you to revert and repatch on the main view.
