### ISSUE TITLE
Crash on Load 

### ISSUE THREAD

**Issue by Amorphist-zz** [bcssov/IronyModManager#260]
**Describe the bug**
I was able to launch the launcher a few times, but today I am unable to launch it. It briefly opens a window that says "error" in the title bar. This small window is oddly enough to the right of my monitor, as if I had another monitor to its right. 

**To Reproduce**
1. Install (and try to clean reinstall)
2. Double click desktop icon
3. Watch it crash

Note: I followed the recommended steps of installing the visual studio redist

**Expected behavior**
For it to launch :-) 

**Screenshots**

**Logs**
Log attached
[2021-05-20_Error.log](https://github.com/bcssov/IronyModManager/files/6519468/2021-05-20_Error.log)

**Version:**
Windows 10 x65

**Additional context**

**Comment by bcssov** [comment]
On what Irony version are you exactly on?

The error I'm seeing suggests that DI framework is going beserk, something that should not really happen until an install is corrupt I guess. 

Uninstall Irony completely, this means delete all files in the install folder and then reinstall and try again.

**Comment by Amorphist-zz** [comment]
Version v1.16.26.

I ran the uninstaller and deleted the entire folder. This time I got the .rar version and unpacked it; same thing unfortunately. 

[2021-05-20_Error.log](https://github.com/bcssov/IronyModManager/files/6519907/2021-05-20_Error.log)

**Comment by bcssov** [comment]
Try deleting or renaming %appdata%\Mario\IronyModManager folder (this contains all Irony options, playsets etc)

**Comment by Amorphist-zz** [comment]
That did it, thank you!

**Comment by bcssov** [comment]
If you still have the folder I mentioned I want Database_1.16.json from it to see what happened, otherwise I will not be able to fix it. Closing the ticket, if json is provided I'll reactivate the ticket.

**Comment by Amorphist-zz** [comment]
Here it is!


[Database_1.16.zip](https://github.com/bcssov/IronyModManager/files/6522504/Database_1.16.zip)
