### ISSUE TITLE
Patch is not applied

### ISSUE THREAD

**Issue by Namerian** [bcssov/IronyModManager#261]
**Describe the bug**
When importing a patch (https://steamcommunity.com/workshop/filedetails/?id=2492207486) and doing a basic merge the patch is not applied, no zzz files are added to the result.
If I reset and resolve a single entry before doing the basic merge then the patch is applied.

**To Reproduce**
1. import irony export from link
2. start basic merge
3. when done, notice that there are less than a hundred files that contain "zzz", there are over 20k when it works
4. 

**Expected behavior**
The patch is applied.

**Screenshots**

**Logs**
If the application crashed add error logs related to the crash.

**Version:**
 - OS: [Ubuntu 20.04]
 - Irony Version [1.16.30]

**Additional context**
I could not find an irony error log to post.

**Comment by bcssov** [comment]
I know the collection author he would have reported such an issue to me by now I think.

1. Ensure that patch mod is indeed imported from the mentioned collection (check patch mod status next to the search mods bar in the collection mods area)
2. Ensure that the collection is indeed active (enabled)
3. Basic merge copies the whole output patch mod included into the newly merged mod

**Comment by Namerian** [comment]
It always says "Patch Mod: Enabled" regardless of whether it actually is or not.

Should I be using compress merge? It seems to just create lots of zips.

**Comment by bcssov** [comment]
Patch mod is not copied in basic merge as a separate patch but is instead copied into the merged mod. For the differences between compress merge and basic merge please check the wiki docs.

**Comment by bcssov** [comment]
Believe this should have been resolved in .35 or .36 closing.
