### ISSUE TITLE
Irony Mod Manager fails to launch Stellaris 3.0

### ISSUE THREAD

**Issue by martmists-gh** [bcssov/IronyModManager#263]
**Describe the bug**
IMM fails to launch the game.

**To Reproduce**
1. Load up https://steamcommunity.com/sharedfiles/filedetails/?id=2492207486
2. Press launch game

**Expected behavior**
IMM launches the game.

**Logs**
```
$ irony-mod-manager-bin
[systemsettings.cpp:44] CPU Model: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

[systemsettings.cpp:45] CPU Speed: 3900MHz

[systemsettings.cpp:46] CPU Physical Cores: 6

[systemsettings.cpp:47] CPU Logical Cores: 12

[systemsettings.cpp:48] System Memory: 15781

[systemsettings.cpp:49] OS: Linux;5.11.16-arch1-1;#1 SMP PREEMPT Wed, 21 Apr 2021 17:22:13 +0000;x86_64

[systemsettings.cpp:50] OS Language: 
src/common/pipes.cpp (837) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (837) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (837) : Fatal assert; application exiting
src/common/pipes.cpp (837) : Fatal assert; application exiting
crash_20210527192956_2.dmp[851073]: Uploading dump (out-of-process)
/tmp/dumps/crash_20210527192956_2.dmp
_ExitOnFatalAssert
crash_20210527192956_2.dmp[851073]: Finished uploading minidump (out-of-process): success = yes
crash_20210527192956_2.dmp[851073]: response: Discarded=1
```

**Version:**
 - OS: Arch Linux
 - Irony Version: Latest from AUR (1.16.30)

**Additional context**
It seems the official launcher crashes after attempting to import this collection (?)

**Comment by bcssov** [comment]
Doesn't appear to be related directly to Irony. Also this seems to be the AUR release, I don't maintain that. 
- Irony uses xdg-open command to launch an external process:
	1. Check whether you have that installed
	2. Check if some permissions need to be performed or something
- Also it could be that the game is failing to launch; try launching it directly by launching the stellaris executable directly
- Try with the portable release and see if that works maybe.
