### ISSUE TITLE
Ignore .git folder during conflict detection

### ISSUE THREAD

**Issue by MrCorncrake** [bcssov/IronyModManager#265]
**Is your feature request related to a problem? Please describe.**
People write me that this mod manager says that my mods are not compatible with other ones and send the list of .git files as a prof

**Describe the solution you'd like**
When comparing mods the folder .git should not be taken into account

**Describe alternatives you've considered**
Give way for modders to indicate files to be ignored

**Additional context**
I'm sick of explaining to people that the .git folder has nothing to do with the game and can be ignored

**Comment by bcssov** [comment]
Wrong mod manager, closing. Irony excludes folders that contain dots in their paths.

Also a piece of advice, don't include git folde in your mod distribution it just bloats your mod size ;)
