### ISSUE TITLE
Crashes upon pressing crtl+E in conflict solver

### ISSUE THREAD

**Issue by LloydPage** [bcssov/IronyModManager#268]
If I enter the conflict solver and press ctrl+E, the mod manager crashes outright. Logs are attached below. Let me know if you need any more information or want me to try anything to do testing.
[2021-06-23_Error.log](https://github.com/bcssov/IronyModManager/files/6703705/2021-06-23_Error.log)

**Comment by bcssov** [comment]
Got a report this morning with the mentioned crash log, is fixed in this commit: https://github.com/bcssov/IronyModManager/commit/2881157dfaacf1c595ca82330d846f8443fc599c
Basically something in Avalonia changed which causes a CTD now.
