### ISSUE TITLE
win-x64.rar unble to extract

### ISSUE THREAD

**Issue by shag00** [bcssov/IronyModManager#270]
**Describe the bug**
I am unable to extract the windows portable rar file though the rar setup file is OK
Ver 1.17.104

**To Reproduce**
1. download win-x64.rar and extract
2. 
3. 
4. 

**Expected behavior**
A file folder is created in the specified directory

**Screenshots**
![irony](https://user-images.githubusercontent.com/37562304/125067160-7847bf80-e0e6-11eb-8850-356199131fda.png)

**Logs**
If the application crashed add error logs related to the crash.

**Version:**
 - OS: [e.g. Windows]
 - Irony Version [e.g. 1.5.48]

**Additional context**
Drive has 1.7TB free space

**Comment by bcssov** [comment]
Can't say it's related to Irony. Try using a different RAR client.

**Comment by shag00** [comment]
I agree it's not related directly to Irony, it's a packaging issue. This is the only rar package I have ever not been able to open after many years of using this client.

**Comment by bcssov** [comment]
Again, the rar is just fine on my end. It's your program not a packaging issue.

**Comment by shag00** [comment]
Well you may be right, time will tell.
