### ISSUE TITLE
All my mods are gone?

### ISSUE THREAD

**Issue by japa4551** [bcssov/IronyModManager#274]
**Describe the bug**
After i decided to use Irony, for some reason most of my .mod files were deleted. Havent found a log file so i decided to report this

**Version:**
 - OS: Windows 10
 - Irony Version: 1.17.106 (Using the Portable Version)

**Comment by bcssov** [comment]
Unless:
1. You used delete all and reload
2. Irony prompted you at run that some mods are invalid and asked whether to delete invalid mods

Irony didn't delete any mod files.

If Irony deleted mod files after prompting you but did not detect any. Maybe Irony cannot see your mods, in that case you can use Options screen to configure Irony and it will regenerate mod files.

If Irony cannot see any mod files but didn't actually delete any mod files then it probably cannot see and mods which again you can configure in the Options screen.

**Comment by japa4551** [comment]
After re-checking, the mods that were not removed were all in the Documents/Paradox Interactive/Hearts of Iron IV/mod folder

The mod that were probably seen as invalid were install manually on the Documents/Paradox Interactive/Hearts of Iron IV/workshop/content/281990 folder, only the .mod files were removed, everything else is here.

Any way to generate those files again?

**Comment by bcssov** [comment]
Irony only sees the following when regenerating mod files:
1. Steam auto detected workshop folders (this is automatic)
2. Documents\Paradox Interactive\[Game]\mod directory
3. Custom mod directory (which can be set in the options screen)

**Comment by japa4551** [comment]
The .mod files were there before and all the mods were reconized with no issues, maybe i randomly pressed "Delete All and Load", guess all i can do is reinstall them
