### ISSUE TITLE
Identification/Visibility of conflicts that have been reset due to a mod update in the merge viewer.

### ISSUE THREAD

**Issue by scrangos** [bcssov/IronyModManager#275]
**Is your feature request related to a problem? Please describe.**
With a large number of mods that have conflicts unresolved, the added conflicts that have been reset due to an update are very difficult to identify.

**Describe the solution you'd like**
Labels near the conflict selection that identify if its been restored due to an update, with information if it was previously ignored, or previously resolved.  Possible options for filtering for only updated, only updated previously resolved, only updated previously ignored

**Additional context**
Made a possible mockup of what I was thinking if it helps brainstorm ideas. While the image shows a check mark, its there just to illustrate its a checkbox, the actual contents of the conflict list do not reflect such a filter has been applied.

https://i.imgur.com/KiLKXcf.png

**Comment by scrangos** [comment]
Just occured to me, but the mod that triggered the restoration of the conflict should probably be marked in the conflict merge list.

**Comment by bcssov** [comment]
What is conflict merge list?

**Comment by scrangos** [comment]
> 
> 
> What is conflict merge list?

https://i.imgur.com/uinfr2p.png
this side of the screen, 

i threw in something extra that had been slowing me down. having to manually figure out if the virtual was different than the load order default.  But knowing if it was a resolve or an ignore should help a lot in that regard anyway.

**Comment by bcssov** [comment]
That's a no on this one, too many things that could go wrong. It could be missing, mod could be renamed so I'd have to keep track of much more stuff.

**Comment by bcssov** [comment]
Will use a simplified version of just indicating reset conflict since last run time.
