### ISSUE TITLE
MacOS mod selection broken

### ISSUE THREAD

**Issue by RealTechyGod** [bcssov/IronyModManager#279]
**Describe the bug**
Can not add any mods to list

**To Reproduce**
1. attempt to import any mod
2. nothing happens
3. 
4. 

**Expected behavior**

**Screenshots**

**Logs**
If the application crashed add error logs related to the crash.

**Version:**
 - OS: [e.g. Windows]
 - Irony Version [e.g. 1.5.48]

**Additional context**

**Comment by bcssov** [comment]
There's very little information provided. 
- Is your install steam?
- Where are the mods that cannot be detected located?

And other relevant information.
