### ISSUE TITLE
Irony crashes immediately on opening

### ISSUE THREAD

**Issue by Ophidahlia** [bcssov/IronyModManager#280]
**Describe the bug**

Irony closes down immediately after opening. It was working fine the other day, but today it just terminates before the GUI even comes up. The only change I made to my system is the most recent windows 10 update. I haven't had this issue with any other programs so far.

I uninstalled and reinstalled the program in the default directory at %appdata%\local\programs\Irony Mod Manager, restarted my PC, and I also tried the zip file version separately just in my downloads folder. I still get the same result.

I tried using the updater and it crashes. 

**Screenshots**
I attached a screenshot of my system process log and the message from the update attempt.

**Version:**
 - OS: Windows 10 x64
 - Irony Version: latest 1.17.107

Any help you can offer would be greatly appreciated so I can get back to soylent greening the space weasels

![2021-08-15 11_28_04-Process Lasso Log Viewer](https://user-images.githubusercontent.com/37412592/129482345-0ce77de6-04b1-4828-adfd-cb71ed68c372.png)
![2021-08-15 11_24_36-Greenshot](https://user-images.githubusercontent.com/37412592/129482349-35b1a0bc-244a-434a-a84b-a4a02913bef4.png)

**Comment by bcssov** [comment]
I need Irony logs, see homepage or wiki where to find it. 

Updater executable is not intended for this use case.
