### ISSUE TITLE
Can't import merged mod

### ISSUE THREAD

**Issue by JECJoker** [bcssov/IronyModManager#290]
![image](https://user-images.githubusercontent.com/13439146/131199846-955603b5-0a18-4044-880e-e14ac1e51bc2.png)
So far everyone who I've had try has been stuck in exactly the same way, I'm not sure if I've broken something, or...?

**Comment by bcssov** [comment]
You provided zero information. 
What kind of a mod collection are you trying to import?
Is this an actual merged mod as in whole collection or just load order?
If this is a whole collection how big is it?
Did Irony crash? If so logs.

**Comment by JECJoker** [comment]
Hey now, one is more than zero, and sorry for the severe lack of information, not sure what I was thinking.

It's a merged Stellaris collection consisting of just the complete merged file, it doesn't crash, it just stops at that point in the screenshot, and leaving it for awhile doesn't seem to do anything. The exported merge file is just under 3GB.

**Comment by bcssov** [comment]
It could be that it takes a while to unpack, this depends on hard disk performance. Check Irony logs maybe it also produced a log (check Irony homepage for a location).
