### ISSUE TITLE
Conflict resolver - .dds files

### ISSUE THREAD

**Issue by Virstag** [bcssov/IronyModManager#292]
It seems to me that in the new version (1.18.71) it is impossible to resolve the conflicts between .dds files - nothing happens after choosing the left or right side and clicking on "Resolve". I was able to verify that rolling back to the earlier version (1.17.107) eliminated the problem.

**Comment by scrangos** [comment]
Ugh, thats 99% chance my fault.  I'm looking into it.

**Comment by bcssov** [comment]
It got broken with a feature request which validates brackets. It's fixed in the latest version.
