### ISSUE TITLE
Irony being detected as false positive in BitDefender

### ISSUE THREAD

**Issue by sovietpi** [bcssov/IronyModManager#293]
**Describe the bug**

**To Reproduce**
1. Download either Windows installer or archive
2. Run installer/Extract Zip
3. Start the installer
4. it gets flagged as Gen:Variant.Bulz.675162

**Expected behavior**
Irony to install successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/90199637/132226461-5aa30900-d210-443b-8477-1ed0ffff1e7b.png)

**Logs**
If the application crashed add error logs related to the crash.

**Version:**
 - OS: [Windows]
 - Irony Version [v1.18.76]

**Additional context**

**Comment by bcssov** [comment]
uninst dat file usually contains information which tell the uninstaller which files to remove. Here are the virus total results of the following:

- I uploaded the dat file from my own computer to virus total and it states that it's clean
![1](https://user-images.githubusercontent.com/5864390/132229205-f1b1d4a8-c41c-41c7-b6c3-09f91fbde8ae.jpg)
https://www.virustotal.com/gui/file/e77c3d3a775319f785d3a15a69b99ad5844366882aa8b4dd428873723d11b166/detection 

- I also uploaded the rar which contains the installer it also states that it's clean
![2](https://user-images.githubusercontent.com/5864390/132229208-7d1e2ec2-0a8b-49fc-b862-7720e1cc297c.jpg)
https://www.virustotal.com/gui/file/42c6d73f138ef57356132ca5e4b8c3f3c560fa297d413751c7e6e8d95e7d6d64/detection

- Only the setup exe
![3](https://user-images.githubusercontent.com/5864390/132232190-3c1d3d5c-f0ef-4dbe-af46-00a37a89694f.jpg)
https://www.virustotal.com/gui/file/f7c1a733a8ba56503381721920439bdbfd71effe94fc9230692cd357671a5378/detection

I don't have time to run around and whitelist every reported instance of a false positive out there and have no intention to do so. Just in case though scan your computer to see that it's not infected with something.
