### ISSUE TITLE
crashes when i conflict solve

### ISSUE THREAD

**Issue by dandacan** [bcssov/IronyModManager#294]
**Describe the bug**
Today I updated the mod manager to the latest version and encountered 2 popups when i open the app that say "unhandled exception, the app will close automatically" it does not close automatically. it appears to be fine until I hit the conflict solve button and wait until step 6 gets to 2.4% then the manager crashes and a third window pops up that says the same thing and the window closes itself.

**To Reproduce**

1. open mod manager, pre-configured to be managing the stellaris mods
2. _the first 2 popups occur, then they close themselves_
3. click the conflict solver button and wait until it begins to analyze resolved conflicts, then gets to 2.4% (might be related to the number of mods that i have)
4. _the final critical error occurs closing the app with it_

**Expected behavior**
I expected to be able to solve my conflicts like i did moments prior to updating

**Screenshots**

**Logs**

[2021-09-08_Error.log](https://github.com/bcssov/IronyModManager/files/7132742/2021-09-08_Error.log)
 - 

**Version:**
 - OS: Windows 10
 - Irony Version 1.18.76

**Additional context**

**Comment by bcssov** [comment]
Antivirus

**Comment by dandacan** [comment]
i use windows defender

**Comment by bcssov** [comment]
Regardless of what you use Irony is denied write permissions to documents folder. Simple as that.

**Comment by dandacan** [comment]
ah that fixed it
