### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by DovahFett** [bcssov/IronyModManager#296]
**Describe the bug**
Seconds after starting the program, a window with the text "Fatal Error" pops up.  The program exits out a few seconds afterwards.  Looking at the crash log seems to suggest that the crash is caused by a parameter called 'path1', which has a null value.  It's interesting that this error only occurs when I switch the selected game to CK3 or start the program when it's already set to CK3.  It works on all other titles.

**To Reproduce**
1. Start the program via the executable or a shortcut.
2. Switch the game to CK3 via the drop down.
3. Wait a second or two for the error message to popup and wait a few seconds more for the application to crash.

**Expected behavior**
When started the application should successfully load all mods and collections without a fatal error.

**Logs**
[2021-09-11_Error.log](https://github.com/bcssov/IronyModManager/files/7148663/2021-09-11_Error.log)

**Version:**
 - OS: Windows 10
 - Irony Version 1.18.78

**Comment by bcssov** [comment]
Looks like a lot of things are broken around CK3 and Imperator. Had to borrow the game from a friend since I don't own any other game than Stellaris.

**Comment by DovahFett** [comment]
Thanks for the fast response.  I'm glad to help.
