### ISSUE TITLE
Conflict Resolution - Left/Right side not changing viewed data

### ISSUE THREAD

**Issue by lmSleepless** [bcssov/IronyModManager#297]
**Describe the bug**
Updated to version1.18.86. Now when I do default conflict resolution of Stellaris mods, I cannot choose what mod's data I'm viewing on either left or right side. I seem to be stuck viewing base Stellaris on left and merge mod on right. 

**To Reproduce**
1. Install 1.18.86
2. Get some conflicting stellaris mods. (In my case, I know that "Expanded Stellaris Ascension Perks" and "Gigastructural Engineering" have some easy to fix conflicts in common/ascension_perks/ap_defender_of_the_galaxy)
3. Go to default conflict resolution
4. Attempt to view different mods in left or right side.

**Expected behavior**

**Screenshots**
![Irony Conflict Resolve Issue](https://user-images.githubusercontent.com/1791589/133851688-062a5675-ca24-4975-a711-21ec3e4dd252.gif)
**Logs**

**Version:**
 - OS: Windows 10
 - Irony Version 1.18.86

**Comment by Virstag** [comment]
You know, I think this issue is back in v1.18.89.
