### ISSUE TITLE
Conflict Resolution - Left/Right side not changing viewed data: the sequel

### ISSUE THREAD

**Issue by Virstag** [bcssov/IronyModManager#298]
I think the problem described here:

https://github.com/bcssov/IronyModManager/issues/297#issue-999709929

is back in the 1.18.89 version.

**Comment by shinooni** [comment]
I Second the issue. Its back in 1.18.89

**Comment by bcssov** [comment]
Imagine using a refactoring tool which ends up messing protection level when you perform a code cleanup.
