### ISSUE TITLE
Save Error

### ISSUE THREAD

**Issue by Tokuraj** [bcssov/IronyModManager#303]
**Save Error**
When I have mods saved on the mod panel and I click "apply", then message pops up. This says Irony is unable to "write to mod files". And I did as the message told me.

**Logs**

[error.log](https://github.com/bcssov/IronyModManager/files/7403309/error.log)

**Version:**
 - OS: [Windows 10]
 - Irony Version [e.g. 1.18.92]

**Comment by bcssov** [comment]
This is not the Irony exception log but game error log.
