### ISSUE TITLE
Ignore Rules Wildcard Mistake

### ISSUE THREAD

**Issue by benmontour** [bcssov/IronyModManager#307]
**Describe the bug**
I accidentally hit Enter with a `*` Ignore Rule. Now I can no longer access the Ignore Rules option to remove it. When I go into Conflict Solver all I see are the Invalid rules, and the Ignore Rules button is not presented on that screen.

**To Reproduce**
1. Add Ignore Rule of `*`
2. ...
3. Be sad that you just locked yourself out of the Conflict Solver you spent the last 3 hours in resolving conflicts.

**Expected behavior**
An option to open the Ignore Rules from the Conflict solver, even if there are no "valid" conflicts and only the Invalid ones.

**Screenshots**
![invalidNoIgnoreRules](https://user-images.githubusercontent.com/8712103/140627858-cf692701-8b49-4547-b00c-aecedd8fe7a2.PNG)

**Logs**
n/a

**Version:**
 - OS: Windows
 - Irony Version: v1.19.76

**Comment by benmontour** [comment]
Closed with no comment? 
No discussion of maybe a "Reset Ignore Rules" button within Options, or a filter to prevent a single `*` from being entered in as a rule? 
I know it was a mistake on my part but a way out of a bad situation would be nice to have. Seems not ideal that doing so would permanently lock a user of Irony out of any further Conflict Merges unless they decided to delete their merge file and start fresh.

**Comment by bcssov** [comment]
Have you payed attention to new version release notes?

https://github.com/bcssov/IronyModManager/releases/tag/v1.19.81

**Comment by benmontour** [comment]
I see that now. That was not reflected in the closing of this issue. Thank you though. Very much appreciated!
