### ISSUE TITLE
Possible mod merging error causes graphic bug?

### ISSUE THREAD

**Issue by Botroas** [bcssov/IronyModManager#309]
**Describe the bug**
Manager used for Stellaris game mod merging. 
An in-game graphic object turns into a square box. 
When running game without some mods, box have different colored sides, with x, y, z on them. 
Starting the game without the Irony mod merging files, the problem do not show.

**To Reproduce**
1. Loading any mod in Irony manager
2. Making custom merged mod data from previous conflict solver runs accessible for Stellaris
3. Starting Stellaris through Irony manager

**Expected behavior**
Normal object display after starting game, with mod merging files.

**Screenshots**
![image](https://user-images.githubusercontent.com/94015170/141002347-7dfb79e7-be30-4512-b1d5-80bb80847e15.png)

**Logs**
No crash, there is no log.

**Version:**
 - Windows 10 Pro 64 bit
 - Irony Version 1.19.81.

**Troubleshooting tries**
- starting Stellaris with less mods : problem always present, even with mod unrelated to bugged object. (text altering for ex.)
- after re-installing Stellaris, Irony manager, all mods : problem remains

- removing mod merging files and starting game with all mods through Irony manager: Ok, problem gone
- enabling all mods and starting with official Paradox launcher (have no mod merging function) : Ok, problem gone
Problem noticed after usual Irony manager usage, like mod refreshing, conflict solver running.
Im not sure if the manager causes it, but it might worth to check it, other ideas did not worked so far.
Thank you!

**Comment by bcssov** [comment]
That's not an Irony issue that's a mod bug. It's not using proper path casing which becomes noticeable in merged mods or on file systems which are case insensitive. Windows file system by itself is case insensitive.

**Comment by Botroas** [comment]
Thanks for the feedback, sorry for the invalid post.

**Comment by bcssov** [comment]
Check the game logs I guess, it should tell you something.

**Comment by Botroas** [comment]
Ok, thank you.
