### ISSUE TITLE
Patch mod is causing a compat mod to fail

### ISSUE THREAD

**Issue by lmSleepless** [bcssov/IronyModManager#312]
**Describe the bug**
I have encountered a set of mods that work perfectly when ordered correctly, but fail the minute I open and close conflict solver. I can get it back to normal by disabling/deleting conflict patch. Making it even stranger, there are no (unsolved?) conflicts listed in conflict solver when it is opened. The mods in questions are:

- https://steamcommunity.com/sharedfiles/filedetails/?id=2379954995
- https://steamcommunity.com/sharedfiles/filedetails/?id=1623423360
- https://steamcommunity.com/sharedfiles/filedetails/?id=2630122716

These are the UI Overhaul mod, Revolutions - Ethics and Civics, and its compat path with UI Overhaul.

I also seem to get this behavior when I try a different ethics overhaul mod with its ui overhaul patch, can provide details on that one if you'd like.

**To Reproduce Correct Behavior**
1. Load mods in order of Revolutions, UI Overhaul, and the compat patch
2. Launch Stellaris without opening conflict solver. Create New species, go to Government & Ethics, and you can interact with ethics selection as expected.

**To Reproduce Error Behavior**
1. Load mods in order of Revolutions, UI Overhaul, and the compat patch
2. Open conflict solver, then close it.
3. Launch Stellaris, Create New species, go to Government & Ethics. Normal ethics will sort of work. Fanatic ethics will be borked. Will also notice yellow select ring in top left corner.

**Screenshots**
Load Order
![Load Order](https://user-images.githubusercontent.com/1791589/143669390-639f87ec-06d2-4f1b-ab15-162a79ec1556.PNG)
Working
![Working](https://user-images.githubusercontent.com/1791589/143669393-bbb708c6-caf1-47d9-b298-9e4911d4ab37.PNG)
Not Working
![Not Working](https://user-images.githubusercontent.com/1791589/143669392-ddbc4da1-b1ac-47a7-8b69-0a276fc498dd.png)

**Version:**
 - Irony Version 1.20.24

**Comment by bcssov** [comment]
.25
