### ISSUE TITLE
macOS Launch Incompatible

### ISSUE THREAD

**Issue by helloitisjc** [bcssov/IronyModManager#313]
**Describe the bug**
The osx file is not launchable on M1 Apple devices.

**To Reproduce**
1. Follow the osx installation steps on the release page.
2. There is no valid Apple security certificate to allow this to operate on M1 chip devices.

**Expected behavior**
Being able to launch Irony on my device.

**Screenshots**
N/A

**Logs**
N/A

**Version:**
 - OS: macOS 12.0.1 [M1 Chip]
 - Irony Version: 1.20.25

**Additional context**
Might I suggest converting this to a DMG file instead so it's not such a manual process for installation?

**Comment by bcssov** [comment]
See #119 for more details.

I will eventually provide an installer version for macs but I will not provide signed certificates for several reasons:
1. I don't own a mac
2. Irony has a very low mac user base (~1.2%)
3. $$$ involved for this whole process which puts me away (need to own a mac, need to own sdk subscription etc)
