### ISSUE TITLE
Unable to import collection

### ISSUE THREAD

**Issue by adecoy95** [bcssov/IronyModManager#315]
I am unable to import a collection on my second computer, i checked the logs and it looks to be related to mods with japanese characters in the name. is there a way to fix this?

**Comment by bcssov** [comment]
Probably an old collection there was a bug in how Irony handled chinese\japanese characters in zip files which was fixed in newer versions. You're going to have to manually open the zip and find the problematic file and rename in the zip itself.

**Comment by adecoy95** [comment]
sorry for the delay, it is not an old collection, i am trying to sync up my checksums between two computers to play multiplayer, and ran upon this issue in the latest version of irony. i can state that i cannot see japanese characters in one of the computers winrars, if that helps, im not sure if its related or how to fix it. i installed japanese language pack on that computer to try and resolve even though the one that works on does not need it.

**Comment by bcssov** [comment]
In such instance Irony must have crashed, if that is the case provide irony error logs.
