### ISSUE TITLE
Conflict database location

### ISSUE THREAD

**Issue by KySoto** [bcssov/IronyModManager#316]
I am trying to figure out how to send my conflict database to my friend, so he can take what i did in my generated patch mod so we have the same game version. I tried sending him the patch mod i generated, but it didnt seem to apply correctly.

In the end, where should my conflict manager database be stored by default.

**Comment by bcssov** [comment]
The "conflict database" or what is called the patch mod is located in the patch mod which is exported when you export the load order (by toggling the export button). If you're trying to do an online play then this usually means that:
1. You are on 2 different steam branches 
2. Steam messed up downloading a mod for your friend thus resulting in game checksums being different
3. One of you has modified their game files 
4. One of you ran conflict solver in between importing collections 
...

**Comment by KySoto** [comment]
Thanks for the explanation how it worked. that helped us get everything working
