### ISSUE TITLE
Conflict solver not remembering state (showing conflicts regardless of being patched/changed or not)

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#32]
For a test case install the following mods:

ACoT https://steamcommunity.com/sharedfiles/filedetails/?id=1419304439
Plentiful Traditions https://steamcommunity.com/sharedfiles/filedetails/?id=1311725711

Patch the armies and Scripted Triggers and flag everything else as ignored. There should be now nothing in the drop-down or list view.

Exit solver.

Enter solver

Everything is back in the drop-down/list view.

It *does*, however, remember state if you exit Irony and restart the app before re-entering the conflict solver. But if you then enter, exit, re-enter the solver everything is back again.

**Comment by bcssov** [comment]
Scheduled after CWTools implementation.

**Comment by bcssov** [comment]
Reminder:

LordOfLAToday at 5:33 AM
hmm, is the solver supposed to read-back in existing patches when it spots mods have changed?
MarioToday at 5:34 AM
last item from conflict history
from state.json
LordOfLAToday at 5:34 AM
it's not doing that then currently either
when it forgets it just shows the conflicts as if it's the first time it saw things. Existing patch isn't shown in the IronyPatch entry
