### ISSUE TITLE
Don't compress music mods, just smush them all together into a loose file mod in the local mod folder

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#321]
As title. Would reduce compress merge times a fair amount, potentially save disk space since the .ogg files are compressed audio anyway afaik.

**Comment by bcssov** [comment]
That would significantly complicate the logic with no real benefit to the overall logic. Will think this through.

**Comment by LordOfLA** [comment]
Could also just skip processing mods that contain only music + asset file for said music, let them load as-is from the workshop folder. It isn't as though music mods are limited to game versions at the moment.

**Comment by bcssov** [comment]
This is a really low priority.

1. It adds nothing to the program or overall really
2. It complicates already complex logic 
3. Additional complexity comes when a music mod is not just a music mod but a hybrid of whatever someone decides to add to it

**Comment by LordOfLA** [comment]
Can be as low as you want. It's a qol / time saving feature for users and probably the driving desire for the "don't repack unchanged mods" feature request.

Plus the request is for *just* music mods not mods with music and other stuff. Really easy to tell what those mods are and easy to therefore skip.

**Comment by bcssov** [comment]
This is outdated.
