### ISSUE TITLE
Segmentation fault with /usr/lib/libfontconfig on Arch Linux

### ISSUE THREAD

**Issue by RA3236** [bcssov/IronyModManager#322]
[journalctl log related to segmentation fault](https://pastebin.com/XQiU5VAJ)

Irony doesn't create a log file in .config/Mario, and the log that appears in journalctl [doesn't seem to show anything of significance](https://pastebin.com/W84mbT2X).

Occurs with both AUR package and download from Github.

Steps to reproduce:

1. Do anything on the application (for example, click on Conflict Solver and wait until Step 6 is at 100%). I had this earlier where it would occur at any point, but deleting the Database file fixed it.

[Package list](https://pastebin.com/J4xpFRbX), includes noto-fonts and noto-fonts-cjk

**Comment by bcssov** [comment]
Some distro setups are finicky (best description). Even though I've had a few reports of segfaults I've never been able to reproduce myself on a VM.

Based on these experiences what was discovered was that one of the following works:
1. Installing msttcorefonts package helps
2. Set this to true: https://github.com/bcssov/IronyModManager/blob/ac4b55a2c9155040635bf889b57aaf8754c29753/src/IronyModManager/appSettings.json#L9
Alternatively (preferably) you can use this (quote from discord):
> One undocumented feature if you want to override appSettings.json but don't want it being reset after an update you can make a copy of appSettings.json and rename it to appSettings.override.json and selectively override elements from appSettings.json. Irony loads both of these files with the override taking priority so you don't have to lose your personal appSettings preferences. Keep in mind that these jsons are merged so missing options from the override file will not be a problem.

**Comment by RA3236** [comment]
Setting that option seems to work. Thank you, closing.
