### ISSUE TITLE
Cannot apply mods to collection, cannot launch game.

### ISSUE THREAD

**Issue by avocadobri** [bcssov/IronyModManager#325]
**Describe the bug**
I downloaded the mod manager, created an collection. Added my mods, hit apply and get an error.

**To Reproduce**
1. Create Collection
2. Add all mods
3. Select Apply
4. 

**Expected behavior**
I expected the list to save and be able to open the game.

**Screenshots**

**Logs**
If the application crashed add error logs related to the crash.

**Version:**
 - OS: ![2021-12-25 11_19_32-Irony Mod Manager_ v1 20 37](https://user-images.githubusercontent.com/96660264/147389332-3a7ebf0b-00de-478e-9cf7-82b4f4d384e3.png)
![winver](https://user-images.githubusercontent.com/96660264/147389333-85dca6eb-8603-4c9d-9cdb-91037c01485e.png)

 - Irony Version
 - 1.20.37

**Additional context**
[error.log](https://github.com/bcssov/IronyModManager/files/7776033/error.log)

**Comment by bcssov** [comment]
I can't tell anything from this as it's missing the program error log.

**Comment by tiger8255** [comment]
> I can't tell anything from this as it's missing the program error log.

Is that not what's under "Additional Context"?

**Comment by bcssov** [comment]
No, what you posted is the **game** error log.

**Comment by avocadobri** [comment]
Honestly guys, I couldn't get it to work. I just uninstalled it and went back to the paradox launcher and had no issues once I uninstalled the mod manager completely :(On Dec 28, 2021, at 9:56 AM, Mario ***@***.***> wrote:No, what you posted is the game error log.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
