### ISSUE TITLE
Button to test configured external diff tool.

### ISSUE THREAD

**Issue by rnett** [bcssov/IronyModManager#328]
**Is your feature request related to a problem? Please describe.**
I can't get IntelliJ working as an external diff tool.

**Describe the solution you'd like**
A button to test the external diff tool w/ example files.

**Comment by bcssov** [comment]
Sounds reasonable, something I might do in the next update even.

Just to satisfy my curiosity why IntelliJ?

**Comment by rnett** [comment]
Since I'm used to it and already have it installed.  It supports multi-file diffs, too, but it doesn't look like there's any way to take advantage of that.
