### ISSUE TITLE
Save Error: Something seems to be blocking Irony's write

### ISSUE THREAD

**Issue by colingroh** [bcssov/IronyModManager#329]
I am having a save error similar to [#128](https://github.com/bcssov/IronyModManager/issues/128) but when I went to go find the sqlite file mentioned in that issue. I only found one called "emptyParadoxLauncher.sqlite" or something like that, but when I tried to open it Windows then told me the file didn't exist. My Database folder was also completely empty.
[2022-01-16_Error.log](https://github.com/bcssov/IronyModManager/files/7877719/2022-01-16_Error.log)

**Comment by my0n** [comment]
The sqlite file you're looking for is at `%USERPROFILE%\Documents\Paradox Interactive\Stellaris\launcher-v2.sqlite` on Windows
I just visited this repo because I ran into the same issue ten minutes ago and forgot how to fix it hehe

**Comment by bcssov** [comment]
You got an older version of pdx launcher with a different db schema (a new required column). I take that into account in the latest launcher version but not apparently in an update somewhere in between. I'm going to need to see your sqlite json to see what the db schema looks like. After that:
1. Upgrade to the latest pdx launcher
2. Delete sqlite database (which ever you prefer is fine by me). Do note that purge means you lose any data you might have in the pdx launcher in regards to stellaris.

**Comment by bcssov** [comment]
Issue should be fixed (just in case do post your sqlite db). I won't be releasing the fix immediately as it's not really urgent. Users can bypass the issue manually.
