### ISSUE TITLE
[Linux] Add setting enviroment variable or wrapper command option.

### ISSUE THREAD

**Issue by SSUPII** [bcssov/IronyModManager#337]
**Is your feature request related to a problem? Please describe.**
On laptops with NVIDIA Optimus every program runs on the integrated, low consumption iGPU by default. This of course means that the mod manager will also launch the game with the iGPU giving really poor performance. To have a program run using the discrete card instead, some environment variables need to be set at every program execution.

**Describe the solution you'd like**
A textbox in config where I can specify a wrapper command, empty by default, but if limited in lenght should be enough to fit this string:
`env __VK_LAYER_NV_optimus=NVIDIA_only __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia`

**Describe alternatives you've considered**
Running the mod manager with this environment could also pass the same definitions to the game when launched. This is something that it is already doing, as per default behavior a program running on a specific graphical device will launch any child processes under the same device. Unfortunately, I am forgetful unless I make it into a one line script just to call the launcher under the right environment. Also, this is the mod manager running on the discrete card when it is minimized and brought back up:
![Istantanea_2022-02-23_12-02-59](https://user-images.githubusercontent.com/42090377/155307017-81333745-6dd9-4fe1-adfa-bdbbc3ce1d78.png)

**Comment by bcssov** [comment]
The rendering issue is related to framework I'm using. Seems like a redraw issue it doesn't seem to be triggered for some reason. You could try playing around with the linux related options that are exposed:
https://github.com/bcssov/IronyModManager/blob/25fb9776c4e2a22825892bfb87497f56a94aa570/src/IronyModManager/appSettings.json#L11-L15
The documentation of the framework exposed options can be found here:
https://github.com/AvaloniaUI/Avalonia/blob/995e6fdaa91830d2a10f5b89e192851b39c567fc/src/Avalonia.X11/X11Platform.cs#L273

The environment args passing I'm going to put on low priority.

**Comment by bcssov** [comment]
Since you said it yourself child process inherits environment variables, just remember to create a shortcut with the following environment variables. I will go ahead and close this ticket since it really seems redundant.
