### ISSUE TITLE
Unable to Create Patch Mod

### ISSUE THREAD

**Issue by explodoboy** [bcssov/IronyModManager#338]
**Describe the bug**
I am unable to create any Patch Mods via Irony. Performing a (to my knowledge) clean reinstall (uninstalling Irony and then deleting everything in Appdata I was able to find) does not fix this.

**To Reproduce**
1. Have 'Stellaris' as active game
2. Create (and populate) a collection, OR import a collection.
3. Unable to create Patch Mod; "Patch Mod: Not Available" is present where the option to create a patch mod would be.

**Expected behavior**
The ability to create and adjust a Patch Mod should be available when a populated collection is active.

**Screenshots**
![image](https://user-images.githubusercontent.com/27088767/155904529-9f9542ea-5063-4d94-9aec-a13c0076a0b1.png)

**Logs**
No logs.

**Version:**
 - OS: Windows 11 Insider Build 2200.469 co_release (Release Preview branch)
 - Irony Version v1.21.119

**Additional context**
I have been using Irony since around the time it was released to the public. I don't know precisely when I was unable to create a patch mod, but I just realized that it was an issue very recently, as even with merging, there are still a few conflicts present that would demand a patchmod to fix.

**Comment by bcssov** [comment]
I'm going to have to label this one as invalid. Irony never had a button which allowed you to create a patch mod manually. Patch mods are created when you run conflict solver and only if necessary (it's auto determined by conflict solver)

**Comment by explodoboy** [comment]
My bad, I completely misremembered.
