### ISSUE TITLE
A brand-new install of Irony doesn't generate the patch .mod file when importing.

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#34]
A user of my most recent Steam collection that uses Irony reported the .mod file was missing on import.

Having completely cleared out the Stellaris folder and the AppData folder for Irony, followed by re-importing my collection, I can confirm that, if not for everyone, it does not create the necessary .mod file for the bundled patch.

Everything I expect you'll need to reproduce is on https://steamcommunity.com/sharedfiles/filedetails/?id=2062766262

**Comment by bcssov** [comment]
I'll usually need a minimal repro, not a requirement to download 5 GB of data :S. 
Here Irony is missing logic in apply button to generate a a patch mod file. Import was never intended to generate one nor it ever will however Apply should have this logic (which is missing unfortunately).

**Comment by LordOfLA** [comment]
Well, where-ever it's supposed to be, and yes I generally do try and give you a minimal repro, but in this instance I figured you may need the entire collection to be able to reproduce the problem on account of needing the mods to be present.
