### ISSUE TITLE
exported.json in mod export - identifying mod information

### ISSUE THREAD

**Issue by MattMills** [bcssov/IronyModManager#346]
**Is your feature request related to a problem? Please describe.**
Could you please add mod identifiers to the exported.json exported mod information such that the list of mods could be resolved back to original steam mod IDs (or other mod ID, where available)?

**Describe the solution you'd like**
I'd like to be able to automatically identify user mods by looking at the JSON data, and correlating them against steam mod listings.

**Describe alternatives you've considered**
I suppose it may be possible to look at the descriptor.mod in each individual mod file and use the remote file ID data from there, but that would require decompressing a lot more data to get to them.

**Additional context**
Only that I'm hoping to do so from a client side javascript web-app.

**Comment by bcssov** [comment]
The current spec is something like this:
`Game`: Used to determine which game this export belongs to.
`IsSelected`: Not used
`MergedFolderName`: Parent merged mod name which is used by Irony internally to offer a prompt to delete the whole folder
`ModNames': Not used by Irony I think but some people use it to see mod names. 
`Mods`: Used actually by Irony to match imported mods.
`Name`: Collection name
`PatchModEnabled`: Indicates whether the patch should be enabled by default during the import

So given the current spec the easiest way would be to just add something like `ModIds` with object information ex.
```
ModIds: [
	{ SteamId: id, ParadoxId: null }
]
```

The proper way would be to of course ditch all of these fields and just rework Mods field containing all the information but that would be a breaking change which would make lots of users angry. On the other hand I could detect maybe spec format but that would also be a pain... I'll think about it some more for future versions.

**Comment by MattMills** [comment]
I'm fine with however you want to do it, thanks though!

**Comment by bcssov** [comment]
Will add additional line in the exported.json (easier for me)

**Comment by MattMills** [comment]
<3
