### ISSUE TITLE
Error logged when Opening and then When Applying

### ISSUE THREAD

**Issue by ImKermitz** [bcssov/IronyModManager#348]
**Describe the bug**
Error is logged when opening up Irony but, Irony does not mention it has. Then when trying to apply on Irony the 'Save Error' is shown

**To Reproduce**
1. Open up the program - Error logged
2. Add any mod that should work
3. Click apply - Save Error

**Expected behavior**

**Screenshots**
![IronyError](https://user-images.githubusercontent.com/48301125/159224592-e1e26a91-7d0d-42c5-b9d4-ecd5840bb387.PNG)

**Logs**
[2022-03-21_Error.log](https://github.com/bcssov/IronyModManager/files/8313921/2022-03-21_Error.log)

**Version:**
 - OS: Windows 10
 - Irony Version v1.21.127

**Additional context**
I have looked at the log and find it strange as I do not have stellaris or Irony stored on my D drive and I do not have a folder called 'Working'.

**Comment by bcssov** [comment]
1. You have a corrupt libraryfolders.vdf file somewhere in steam. That's what the "silent" error says. This is Irony trying to find from steam location of your game installations.
2. One of jsons in the C:\Users\Username\Documents\Paradox Interactive is corrupt. Delete each of them and reapply.

> I have looked at the log and find it strange as I do not have stellaris or Irony stored on my D drive and I do not have a folder called 'Working'.

It's debug info intended for me. It's a location on my VM where jenkins is located which builds the binaries.

**Comment by ImKermitz** [comment]
Thanks that was the issue, resolved.
