### ISSUE TITLE
[LInux] Launching from Irony Deletes Mods and invalidates list

### ISSUE THREAD

**Issue by JeremyDaug** [bcssov/IronyModManager#351]
**Describe the bug**
When running from Linux (Pop!_OS). Trying to run from the launcher causes all mods to be deleted and the system to load without the selected mods.

**To Reproduce**
1. Create a mod list as normal.
2. Hit Launch

**Expected behavior**
It should be loading the game with mods.

**Version:**
 - OS: Pop!_OS
 - Irony Version 1.21.130

**Additional context**
I believe this may be a double problem on my end. The deletion seems to be caused by Irony. But the not loading mods seems to be caused by Stellaris itself. I will explore more and get back to this.

**Comment by bcssov** [comment]
Irony does not delete *.mod files unless you tell it to (as in say yes to a prompt). It also doesn't touch mods unless you tell it to. Stellaris executable is however known to delete local *.mod files at times.

**Comment by JeremyDaug** [comment]
Alright, I thought it was caused here because it seemed to only happen when using Irony's launch. Stellaris' launcher didn't do it to me.

**Comment by bcssov** [comment]
Do mod files (docs\pdx\stellaris\mod\*.mod) psychically disappear or does the game just not load mods when you boot up with Irony?

**Comment by JeremyDaug** [comment]
They physically disappear from the folder. Also, when trying to run mods from the paradox launcher it doesn't delete, but it doesn't load the mods either.

**Comment by bcssov** [comment]
In the options do you have ticked refresh descriptors before playing? This could be why Irony deletes *.mod files.
But if it doesn't recreate them that means it cannot locate them.

**Comment by JeremyDaug** [comment]
I had it set for Refreshing descriptors before play, but I also tried to remove that and it still seemed to do it.

**Comment by bcssov** [comment]
After this is turned off Irony will no longer delete descriptor mods. But this is not the root cause of the problem. The root cause is that mods don't appear to be properly installed on your computer. This function deletes and recreates all mod descriptors from mod location sources Irony is able to find. 

I believe you should have a warning prompt or question from Irony complaining about invalid mods detected, if so this means that these descriptor mods point to a location on your computer which simply does not exist and explains why pdx launcher also does not load any mods.

**Comment by JeremyDaug** [comment]
Ok, you seem to be correct, unselecting that stops the deletion. It seems that something doesn't like it and it's unable to find the workshop mods. It doesn't seem to like where they are stored on Linux. Trying to go to it from Irony returns a Does Not Exist error. 

The not running the mods is definitely a problem with Stellaris.

**Comment by bcssov** [comment]
If memory serves me correctly for Linux Irony looks in this location for it: /home/{user}/.local/share/Steam/...
That's the official install location I believe and the one I support.

**Comment by JeremyDaug** [comment]
Sorry, I meant when doing the Open Mod Folder/File on a particular mod. It says it doesn't exist, which is strange because I'm looking at that exact location and it's there.

**Comment by JeremyDaug** [comment]
I'm going to close this as this doesn't seem to be the problem I'm having.
