### ISSUE TITLE
Segmentation fault in Conflict solver

### ISSUE THREAD

**Issue by HeathenHacker** [bcssov/IronyModManager#352]
**Describe the bug**
Segmentation fault when using the conflict Solver for Stellaris under Linux

**To Reproduce**
Start the conflict solver, once it reaches 100% on step 6 the manager crashes (SIGSEGV)

 - OS: arch linux kernel version 5.16.16-arch1-1
 - Irony Version 1.21.130+9d671b6620

**Comment by bcssov** [comment]
I've never been able to fully isolate or to be more precise recreate an environment myself to see what's going on under these circumstances. All I know is that it's tied to fonts somewhere that are missing under certain situations (maybe heavily customized distros, slimmed or missing packages). For people like with problems similar to yours theirs this workaround: https://github.com/bcssov/IronyModManager/issues/322#issuecomment-993182022

**Comment by HeathenHacker** [comment]
thx, that worked
