### ISSUE TITLE
[Stellaris] Force resource loading first/"Unexpected Token" fix

### ISSUE THREAD

**Issue by i2amroy** [bcssov/IronyModManager#356]
Not quite sure if this is a feature or bug since it's more a way to work around a limitation of the Stellaris parser itself.

The issue is that apparently if you try to load too many things before loading Stellaris's basic resources (i.e. 150+ mods worth of FIOS conflict resolutions) then the parser starts collapsing from the number of unresolved references before it ever gets to the resource file to resolve them (this will probably happen for any case with like 1000+ unresolved references, but resources are the major one since they show up in like 90% of entries). This makes the game crash the instant that you click on the "new game" button from the main menu, while spitting out a huge number of lines into error.log that look like this:

`[23:00:12][persistent.cpp:35]: Error: "Unexpected token: unity, near line: 280`
`" in file: "events/my_modded_actions.txt" near line: 361`

The solution is as follows:
1. Create a local mod with a copy of the resource files that starts with "!!!_"
2. Irony will now move it's resource entries into a "!!!!!!_irony_merged.txt" file.
3. Because this file comes before the normal conflict resolution files asciibetically it gets loaded first, meaning no unresolved references and no crashing parser.

One way this could potentially be "fixed" on the Irony side would be to have an option to always generate a merged resource file with a name that lets it load before all the other conflict resolution files.

No priority though! (Especially since I know you mentioned you were taking a break in the discord). I don't think there's exactly a lot of us out here with 150+ mod compilations we're resolving conflicts for, and those that are running that large of a compilation probably have enough know-how to be able to follow the solution steps above on their own. I mainly just wanted to make sure to get this written down somewhere so future people looking for answers might be able to find it and use your great tool to push the limits a little more.

**Comment by bcssov** [comment]
It's neither:
1. Irony already provides zero byte files to all other strategic resource entries
2. Irony already merges resources in a single file named !!!_irony_merged.txt

This seems like your problem might be elsewhere.

**Comment by i2amroy** [comment]
After our discussion on discord I suspect that this is potentially due to something going sideways after multiple months of updates. Seems to be properly generating the file every time now, so closing this unless it happens again.
