### ISSUE TITLE
Always crash on ubuntu/gnome based systems

### ISSUE THREAD

**Issue by l7943416** [bcssov/IronyModManager#357]
**Describe the bug**
Always crash on ubuntu/gnome based systems

**To Reproduce**
1.open iroly
2.no action
3.wait a minute
4.automatic crash

**Expected behavior**

**Screenshots**

**Logs**

022-04-24 03:16:15.5587 Version: 1.21.131+f60aeacd91
OS Description: Linux 5.16.19-76051619-generic #202204081339~1649696161~22.04~091f44b SMP PREEMPT Mon Apr 11 17
Runtime Identifier: pop.22.04-x64
 Tmds.DBus.DBusException: org.freedesktop.DBus.Error.UnknownMethod: 没有“Destroy”这个方法
   at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)

**Version:**
 - OS: [e.g. pop.22.04-x64]
 - Irony Version [e.g. 1.21.131]

**Additional context**

**Comment by bcssov** [comment]
I'm guessing you're missing a package for this particular OS (don't know which). I've tried (just in case) Irony on Ubuntu based VM, it started without any issues. I also had recently got a ticket opened from a person running Irony on pop OS, their problem was related to steam installation but they seemed to run Irony just fine there as well.

For a start try these options which are exposed for Linux distros:
https://github.com/bcssov/IronyModManager/blob/f60aeacd9115196f12ebca43b2f7cef6c1b9e700/src/IronyModManager/appSettings.json#L11-L16

As well try turning on this option (it has been known to fix issues on some distros):
https://github.com/bcssov/IronyModManager/blob/f60aeacd9115196f12ebca43b2f7cef6c1b9e700/src/IronyModManager/appSettings.json#L9

**Comment by l7943416** [comment]
I tried the solution you suggested
invalid
This problem only occurs in the gnome desktop environment
There is no problem with kde of manjaro

**Comment by bcssov** [comment]
Irony doesn't hate gnome: ![Image2](https://user-images.githubusercontent.com/5864390/164968993-d01c2829-32d0-429b-af20-37c4afe1a0d4.jpg)

It's gotta be a missing package...

**Comment by l7943416** [comment]
Can know what package is missing
What dependencies are needed
I go to install

**Comment by bcssov** [comment]
I honestly have no idea.

**Comment by l7943416** [comment]
I just tried it, it's a locale problem
I use Chinese, error
I use English, no problem

**Comment by bcssov** [comment]
That's interesting, Irony should not have problems with the locale. This indicates an issue with fonts being used (perhaps a missing font package). In cases such as these this should have fixed the issue:

> As well try turning on this option (it has been known to fix issues on some distros):
> https://github.com/bcssov/IronyModManager/blob/f60aeacd9115196f12ebca43b2f7cef6c1b9e700/src/IronyModManager/appSettings.json#L9

This forces Irony to use inbuilt fonts. I'm unaware of any locale problems with either Irony or Avalonia.
