### ISSUE TITLE
Search filter extension

### ISSUE THREAD

**Issue by Arkhorse** [bcssov/IronyModManager#358]
Extend the search filter to allow for and / or of the same filter types. OR would work so that if any of the options match, show the mod. AND would operate so that all options must match

OR EG: `source:steam|paradox`, `version:3.*.*|*.*.*`
AND EG: `source:steam^paradox`, `version:3.*.*^*.*.*`

Additional possible methods to do this:
Possibly a dropdown to select source and versions the user wants to view. Maybe a checkbox above the search box to ignore merged mods.

**Comment by bcssov** [comment]
Note: Just the or operator is applicable.
