### ISSUE TITLE
Clarification for updating mods that are merged?

### ISSUE THREAD

**Issue by hifiguyy** [bcssov/IronyModManager#359]
Just wondering what the process is? Do we replace the updated mod and hit merge again, or do we have to make a new collection, delete the merged files, re add the mods, re sort, and then merge again?

Cheers

**Comment by bcssov** [comment]
Going to change labels.

The process would be to go to the original collection (non merged) make any changes there and hit merge. Irony will create a new merge under a new name. After that you can then delete the old merge collection.

**Comment by hifiguyy** [comment]
awesome thanks

**Comment by bcssov** [comment]
I do not follow the question. Mod descriptors that Irony detects only point to a folder so there never is or will be a need to recognize an updated mod.
