### ISSUE TITLE
[Ck3] Game crashes with exported or merged collections

### ISSUE THREAD

**Issue by Nilserich** [bcssov/IronyModManager#360]
**Describe the bug**
The game crashes as soon as I start the game with an exported or compressed merged collection. A basic merged collection does not apply at all (The game starts, but the mods are not active ingame). 

If I start the exact same collection with the mods downloaded directly from the workshop, the game starts properly.

**To Reproduce**
1. Create a collection with Steam Workshop mods.
2. Create an export/compressed merge/basic merge from this collection
3. Import the new exported/compressed merged/basic merged collection and apply it.
4. launch the Game through the Mod Manager. 

**Expected behavior**
The game starts with mods from the export/compressed merge/basic merge applied

**Screenshots**
-

**Logs**
The Mod Manager does not create an error log

**Version:**
 - OS: [Win10]
 - Irony Version [1.21.133]

**Additional context**
-

**Comment by bcssov** [comment]
That's a game problem as it maybe doesn't support these features then. Nothing that I can do about it. Or maybe the game has some kind of quirk that it doesn't like local mods.

**Comment by Nilserich** [comment]
Thanks for the info that the mod manager can't be the cause of the problem.

**Comment by bcssov** [comment]
Unless there's a special command argument being passed to CK3 exe then that's not related to Irony. The only communication that Irony and the games have are via:
* dlc_load.json
* Command line arguments
