### ISSUE TITLE
filtered IgnoreAll

### ISSUE THREAD

**Issue by shadoxxhd** [bcssov/IronyModManager#363]
**Is your feature request related to a problem? Please describe.**
Right now, when mod A is a patch for mod B, I need tomanually ignore or resolve every single change, even though I know I'll always keep the patch version.

Example: Acquisition of Technology is supposed to always overwrite The Zenith of Fallen Empires

**Describe the solution you'd like**
It would be nice if I could say eg. "ignore all cases where mod A overwrites mod B". The simplest case is designating a mod as a patch for another, so all overwrites are automatically authorized. A patch can overwrite multiple mods, and a mod can be patched by multiple other mods, so you should be able to add arbitrarily many patch combinations.

A more powerful version would apply some logical rule system, so eg. filtering for file path/filename/etc. would also be possible (eg. ignore all overwrites of mod A over B in a path matching C, or ignore overwrites of any mod over mod A for gfx and localization, or ignore all localization overwrites in general)

This is different from ignore rules, which can't move items into the "ignored" bin, and also can't filter by mod combination (as far as I can tell).

**Comment by bcssov** [comment]
I believe this suggestion is covered by these 2 existing tickets:
#99
#214

Can you check and confirm?

**Comment by shadoxxhd** [comment]
Not quite. One difference is in the proposed solution - my idea was a function to batch-move individual conflicts to the "ignored" list (like selecting "ignore" for each one), while the other suggest an extension to the permanently active ignore rules.

Being able to ignore differences between 2 mods is an alternative to the "simple" part of my idea, but the "is a patch for" designation might also add value later down the line, in case some system for publishing conflict resolutions would be developed (as well as adding value in the context of static ignore rules, since it would flag any case where eg. Zenith overwrites Acquisition in my example, whether through wrong load order or modder mistake).

The more complex rules are not covered at all by the other tickets, and might be hard to manage with a static ignore rule system (and more convenient with a "batch move to ignored" approach).

**Comment by bcssov** [comment]
Note for future reference. Conflicts with:

#99
#214

Have to decide which approach to use when these come to turn.

**Comment by shadoxxhd** [comment]
#99 is not enough if you want one mod to overwrite the other, but not the reverse. If overwriting doesn't depend on load order, the source mod might overwrite the patch, which you might want to fix yourself. So this relationship needs to be directional to cover all relevant use cases.

**Comment by bcssov** [comment]
Closing this in favor of the mentioned 2 tasks. New mod filter behavior change allows partially something like this.
