### ISSUE TITLE
Unable to activate mods (win-x64-setup.rar-latest version)

### ISSUE THREAD

**Issue by GitWolf22k** [bcssov/IronyModManager#364]
Having an issue where i can see all my installed mods but i can't activate any of them. All the directory settings are right. I have tried reinstalling Irony. I have set exclusions in Anti-Virus & Fireawall. I have tried removing all mods but one from the directory in the case that one of the mods was causing a conflict. I have tried using the previous version (v1.21.135) with the same issue. I have googled this issue (with no results).

I'm hoping someone has some suggestions. Thankyou in advance.

**Comment by bcssov** [comment]
Sounds like you haven't created the collection.

Here's a checklist for new users and see which step you've missed: https://github.com/bcssov/IronyModManager/wiki/New-User-Checklist
