### ISSUE TITLE
Output mod version when getting mod list (copy collection)

### ISSUE THREAD

**Issue by Arkhorse** [bcssov/IronyModManager#365]
Could you add the mod version to the output when someone uses the copy collection to keyboard? Would be useful info for debugging and for mod users when they ask for help

**Comment by bcssov** [comment]
This is going to break the export\import simplicity and readability and turn it into a csv. Not sure I want to go down that route.

**Comment by Arkhorse** [comment]
>

> This is going to break the export\import simplicity and readability and turn it into a csv. Not sure I want to go down that route.

Cant you add it to the line with the modname without using a column?

**Comment by bcssov** [comment]
And make my life even harder by having to manually strip the version. That's even worse.

**Comment by Arkhorse** [comment]
> And make my life even harder by having to manually strip the version. That's even worse.

Ah ok. Wasnt sure if it would be easier or not.

**Comment by MattMills** [comment]
FYI for stellaris mods at least, I'm planning on implementing an API that can use file checksums to identify mod versions, at least for the mod versions I know about, although it will basically require checksumming every file in a mod and comparing it against known checksums to find the most likely version number, which will likely be somewhat non-trivial for large mods.

This will eventually be a part of https://collect.dev.stellarstellaris.com/
