### ISSUE TITLE
Export mod collection not working

### ISSUE THREAD

**Issue by Mete0** [bcssov/IronyModManager#366]
**Describe the bug**
when exporting whole colelction, it gets stuck at 0.000% and never completes. occurs even when trying to export 1 small mod

**To Reproduce**
1. select any mod
2. export whole collection

**Expected behavior**
Collection exported into a zip file

**Screenshots**
https://ibb.co/GJHgGc4

**Logs**
If the application crashed add error logs related to the crash.

**Version:**
 - OS: Windows 11
 - Irony Version [1.21.144]

**Additional context**

**Comment by bcssov** [comment]
I need the Irony error logs, you can find them in %appdata%\mario\ironymodmanager.

As well I'd check your antivirus it most likely is blocking Irony somewhere.

**Comment by Mete0** [comment]
I was able to fix it by running the program with admin privileges
