### ISSUE TITLE
Improve JSON Deserialization

### ISSUE THREAD

**Issue by arieviillo** [bcssov/IronyModManager#370]
**Describe the bug**
During a simple "analyze" process the application crashed to desktop.

**To Reproduce**
Put 3 mods on my list and hit analyze
![Untitled](https://user-images.githubusercontent.com/103542481/173191644-b844478a-ac33-4a59-b3c2-f3cb02324ee1.png)

**Expected behavior**
A fix?

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/103542481/173191439-c228f95e-35b8-4f61-886f-3ebecf66c9fb.png)

**Logs**
[2022-06-11_Fatal.log](https://github.com/bcssov/IronyModManager/files/8884066/2022-06-11_Fatal.log)

**Version:**
 - OS: Windows 10.0.19044
 - Irony Version 1.21.151

**Comment by bcssov** [comment]
What are your system specs?

**Comment by arieviillo** [comment]
A potato noebook. Maybe something related to my ram?

Windows 10 Pro 21H2

64 bit Intel(R) Pentium(R) CPU  N3530 - 2.16 GHz
4gb ram
Intel HD Graphics

**Comment by bcssov** [comment]
Lack of RAM it seems.

**Comment by arieviillo** [comment]
So... a minimum recomended ram to use your app is +- 6gb? Bcuz 2 it's only for windows and plus 2 it's not enough.

**Comment by arieviillo** [comment]
Well if it was found that the problem is the lack of memory is the you can close the ticket. Thanks.

**Comment by bcssov** [comment]
I will not close as perhaps deserialization can be performed to be streamed which would consume less memory. Not a priority of course.

**Comment by arieviillo** [comment]
It's definitely memory usage.
![Untitled](https://user-images.githubusercontent.com/103542481/173200545-32e53260-127c-4fac-ae9b-95805ef7b3dc.png)

Just out of curiosity, how does this app use more memory and disk than the game itself? Even processing lines of code, there is nothing graphical or that uses the cpu itself.

**Comment by bcssov** [comment]
Because RAM fast and disk slow. It contains thousands of objects parsed and prepared for fast querying in memory on demand.
