### ISSUE TITLE
Invalid file catagory in the merge tool not being accurate for creating a custom patch

### ISSUE THREAD

**Issue by lyratcm** [bcssov/IronyModManager#372]
**Describe the bug**
Invalid file errors due to things like a missing closing } in the merge tool show the original line of the error whereas the custom patch tool ignores comments leading to the line not matching up

**To Reproduce**
1. have a mod not close it } correctly (or anything that would lead to the file showing up as invalid) that also has comments
2. try to find the line that irony says it at issue
3. that line will be different to the one errored due to it not including comment lines

**Screenshots**
![image](https://user-images.githubusercontent.com/13206890/174220413-a2eb8649-fee5-4ba0-900a-db38882fa984.png)
![image](https://user-images.githubusercontent.com/13206890/174220467-82d3fd46-599d-4da5-aa71-de3659968766.png)
there isn't even a line 773 in this custom patch

**Version:**
 - OS: win 11
 - Irony Version: 1.21.152

**Comment by bcssov** [comment]
Note: Not really a big priority

**Comment by bcssov** [comment]
This is unsolvable. Irony reports errors on actual file not for scenario where it has stripped down comments. So either report inaccurate virtual code info or actual file info. I chose to report actual file errors. Won't fix.
