### ISSUE TITLE
Conflict Solver - File Last Modified

### ISSUE THREAD

**Issue by Sindusk** [bcssov/IronyModManager#373]
**Is your feature request related to a problem? Please describe.**
When the conflict solver resets the status of a conflict with multiple source files, it can be difficult to track down which one was recently changed. If only one file out of 10 was changed, scrolling through trying to find the one that changed can be time-consuming and tedious.

**Describe the solution you'd like**
It would be a great help if the conflict solver window included the "last modified" date and/or time of the source file you're looking at.

**Describe alternatives you've considered**
Can't think of any.

**Comment by Factor2** [comment]
Came here (GG from stellaris modding den dc) to suggest this as a feature but its all done. +1 to Sindusks suggestion. Delete this comment np if you want to keep things clean
