### ISSUE TITLE
Conflict solver patch generation has non-deterministic output on different PCs

### ISSUE THREAD

**Issue by gab** [bcssov/IronyModManager#375]
**Describe the bug**
The patch generated by the conflict solver is detected as having many different files on two different computers when validating checksums, despite mod content itself being strictly identical.

**To Reproduce**
1. Subscribe All to Stellaris Ultimate Pack 3.4 https://steamcommunity.com/sharedfiles/filedetails/?id=1220270825
2. Create an Irony collection called Stellaris Ultimate 3.4 using the load order from this post https://steamcommunity.com/workshop/filedetails/discussion/1220270825/4658416565931409001/?ctp=3#c3423312514213004814
3. Run the conflict solver in Default mode and hit Back
4. Export collection hashes for verification
5. Run steps 1-3 on another computer B.
6. On computer B, verify the hashes exported from computer A.
7. Notice that the validation confirms that all mod contents is identical, but reports tons of discrepancies between files of the generated patch.
8. Notice that the game's checksum also ends up different on each computer.

**Expected behavior**
Running the conflict solver in the same mode on the same mod content should yield exactly the same auto-generated patch, even on different machines.
This is necessary so that people can play in multiplayer while benefitting from the conflict solver's automatic fixes, without having to resort to a full collection export, and the delays and online hosting and downloading that entails.

**Version:**
 - OS: The two computers used were under Windows 7 x64 and Windows 10.
 - Irony Version [1.21.152](https://github.com/bcssov/IronyModManager/releases/tag/v1.21.152)

**Additional context**
It's possible I'm not interpreting correctly, and that it's actually the hashes export and verification which is somehow faulty and reports false discrepancies for the patch generated by the conflict solver.

The non-deterministic behavior I'm detailing here seems to create fear around the Conflict Solver. The instructions received from a lot of people are to NEVER touch the Conflict Solver unless you know what you're doing. It would be much better if people could be encouraged to always run it to benefit from automatic fixes. The risky part should be manual merging, not running the solver.

**Comment by gab** [comment]
We were using the exact same load order, since the checksum validation didn't find any difference except in the auto-generated patch. We were also both on Windows, although Windows 7 and 10, so I don't see how line endings could be involved. There must be something else going on, that makes the patch generation inconsistent from run to run. This might be causing hard to spot bugs and shouldn't be brushed-off.

Regarding the things that can go wrong:

1. People can hit a lot of buttons or even move files accidentally in explorer without being aware, so I don't really see how that's relevant. People in my group might not be computer wizards but they're smart enough to follow the instruction "run the conflict solver on Default and hit Back when it's done without touching anything else".
2. Since the number of Irony users knowledgeable enough to resolve things manually is always going to be a tiny minority (and more so if the program keeps getting more popular), this is not a factor in most cases.
3. They will if they copy-paste the load order provided through some chat software, which is easier than uploading a file somewhere.

From what I understand using only the load order is a mistake, since you're missing out on some automatic fixes. So I don't consider this an option.

The workflow I had in mind for every player:
- subscribe to some Steam collection
- import load order through chat or forums (no file needed)
- run conflict solver
- play
Then before subsequent sessions:
- run conflict solver
- play

What I like about this workflow is that if you have three people playing Stellaris with the same modpack they initially set up together, everyone can do their own maintenance on their end after workshop updates come in, including running the conflict solver. Perhaps they also play a couple solo games to explore the mods on their own. Then when it's time to play together again, they can have Stellaris up and running on time for the beginning of the multiplayer session. If everyone then has the same checksum, it's great because the group starts playing right away. **The key difference is that you only wait for one person to export and upload and for everyone to finish importing if there's a problem,** instead of always.

(What would be great, though, is a collection export that combines not only load order and patch mod but also file checksums, guaranteeing that you're 100% ready to start playing if you import it successfully. I might open a suggestion for that.)

**Comment by bcssov** [comment]
About patch generation being consistent that's something that I've tested for a while (it was a single computer though) but it was always consistent under the same exact conditions.

One of your friends could still not have Irony pointed towards the exe. Exe determines whether Irony will see the game and be able to use data from the game itself during conflict solving process which also could influence what kind of files are dumped into the patch mod.

When a large group of people are involved and not all of them are tech savvy I usually attribute these to one of the following:
1. Steam going crazy and mod files are not in sync (happens a lot)
2. People have extra files in their games
3. Not the same game version

I've given you the recommended methods to play MP, your is not exactly supported (never was).

**Comment by gab** [comment]
The test reported above was done with only two people, and the friend in question happens to be tech-savvy and experimented in modding games in general (as a mod user). Moreover, I guided him through every single modding step and he never fiddled with the mods without me.

We managed to play a game together right after experiencing the problem reported in the OP: he did a full export and I imported it. This rules out Irony not pointing towards the .exe, as we both started the game through Irony.

Regarding the usual suspects:

1. Since the checksum validation passed on workshop mods, Steam wasn't going crazy and mod files were in sync.
2. After using a full export, the game checksum was identical and we could play in multiplayer, ruling out the extra files theory (and I know for a fact my friend didn't add files to his game directly).
3. Same checksum, so same game version and same files.

All in all I think my bug report is solid.

As for the MP sync method, we'll fall back on what you're recommending for now, although I hope you'll reconsider.

**Comment by bcssov** [comment]
Upon further inspection on the left you can see win7 and on the right you can see win10 patch mod. Identical mods and load orders.

![Image1](https://user-images.githubusercontent.com/5864390/175663311-4e66fac6-726b-4d33-ad50-aedcd878662d.jpg)

All dumps are the same, except a merged file which is also consistent. The naming of variables is out of order as the variables are written in async loop and generally are named on first come first serve logic (their values are the same of course). Irony ensures that the variables have unique names and duplicats them to make my life easier.

![Image4](https://user-images.githubusercontent.com/5864390/175663318-e08692d7-f231-47ac-a4c3-cc787d3288f1.jpg)

I see nothing wrong here.

**Comment by bcssov** [comment]
There's been a commit which might produce a more consistent files. No guarantees (it's in the latest version).
