### ISSUE TITLE
Deactivate a mod while leaving it in the collection

### ISSUE THREAD

**Issue by gab** [bcssov/IronyModManager#377]
**Is your feature request related to a problem? Please describe.**
I jump between three modpacks as I test various mods with friends, so I'm subscribed to a *lot* of mods. This means that if I want to remove a mod from my load order temporarily to test something or diagnose a bug, the mod in question gets lost in a sea of other mods and can be hard to find again.

**Describe the solution you'd like**
I'd like to be able to uncheck a mod in a collection without removing it from the collection. The mod would stay in the collection for display purposes, but its files would otherwise not be used, and it would not use up a number in the load order.
Deactivated mods would not be exported, to avoid complicating the export format.
To remove a mod completely from a collection, there would be a Remove from Collection context menu entry.

**Describe alternatives you've considered**
One can always take notes to remember which mods he removed from the collection, or try to remember part of the name and use text search.

**Comment by bcssov** [comment]
Closing as this requires significant UI workflow change and json spec export change. Irony collections existed **before** paradox launcher had playsets. There is a suggestion related to workflow changes on the discord therefore any potential tasks there will be tied to these if these are accepted.
