### ISSUE TITLE
Full collection import breaks ability to load UI Overhaul Dynamic and likely other Workshop mods

### ISSUE THREAD

**Issue by gab** [bcssov/IronyModManager#378]
**Describe the bug**
Importing a full collection export breaks the ability to load UI Overhaul Dynamic when the latter's workshop version is added to a new collection. Tiny Outliner v2 and probably all workshop mods are also affected.

This was reproduced after doing a complete wipe and reinstall of Stellaris, Paradox Launcher, Irony and all their settings, i.e. starting completely from scratch.

**To Reproduce**

1. Subscribe All to Stellaris Ultimate Pack 3.4 https://steamcommunity.com/sharedfiles/filedetails/?id=1220270825
2. Create an Irony collection called Stellaris Ultimate 3.4 using the load order from this post https://steamcommunity.com/workshop/filedetails/discussion/1220270825/4658416565931409001/?ctp=3#c3423312514213004814
3. Run the conflict solver in Default mode and hit Back.
4. Do a full export of the collection.
5. Import the resulting zip file
6. Create a new collection containing only the Workshop version of [UI Overhaul Dynamic](https://steamcommunity.com/workshop/filedetails/?id=1623423360)
7. Launch the game
8. Notice that the mod didn't load properly and that only the vanilla UI is showing.

Note that wiping the My Documents\Paradox Interactive\Stellaris folder restores the ability to load workshop mods normally.

**Expected behavior**
A full import shouldn't break the ability to load workshop mods.

**Version:**
 - OS: Windows 7 x64
 - Irony Version [1.21.152](https://github.com/bcssov/IronyModManager/releases/tag/v1.21.152) and 1.21.154

**Additional context**
Since this affects the game, I imagine it could affect the patch generation too? Might explain the weird patch generation behavior I reported.

Theory: perhaps filling the mod registry with so many local mods triggers some kind of mod limit?

**Comment by bcssov** [comment]
Sounds like double mod name bug as in game doesn't work well if you got 2 mods with the same name installed. Can you confirm? I don't have time to currently test with this collection + my internet download speed is not the best at the moment and the following collection has some gargantuan mods.

If that is the case that would not be exactly a bug but but not be a feature either. A workaround can be made by changing mod names during export to make them more unique.

**Comment by gab** [comment]
double name bug seems to be it. Exporting then importing a full collection (no patch mod needed) containing only UI Overhaul Dynamic is sufficient to break the loading of its workshop version, but it doesn't break other workshop mods  - at least, Tiny Outliner v2 which I tested was working.

It's a pretty silly implementation on Paradox's side since they have mod IDs, so why would they require unique names too... insert facepalm.

**Comment by bcssov** [comment]
You'd have to ask paradox. I don't want to invent a new label so just gonna label this bug and feature.
