### ISSUE TITLE
Fatal Error while loading mod definitions.

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#38]
Timestamp 2020-04-26 05:44:22.4353 was before I deleted the .35 alpha patch mod.

Timestamp 2020-04-26 05:57:14.8583 was after deleting the .35 alpha patch mod and the Event Horizon Offset Facility mod and its UI patch from the collection,

Edit: this is the mod it trips up on: https://steamcommunity.com/sharedfiles/filedetails/?id=682691478 will cause the fatal error on its own.

[2020-04-26_Error.log](https://github.com/bcssov/IronyModManager/files/4534636/2020-04-26_Error.log)

**Comment by bcssov** [comment]
It's CWTools bug.

**Comment by bcssov** [comment]
Gonna have to wrap CWTools in try\catch. If it spits out an error then fallback to mine simple parsers.
