### ISSUE TITLE
When I launch the game, it won't have any mods.

### ISSUE THREAD

**Issue by hiphop4eva** [bcssov/IronyModManager#380]
I load all the mods I need to the manager and press apply, and it says they were successfully applied. Then I launch the game. But when I start playing there are no mods, it's just vanilla Stellaris. I tried to open the game with the Paradox Launcher at it works perfectly fine.

Irony Launcher v1.21.158
Stellaris v3.4.5

**Comment by hiphop4eva** [comment]
Sorry that's not what I meant. The dlc's are fine. The mods don't work.

**Comment by bcssov** [comment]
This has so far been shown to be a user error. Most common ones are:

1. Make sure irony is pointed towards the correct data directory in documents\paradox interactive\stellaris
2. Don't run pdx launcher at the same time as irony
3. Check whether you're using onedrive, stellaris and pdx launcher might be looking there
4. Check whether antivirus is interfering

**Comment by hiphop4eva** [comment]
I've made sure that it's pointed in the correct folders. I'm not running both launchers at the same time.
How do I know if the launchers are looking at OneDrive or not? I never really use OneDrive and the Irony Launcher is targeted at the correct folders. I tried to also make sure to add the Irony Launcher as an exception to antivirus. It still doesn't seem to work.
There are mod files inside the Stellaris/data folder, but when I start playing the game won't recognize any mods when I run with the Irony Launcher.

**Comment by hiphop4eva** [comment]
I experimented a little and it seems that irregardless of what mods I use with Irony, the game launches with the mods that I enabled with the Pdx Launcher. So I open pdx, enable some mods, close it, and then open Irony and start the game from there. And the game will completely ignore Irony's modlist and start with the mods that were enabled with pdx.

**Comment by bcssov** [comment]
> How do I know if the launchers are looking at OneDrive or not?
Track where pdx launcher writes\modifies files

> I experimented a little and it seems that irregardless of what mods I use with Irony, the game launches with the mods that I enabled with the Pdx Launcher. So I open pdx, enable some mods, close it, and then open Irony and start the game from there. And the game will completely ignore Irony's modlist and start with the mods that were enabled with pdx.

Pdx launcher overrides dlc_load.json all the time it's why I mentioned to not run irony and launcher at the same time.
