### ISSUE TITLE
Stellaris DLC detection

### ISSUE THREAD

**Issue by Meeperdude** [bcssov/IronyModManager#385]
**Describe the bug**
On the OSX version, stellaris will not detect any purchased DLC if launched via Irony Mod Manager
**To Reproduce**
1. open irony mod manager
2. launch Stellaris through Irony mod manager
3. see that any save games created with DLC are unlaunchable
4. 

**Expected behavior**
Stellaris will remember dlcs purchased on steam
**Screenshots**

**Logs**
If the application crashed add error logs related to the crash.

**Version:**
 - OSX
 - Irony Version 1.21.158

**Additional context**

**Comment by bcssov** [comment]
1. 1.21 version is no longer supported
2. Irony has nothing to do with DLC detection, this is validated against steam as far as I'm aware
3. Irony tries to run steam before running the game in the hopes of steam being ready. You can try to manually run steam before Irony which could help.
4. 1.22 has better steam ready detection which should help

This is not an OS specific problem.
