### ISSUE TITLE
Issue applying/saving modlists

### ISSUE THREAD

**Issue by weMAYid** [bcssov/IronyModManager#391]
[2022-08-25_Error.log](https://github.com/bcssov/IronyModManager/files/9428347/2022-08-25_Error.log)

not sure how i broke it

**Comment by bcssov** [comment]
https://github.com/bcssov/IronyModManager/issues/200#issuecomment-783788786

**Comment by weMAYid** [comment]
that fixed my issue! thank you very much for your time.
