### ISSUE TITLE
stellaris' common/terraform should be DUPL and not LIOS

### ISSUE THREAD

**Issue by sommio** [bcssov/IronyModManager#392]
**Describe the bug**
stellaris' common/terraform should be DUPL and not LIOS

**Expected behavior**
Describe common/terraform as DUPL

**Screenshots**

![屏幕截图(16)](https://user-images.githubusercontent.com/64189793/190534744-816e1e88-cb23-4988-8da3-5a0cc8729e6f.png)

**Version:**
 - OS: Windows 10 LTSC 2021
 - Irony Version 1.23.43

**Additional context**
I wish it could be like this
![屏幕截图(16)](https://user-images.githubusercontent.com/64189793/190535463-6dba6004-f3a7-45d5-a766-dd93118cae91.png)

**Comment by bcssov** [comment]
Irony does not have "dupl" type and treats these as LIOS. However it is aware that internally some folders need to be de-duplicated (as in overwritten with zerobytes and does this) to ensure only 1 item is present in the game.
