### ISSUE TITLE
Steam thinks Irony is Stellaris

### ISSUE THREAD

**Issue by lordlony1** [bcssov/IronyModManager#393]
When closing game as long as Irony Mod Manager remains open, steam believes the game is still running.
This is preventing Stellaris from updating well Irony is open, making it harder to work though checking mods.

**Comment by bcssov** [comment]
This was raised on discord a while ago and it's a steam issue not Irony.

> Sometimes when Irony tries to run steam games steam does not properly start (if not running) and does not validate properly dlcs. The latest version to circumvent this integrates via steam_api to detect whether steam is running. Meaning it introduces itself as host process for the game in order to perform some checks like: whether steam is running, whether you're logged in to ensure that it can safely proceed and start the game. Immediately after that is done Irony unregisters itself and tells steam "please unregister me I'm done". Steam does not obey and still tracks child processes (so it's a steam issue). See explanation: https://wiki.facepunch.com/steamworks/Installing_For_Unity#shuttingdown
> 
> Don't like this? Revert legacy behavior (it's still there) https://github.com/bcssov/IronyModManager/blob/30bddd183cec511a3beb2729d172bdaa5f551456/src/IronyModManager/appSettings.json#L21
