### ISSUE TITLE
External Merge isn't showing up in the Editor.

### ISSUE THREAD

**Issue by jusitnboggs** [bcssov/IronyModManager#394]
External Merge isn't showing up in the Editor.

**Comment by bcssov** [comment]
In conflict solver you mean? You need to set the path to the executable in the options.

**Comment by jusitnboggs** [comment]
I have. I even hit the test button and it works.

**Comment by bcssov** [comment]
Set editor args too, Irony only knows it must launch a program but doesn't know how to pass left and right file args to it.

**Comment by jusitnboggs** [comment]
I'm using visual studio code do you know what arguments I need?

**Comment by jusitnboggs** [comment]
Thx for the example.
