### ISSUE TITLE
(Not tech savvy) Keep getting Fatal Error 

### ISSUE THREAD

**Issue by ThatApollo** [bcssov/IronyModManager#396]
**Describe the bug**
I keep getting a Fatal Error when I try to start the Mod Manager.

**Screenshots**
![Fatal Error 1](https://user-images.githubusercontent.com/115643956/195367774-5e96fc10-9389-4ab9-a678-64b65d459151.PNG)
![Fatal Error 2](https://user-images.githubusercontent.com/115643956/195367775-9583c3f9-b8e0-4bcb-a2e5-f2243f6d94cc.PNG)

 - OS: Windows 10
 - Irony Version v1.23.55

**Comment by bcssov** [comment]
See: https://github.com/bcssov/IronyModManager/issues/249#issuecomment-831664161

**Comment by ThatApollo** [comment]
Thank you.
