### ISSUE TITLE
allow user to stop irony from deleting decriptors when mods are missing

### ISSUE THREAD

**Issue by lyratcm** [bcssov/IronyModManager#399]
**Is your feature request related to a problem? Please describe.**
Irony removing mod descriptors with no way to stop "some mods are missing and have been removed from the collection automatically"
Theres no way to stop this when it happens leading to collections being wiped if the mods aren't installed at the that (such as not downloading to save space/declutter list or sometimes happens to mods from family sharing)

**Describe the solution you'd like**
Give the user an option like it normally does.
I can't see a reason that the user should be forced but having a collection partially wiped for no reason is painful

**Comment by lyratcm** [comment]
this sometimes happens when a mod is downloaded for an account that is family sharing the game but hasn't logged in, even if the files are still there
![image](https://user-images.githubusercontent.com/13206890/197332815-5ff9345b-afc1-4363-a7e2-ec762f4d0bef.png)

**Comment by bcssov** [comment]
The reason there is no choice is how Irony is written and designed. This whole section requires a rewrite of how Irony handles active mod collections and stores them. 

This also is conflicting with another ticket over at discord (it's in planning phase) so this is a duplicate.
