### ISSUE TITLE
Feature request : Navigable virtual Stellaris folder

### ISSUE THREAD

**Issue by calniotrey** [bcssov/IronyModManager#40]
Emulate what Stellaris would see once launched (so what will be overwritten is ommited).

Possibly just create a "Merge" button that creates a new mod for the collection containing all mods of the collection and the patch, without any overwrites.

That would be quite handy when trying to look into errors from error.log or just to find the definitions without having to find which mods add it first.

**Comment by bcssov** [comment]
Gonna put this on an undetermined version. Needs wireframing before I proceed.

**Comment by bcssov** [comment]
Think this is obsolete with all the various features out there.
