### ISSUE TITLE
Add Victoria 3 support

### ISSUE THREAD

**Issue by SocialistElmo** [bcssov/IronyModManager#401]
**Additional context**
Now that Victoria 3 is released i hope you can add a support for it :)

**Comment by SocialistElmo** [comment]
so i checked the discord sorry for bothering you

**Comment by bcssov** [comment]
Duplicate: https://github.com/bcssov/IronyModManager/issues/354

Closing. Note to anyone seeing this topic, there are major changes in how the mods are loaded\read (so on) in victoria 3 when comparing to CK3, EU4 etc So it might take a while
