### ISSUE TITLE
Added irony location in appdata

### ISSUE THREAD

**Issue by WeleSS2** [bcssov/IronyModManager#402]
If it's possible last run location (current .exe location) in irony settings in %appdata%. To retrive and use to run from other programs.

**Comment by bcssov** [comment]
%appdata%\Mario\IronyModManager-Location\last-known-location.json

json schema:
```
{
  "FileVersion": "1.24.39.56847",
  "Path": "Install folder",
  "ProductVersion": "1.24.39-alpha+de0ff6e446"
}
```
