### ISSUE TITLE
Steam thinks the game is running while Irony is running

### ISSUE THREAD

**Issue by Arkhorse** [bcssov/IronyModManager#406]
**Describe the bug**
If the game is launched from Irony, Steam will continue to think the game is running even when its exited

**To Reproduce**
Run game through irony
close game through any exit game button
see issue in steam

**Expected behavior**
Id assume steam would not think Irony is the game

**Version:**
 - OS: Windows]
 - Irony Version: 1.23.59

**Comment by bcssov** [comment]
It's been discussed already and it's steam fault not mine see:
https://github.com/bcssov/IronyModManager/issues/393
https://github.com/bcssov/IronyModManager/issues/398
