### ISSUE TITLE
Detect misplaced brackets in conflict solver

### ISSUE THREAD

**Issue by Arkhorse** [bcssov/IronyModManager#413]
So one of the issues I have with the conflict solver is that it cant detect when there are brackets in the wrong spots. This leads to issues that can only be resolved by manually editing the files or making a patch for those mods to work together. I would be nice if the solver could auto solve this issue (I know the game gives an error with `key={` as the main aspect of the error). 

One possible way is to detect changes in indentation and check if there is a bracket there or not

**Comment by bcssov** [comment]
This is beyond the scope of Irony. Even cwtools would have difficulty with this. Even visual studio tells you hey you got a problem in syntax on line xyz it does not autofix it. 

Rejected as out of scope.
