### ISSUE TITLE
Loading libhostfxr.dylib failed in OSX

### ISSUE THREAD

**Issue by inanx** [bcssov/IronyModManager#418]
**Describe the bug**

**To Reproduce**
1.  Download latest osx-x64.zip
2. Unzip to directory, add exec permission via chmod, run ./IronyModManager
3. It errors out with the following:

 `
Failed to load /Users/<redacted>/Documents/Paradox Interactive/Irony/libhostfxr.dylib, error: dlopen(/Users/<redacted>/Documents/Paradox Interactive/Irony/libhostfxr.dylib, 1): no suitable image found.  Did find: /Users/<redacted>/Documents/Paradox Interactive/Irony/libhostfxr.dylib: code signature in (/Users/<redacted>/Documents/Paradox Interactive/Irony/libhostfxr.dylib) not valid for use in process using Library Validation: library load disallowed by system policy
The library libhostfxr.dylib was found, but loading it from /Users/<redacted>/Documents/Paradox Interactive/Irony/libhostfxr.dylib failed
Installing .NET prerequisites might help resolve this problem.
https://go.microsoft.com/fwlink/?linkid=2063366
`

**Expected behavior**
Successfully open Irony Mod Manager

**Screenshots**

**Logs**
If the application crashed add error logs related to the crash.

**Version:**
 - OS: [MacOS 11.6.8 ]
 - Irony Version [1.24.107]

**Additional context**

**Comment by bcssov** [comment]
I would say it's an incomplete download or corrupt download or gatekeeper. Then I saw the version 1.5.xx has long ago reached end of life and is no longer supported. 1.24.xx version is latest please try that.

**Comment by inanx** [comment]
FIrstly, thanks for this. I checked the downloaded version and updated the comment. It could possibly be corrupt download, so I downloaded again. I unzipped, changed permissions and executed it but I got the same problem.

<img width="260" alt="ss 136" src="https://user-images.githubusercontent.com/13298466/209449033-43b330ce-6b0b-4499-9f4c-8abbb79235e3.png">

I actually have to go to the Finder and right-click to open IronyModManager, but just can't get past this libhostfxr.dylib popup.

**Comment by inanx** [comment]
Also, maybe related to this issue: https://github.com/bcssov/IronyModManager/issues/313#issue-1065547488

**Comment by bcssov** [comment]
This is probably gatekeeper, see: https://github.com/bcssov/IronyModManager/issues/119

I know for a fact when it's not interfering that Irony works. Some unrelated screenshots shared to me by one of testers using mac big sur (which is I believe your version).

![Image2](https://user-images.githubusercontent.com/5864390/209449345-9597ca0d-c919-4837-ad44-2b228f5cad38.jpg)
![img_3](https://user-images.githubusercontent.com/5864390/209449346-9bff4d8a-d872-4be4-8f0a-c19c61051d37.jpg)

**Comment by inanx** [comment]
I was able to make it work without doing anything spectacular. I just copied the whole IronyModManager folder to /Applications and renamed it IronyModManager.app and double clicked it.

I tested it in game and true enough my test mod was in there. Amazing!

Thanks @bcssov! Count me in as one of your mac testers.
