### ISSUE TITLE
Irony Cannot Detect Mods After Moving Workshop Folder

### ISSUE THREAD

**Issue by DovahFett** [bcssov/IronyModManager#419]
**Describe the bug**
After moving my Hearts of Iron IV installation to a new drive, including all of its Steam Workshop mods, Irony Mod Manager no longer detects the mods located on the new drive, even if the directory address is defined in the Custom Mod Directory option in the mod manager. I have checked, and the mods _are_ actually there, but it appears that Irony can't recognize them.

**To Reproduce**
1. Open Steam.
2. Open the _Settings_ window and navigate to the _Downloads_ tab.
3. Click the button labeled _Steam Library Folders_ and move Hearts of Iron IV to a different drive.
4. Open Irony Mod Manager and note the popup window notifying the user that their mods are now missing.

**Expected behavior**
The mod manager would recognize that the game and its mod had moved, and ask for their new locations, or at least be able to do so after being told where those new locations were via the directory configuration options within the mod manager.

**Screenshots**
Steam Storage Manager
![Storage Manager](https://user-images.githubusercontent.com/38407719/209455265-0b41ef34-3632-48bb-8259-f22e8251550d.png)
Missing Mods Error
![Missing Mods](https://user-images.githubusercontent.com/38407719/209455267-57949a32-d128-4af9-ac26-2e8f3031660c.png)
Directory Settings
![Configuration Options](https://user-images.githubusercontent.com/38407719/209455269-cc178364-ee64-4b94-8786-f8343be4ae74.png)

**Logs**
None

**Version:**
 - OS: Windows 11
 - Irony Version 1.24.107

**Additional context**
Irony is no longer located on the same drive as Hearts of Iron IV. I do not know if this issue is purely a product of the game being on a completely different drive, or just an issue with it being in a different directory. Ultimately, this issue might be more a feature request than a bug report.

**Comment by bcssov** [comment]
I suspect maybe steam needs to redownload all those mods. Irony autodetects workshop folders (plural). So meaning if you move it upon Irony restart it will be aware of all workshop folders by parsing steam files. The fact that custom mod directory does not download anything is just proof (also will generate duplicate mod detections so remove that setting).

**Comment by DovahFett** [comment]
So what do you think my best course of action is? Unsubscribing from the mods and then resubscribing? Deleting the mods manually, then resubscribing? Just deleting the descriptor files? I'd rather not redownload 60 GB of mods if I can help it, but if that's what needs to be done, then so be it.

If there's any more information (i.e. screenshots) that I can provide that may help, please let me know.

**Comment by bcssov** [comment]
What I'm about to suggest is potentially destructive operation therefore:
1. Backup Irony's database.json (database_1.24.json) or the whole Irony appdata folder.
2. Backup the game mod directory (due to descriptor.mods)
3. Launch Irony and do Delete all and reload and see the results

If you lost some mods from the collections restore (database.json). If nothing worked report back here and restore backups.

**Comment by DovahFett** [comment]
The "Delete All And Reload" command seems to have solved the issue. I no longer get the missing mod error when starting Irony. I had the same issue with my Stellaris mods (which I also moved to a different drive), and the "Delete All And Reload" command appears to have worked on that game as well. None of my mods seem to have been lost after running the command.

Thank you for your assistance.

**Comment by bcssov** [comment]
Usually Delete and reload is not a destructive operation (provided everything is setup properly -- no mods missing and such). You would have to perform a similar operation with pdx launcher to refresh descriptors since all of them were pointing towards the old location.
