### ISSUE TITLE
Save Error: CK3

### ISSUE THREAD

**Issue by MasuRii** [bcssov/IronyModManager#422]
**Describe the bug**
When I click apply for CK3, It says " Save Error "

**To Reproduce**
1. Irony Mod Manager
2. Apply Mods for CK3
3. Error
4. 

**Expected behavior**
I expect it will says " Collection Applied " just like in my stellaris mods

**Screenshots**
![image](https://user-images.githubusercontent.com/21298898/215299972-c41457c9-9d78-41c1-8c26-f4b6831f423a.png)

**Logs**
[2023-01-29_Error.log](https://github.com/bcssov/IronyModManager/files/10528768/2023-01-29_Error.log)

**Version:**
 - OS: Windows 10 Pro : 21H2 : 19044.1766
 - Irony Version v1.24.107

**Additional context**
None

**Comment by bcssov** [comment]
Delete pdx launcher sqlite dbs from ck3 docs folder and you should be set.

**Comment by MasuRii** [comment]
It works, thanks.
