### ISSUE TITLE
"Unhandled error ocurred" while resolving conflicts

### ISSUE THREAD

**Issue by HimitsuYami** [bcssov/IronyModManager#429]
[error.txt](https://github.com/bcssov/IronyModManager/files/10955598/error.txt)

I was trying to resolve some conflicts between mods and this happened. (also bonus typo issue. "ocurred" should be "occurred".)

**Comment by HimitsuYami** [comment]
Was scrolling through some of the invalid ones and got a second error.
[error 2.txt](https://github.com/bcssov/IronyModManager/files/10955684/error.2.txt)

**Comment by bcssov** [comment]
Duplicate: #426
