### ISSUE TITLE
installed mods completely greyed out no matter what I do

### ISSUE THREAD

**Issue by blvckdrxps** [bcssov/IronyModManager#437]
I've created multiple collections and its still fully greyed out, this worked perfectly until I updated now I can't even add in any mods to my collection whatsoever, previously all i had to do was just tick the box to send it over, now it just refuses to work.

**Comment by bcssov** [comment]
Nothing odd about it. Irony should have shown you a message box stating it detected invalid mods and thus prevents you from doing anything with them. 

Invalid mods are mods which point towards a non existing path. I believe Irony also asks you to delete or refresh mod descriptors as well.
