### ISSUE TITLE
Windows Security reports updater as Trojan

### ISSUE THREAD

**Issue by bfallstrom** [bcssov/IronyModManager#438]
**Describe the bug**
Windows 10 Virus & threat protection reports IronyModManager-Updater\win-x64-setup\win-x64-setup.exe as "Trojan:Script/Wacatac.B!ml"

**To Reproduce**
1. Run Irony Mod Manager version 1.24.119
2. Go to options screen when version 1.24.127 is available
3. Install updates

**Expected behavior**
Expected the mod manager to update to the latest version.

**Screenshots**
![Screenshot 2023-04-28 165428](https://user-images.githubusercontent.com/3976960/235271216-c54c6e30-f4aa-4ebc-8623-8d842576b774.png)

**Logs**
If the application crashed add error logs related to the crash.

**Version:**
 - OS: Windows 10 64-bit 22H2 19045.2846
 - Irony Version 1.24.119

**Additional context**
I expect that this is just a misidentification on the part of Windows but I want to raise it as an issue in case malicious code actually has been introduced somehow.

**Comment by bcssov** [comment]
Yes, it's a false positive and yes windows defender sucks. It's an age old problem of flagging inno setup installers.

1. https://stackoverflow.com/questions/68834409/program-installed-with-inno-setup-seen-as-trojan-wacatac-bml
2. https://answers.microsoft.com/en-us/windows/forum/all/windows-defender-trojanscriptwacatachml-keeps/93ef0ec1-3170-
48d6-86af-5373ff6c3cd1
3. Any other google search results will reveal similar results

Virus total scan clean
![Image2](https://user-images.githubusercontent.com/5864390/235272193-34bb1afc-2d13-4dce-8c65-9f751c614ccb.jpg)
https://www.virustotal.com/gui/file/3dc9cf51ba0dce53ab0843c4c8c45f61f70b27aeccadd8decefc4ddc61a7acfe?nocache=1
