### ISSUE TITLE
Feature Request: Right-Click > Open Folder for invalid mod files

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#44]
Just a QoL thing to make it easier to locally patch invalid mod files.

**Comment by bcssov** [comment]
I have no idea what you're talking about.

**Comment by LordOfLA** [comment]
In the conflict solver invalid files list. Would be handy to be able to right-click an entry and open its folder in explorer or whatever other OS default file manager.

**Comment by bcssov** [comment]
That's a bit much work (though it doesn't seem like it for this version). Putting it on 1.1.
