### ISSUE TITLE
Save Error - Something locking write to mod files.

### ISSUE THREAD

**Issue by fierycookies** [bcssov/IronyModManager#445]
Essentially, I just imported a collection, went to hit Apply and it pops an error up saying:
"Save Error
Something seems to be locking Irony's ability to write to mod files. Please report this on GitHub issue tracker and post the error log."
So I came here to ask how to fix this ofc.

It's not limited to if I import a collection or anything - it also says this when I press launch game. I'm modding Stellaris, just for the sake of information.

This does really screw with the game - when I click launch game, only some mods seem to load or it just crashes outright (not what it should be doing).

![image](https://github.com/bcssov/IronyModManager/assets/133870895/858a82b9-7ce2-4281-a6c8-df3a92fd8f74)

Here's the error log.
[2023-05-17_Error.log](https://github.com/bcssov/IronyModManager/files/11497351/2023-05-17_Error.log)

 - OS: Windows 11
 - Irony Version v1.24.127

**Comment by bcssov** [comment]
It's a corrupt pdx launcher database, wherever it happens just delete `launcher-v2.sql` and `launcher-v2_openbeta.sqlite` (if present). Files are located in docs\paradox interactive\stellaris ie.

**Comment by bcssov** [comment]
You are not doing something right. All your logs state one thing:

```
There are no database fields found for table 'playsets'. Make sure that the target table 
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: playsets'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: playsets'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: playsets'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: playsets'.
```

![Image2](https://github.com/bcssov/IronyModManager/assets/5864390/9766fdb8-78c6-4081-b93b-08bf7f554819)


Paradox still hasn't renamed or removed that table (still present in the latest beta).

Check your logs if they say the same thing then you are doing something wrong or it's the AV.

**Comment by fierycookies** [comment]
Managed to fix it! 

Thank you.
