### ISSUE TITLE
files that are outside of folders in a mod are all deleted even when useful

### ISSUE THREAD

**Issue by lyratcm** [bcssov/IronyModManager#448]
**Describe the bug**
While generally files that are in a folder such as common are just notes there are some files that have actual use. the main reason would be to overwrite a file that isn't in a folder in the stellaris directory. the main one here would be user empire designs to allow for sharing a preset of empires

**To Reproduce**

1. have a mod with a file outside of a folder (file attached)
[user_empire_designs_v3.4.txt](https://github.com/bcssov/IronyModManager/files/11634688/user_empire_designs_v3.4.txt)
2. merge that file
3. file will disappear from merge
4. 

**Expected behavior**
file remains in merge, out side of a folder

**Screenshots**
![image](https://github.com/bcssov/IronyModManager/assets/13206890/25dddce8-48ab-4c1b-8a57-85dbf978ce35)
![image](https://github.com/bcssov/IronyModManager/assets/13206890/1b791493-132f-460f-bc81-e7bbb3f917d7)

**Version:**
 - OS: win 11
 - Irony Version 1.24.128

**Comment by bcssov** [comment]
That's not a bug but by design.

**Comment by lyratcm** [comment]
If it is not a bug, I think an exception should be added for the files that appear outside the folder both in the documents directory and in the game folder.
empire designs are the only file I've really seen it with but there may be others

**Comment by bcssov** [comment]
Sorry I disagree, it's a design decision for Irony to only care about game folder structure folders. If someone is distributing some optional metadata they should use different means. 

I don't intend to switch to blacklist method where even git folders are copied because someone thought it was a good idea to distribute in there.

**Comment by lyratcm** [comment]
I was more thinking of specifically whitelisting the vanilla files outside of a folder but its not much of an issue to add a file or 2 on my ned post merge anyway
