### ISSUE TITLE
Query: Pair of mods ping-pong between LIOS and Load Order. Is this accurate or is code getting confused?

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#45]
To illustrate, install Ethics and Civics Alternative https://steamcommunity.com/sharedfiles/filedetails/?id=1790861374
and Relytor's Empire Governance https://steamcommunity.com/sharedfiles/filedetails/?id=1984230854

Run the solver and then scroll down the list in common\governments - you'll see they alternate between ethics having LIOS and Relytor's having Load Order. Is this correct display or is code getting confused?

I'm proceeding as if code is correct and pulling in the Relytor's data when Ethics is listed is LIOS.

**Comment by bcssov** [comment]
It's a simple so there isn't much room for confusion, nevertheless I'll check it.

**Comment by bcssov** [comment]
Looks correct for example:
- gov_anarchy_communism 
   - one comes from 00_governments.txt
   - one from ethics_somethingsomething.txt
- gov_assembly_of_clans 
	- both come from 00_governments.txt
