### ISSUE TITLE
Folders with custom icons in desktop.ini do not appear in import/export dialog

### ISSUE THREAD

**Issue by origintopleft** [bcssov/IronyModManager#452]
**Describe the bug**
Windows allows for custom folder icons to be displayed if specified in desktop.ini. It's certainly possible for a user to set arbitrary folder icons on just about anything, but most commonly this is found with cloud storage solutions, like Dropbox, or in my case Nextcloud, like below:

![image](https://github.com/bcssov/IronyModManager/assets/4407155/965a4520-3afa-42be-ab7f-9bb80b44c3c9)

In Irony, this folder isn't visible in the directory listing. It can still be navigated to by hand by explicitly specifying `C:\Users\Nicole\Nextcloud` in the top address bar, but it would be nice to be able to just double click it.

**To Reproduce**
1. Install a cloud storage solution, or set a folder icon in desktop.ini some other way
2. Open the import or export dialog.
3. Try to navigate to the iconned folder.

**Expected behavior**
Being able to double click into the folder with the customized directory icon.

**Version:**
 - OS: Windows 11 22H2
 - Irony Version 1.24.157

**Additional context**
Near as I can tell, this only seems to affect the Windows version of Irony; coming to Nextcloud on the Linux build seems unaffected. I haven't got a Mac so I couldn't tell you where that's at.

**Comment by bcssov** [comment]
These types of folders are nothing special. Irony iterates over the file system; not whether a file has "desktop.ini" or not. 

I already have a folder with desktop.ini setup and can access it without any issues within the folder browse dialog.

Regards
