### ISSUE TITLE
Relics are LIOS

### ISSUE THREAD

**Issue by F1r3Pr1nc3** [bcssov/IronyModManager#453]
I first wondered why two mods would make the same mistake, until I realized that Irony is wrong here (FIOS)
here is the log proof (from https://steamcommunity.com/sharedfiles/filedetails/?id=2990642451 or other):
`[07:01:32][game_singleobjectdatabase.h:153]: Object with key: r_toxic_god already exists, using the one at  file: common/relics/zzz_decision_toxic_relics.txt line: 10`

PS: Already mentioned this a month ago (via chat), but people like to see (time consuming) bug reports. :-P
https://stellaris.paradoxwikis.com/index.php?title=Modding&diff=75310&oldid=74099 (I always dishonor it when modders keep their modding knowledge secret but benefit from the knowledge of others.)

Thanks for the best Stellaris modding tool.

**Comment by bcssov** [comment]
I think I already said I need a reminder on github in the form of a ticket. Stuff in chat gets lost easily.

Changed in RC.
