### ISSUE TITLE
IMM Crash After Editing Collection or Conflict Solving

### ISSUE THREAD

**Issue by EverUniverse1** [bcssov/IronyModManager#458]
**Describe the bug**
A crash that occurs when editing the collection (adding/removing mods, changing the load order) and when conflict solving to edit the patch mod. I have reinstalled IMM multiple times, it didn't fix anything. I duplicated my collection and used the copy, still got the crash after trying to edit it.

**To Reproduce**
1. Open IMM;
2. Add/remove a mod, change the load order or conflict solve to edit a mod patch.

**Expected behavior**
The app shouldn't crash after/while doing these actions.

**Logs**
[2023-07-30_Fatal.log](https://github.com/bcssov/IronyModManager/files/12208254/2023-07-30_Fatal.log)

**Version:**
 - OS: Windows 10
 - Irony Version: 1.25.115

**Comment by bcssov** [comment]
Seems like state.irony in your patch mod is completely broken. You can do the following:
1. Delete the patch mod folder inside your mod directory
2. Go into the patch mod folder and see if irony.bak or irony.tmp is present and rename it to irony.bak. You will lose a few resolutions but better than the option 1.

**Comment by EverUniverse1** [comment]
What do you mean by losing a few resolutions?

**Comment by bcssov** [comment]
> What do you mean by losing a few resolutions? 

You lose the few x things you hit resolve\ignore on. Depending on the state of the .bak or .tmp snapshot. You lost the central DB by which Irony knows what was resolved\ignored.

> Also, is the patch mod folder the collection folder, or something inside it?

Patch mod is where all local mods are located. It's prefixed by IronyModManager_\<name of the collection\>.

> I have state.irony (no extension), state.irony.bak and state.irony.tmp in the folder, along with the other stuff.

Backup everything and try restoring one by one, if all fails your best bet is to delete the file completely and re-run conflict solver. Whole Irony mod patch collection will be reset, as I said this holds everything Irony knows about the current state of the mod patch.

**Comment by EverUniverse1** [comment]
So, I'll just delete the state.irony files one by one and try to run the conflict solver like that?

**Comment by EverUniverse1** [comment]
Well, it seems like deleting the state.irony file worked, although I have to solve all 261 conflicts again.
