### ISSUE TITLE
Fatal Error when ignoring conflicts

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#46]
Given the log file, I must be moving too quickly for threads to catch up. Jump to timestamp 2020-04-28 13:33:29.2770 - also it's not automatically closing, it's just sitting there.

[2020-04-28_Error.log](https://github.com/bcssov/IronyModManager/files/4545725/2020-04-28_Error.log)

**Comment by bcssov** [comment]
It indicates that something locked the file (it doesn't necessarily mean that it was Irony itself). This logic is that it is asynchronous which means it can be run on any thread and that task spawns another thread to work in the background while the whole logic is wrapped by an async lock. Meaning while the lock is active any thread coming in must wait to either read or write. Unless the external component that I use for the async lock I don't see a way of Irony locking itself out. Regardless I'll do some simulated runs to see.

**Comment by LordOfLA** [comment]
If I wait a bit after the overlay goes away before clicking ignore again it doesn't trigger the fatal error. If I click as fast as the overlay goes away it'll give me the fatal error fairly quickly.
