### ISSUE TITLE
Missing keys / id

### ISSUE THREAD

**Issue by F1r3Pr1nc3** [bcssov/IronyModManager#460]
There is one near-basic feature that seems to be overlooked. 
Irony can't seem to show missing keys/ids which will be removed if the file is completely overwritten.
I've often seen some mods completely overwrite files and then not update properly (even from experienced good modders) and newly added keys (or id) are missing, but Irony doesn't see this as a difference or error. (but this type of failure can often lead to a CTD).

Here is an actual (personal) case: 
https://steamcommunity.com/sharedfiles/filedetails/?id=2878075116

**Comment by bcssov** [comment]
This is not Irony's job. It's job is to indicate whether a certain duplicate item will be removed by other file overwrite.

**Comment by F1r3Pr1nc3** [comment]
Why so narrow minded? It is even more important to indicate that an item has been removed than that it has been replaced. It makes no sense to ignore it as it suggests false reliability.

**Comment by bcssov** [comment]
There is no narrow mindedness. In certain cases Irony will indicate item overwrite with empty comment provided there are no duplication. If however you have 2 or 3 conflicts or duplicates Irony will not show an artificial conflict like in the first case. It is however aware of the empty overwrite just not showing it. It's point is to show stuff that will be used by the game.
