### ISSUE TITLE
Greyed out mod selection checkboxes, unable to launch

### ISSUE THREAD

**Issue by gr33nranger** [bcssov/IronyModManager#472]
**Describe the bug**
I am unable to select any of my installed mods, the checkboxes are all greyed out, additionally I am unable to launch the game

**To Reproduce**
1. Launch Irony Mod Manager
2. Attempt to select any of the mods on the left

**Expected behavior**
The checkbox should show that it is selected when clicked on

**Screenshots**
![Screenshot_20231119_020030](https://github.com/bcssov/IronyModManager/assets/151412732/2e17dd24-7b44-4cfd-b1e5-645f4b8f80e7)

![Screenshot_20231119_020520](https://github.com/bcssov/IronyModManager/assets/151412732/4bb6605d-d1e9-4178-8c2a-62fc4391beff)

**Logs**
The application did not crash, there are no logs

**Version:**
 - OS: Windows 11
 - Irony Version: Latest release, 1.25.143

**Additional context**
I have only tried this with Stellaris

**Comment by bcssov** [comment]
With the tutorial, and guide on the site you also miss the button with the red border telling you what to do :/

https://github.com/bcssov/IronyModManager/wiki/New-User-Checklist

**Comment by gr33nranger** [comment]
Oh wow, how did I not see that, thank you for your patience, I guess you can close this
