### ISSUE TITLE
Species_classes is now simple LIOS

### ISSUE THREAD

**Issue by Dukko** [bcssov/IronyModManager#473]
**Describe the bug**
Irony treats species_classes in Stellaris modding as a full text overwrite instead of a LIOS.

**To Reproduce**
1. Try to solve a conflict between two species_classes files

**Expected behavior**
Irony should treat species_classes as LIOS so conflicts are resolved correctly.

**Version:**
 - OS: Windows
 - Irony Version 1.25.143

**Additional context**
This is a recent change for Stellaris (possibly 3.10)

**Comment by bcssov** [comment]
Needs verification on discord, I don't think there were any changes to species classes handling based on what wiki stated. Some modders of the past told me they had to use full file overwrite due to issues with same object key. It was not like the other folders.

**Comment by Dukko** [comment]
Nevermind lol
