### ISSUE TITLE
Top level inline scripts marked as an invalid object if inline math with parentheses is present

### ISSUE THREAD

**Issue by PresMemes** [bcssov/IronyModManager#474]
**Describe the bug**
Trying to define an entire object using an inline_script that has inline math that uses parentheses causes Irony to incorrectly mark said object as invalid despite Stellaris compiling it without errors.
Including `# Dear Irony please fallback to simple parser` doesn't fix the issue either.
Removing all the parentheses does make the bug go away, but that's not the most practical solution.

**To Reproduce**
1. Create an inline script that defines an entire object that also uses inline math.
2. Run Irony's conflict solver and check the 'Invalid' section.

**Expected behavior**
Objects entirely defined with inline_scripts with inline math shouldn't be marked as Invalid

**Screenshots**
Inline script definition:
![screenshot13](https://github.com/bcssov/IronyModManager/assets/43762186/974d825e-5db1-411b-8b6f-ab1a4f79b47d)

Object definition (`@civic_default_random_weight = 5`):
![screenshot14](https://github.com/bcssov/IronyModManager/assets/43762186/de6c9e05-e415-4233-8db1-060504d735b8)

Irony's errors:
![screenshot11](https://github.com/bcssov/IronyModManager/assets/43762186/8390de23-1b8a-48a9-a9bd-9576c7367506)
![screenshot12](https://github.com/bcssov/IronyModManager/assets/43762186/88a37c88-b93c-48d1-a69b-cc0c29e32487)

In-game:
![screenshot10](https://github.com/bcssov/IronyModManager/assets/43762186/22fb7985-908e-4ee1-9f19-f30eb520c0bf)

**Version:**
 - OS: Windows 10
 - Irony Version: 1.25.148

**Comment by bcssov** [comment]
Irony uses CWTools beneath it and these are CWTools messages. If you want Irony to switch to a simple inbuilt parser and validation you need to put the comment you mentioned in each affected file (it's per file not global):
```
# Dear Irony please fallback to simple parser
```
And the comment should preferably be on an empty line ie
```
# my comment
block_of_code = {}
# Dear Irony please fallback to simple parser
```

Last time the comment approach was used by the Giga devs; haven't heard from them about any issues with Irony registering and falling back to simple validation.

**Comment by PresMemes** [comment]
So after adding `# Dear Irony please fallback to simple parser` to the top of every file, the inline_script is no longer being marked as invalid but the army itself still is being marked with the same error.

If I nest the inline_script down a level, like so:
```
test_2_army = {
    inline_script = {
        script = test_inline
	HEALTH = @civic_default_random_weight
    }
}
```
Then it is no longer marked as invalid while using the simple parser.

**Comment by bcssov** [comment]
Can you share your test case here?

**Comment by bcssov** [comment]
Excellent, I can confirm several issues. Again a new scenario for Irony.

**Comment by bcssov** [comment]
And fixed 
![Image2](https://github.com/bcssov/IronyModManager/assets/5864390/6842ccfc-f93d-481e-9f75-83f7e1958eef)
