### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by PatoBreezy7** [bcssov/IronyModManager#477]
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**
![17041177503836529066575839500205](https://github.com/bcssov/IronyModManager/assets/155371705/4212d343-b513-4d40-a1ab-6442c711f8f7)

**Logs**
If the application crashed add error logs related to the crash.

**Version:**
 - OS: [e.g. Windows]
 - Irony Version [e.g. 1.5.48]

**Additional context**
![17041178215958424820324171335098](https://github.com/bcssov/IronyModManager/assets/155371705/2b304c08-7cc2-4fa8-a4a0-553fef336e80)
![17041178468265160792547457348693](https://github.com/bcssov/IronyModManager/assets/155371705/65a3c6cf-87bc-4dc6-be3b-4987b14b8ced)
![Uploading 17041178900033716967901572989847.jpg…]()

**Comment by bcssov** [comment]
Check your antivirus. 

These images strain one's eyes and print screen is a thing or you can you copy and paste the error and post it here.
