### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by bcssov** [bcssov/IronyModManager#48]
Will eventually have to set it up. When I find the time, aside from Jenkins\Team City I've very little experience with azure pipelines and or appveyor. If anyone sees this and volunteers to take this one over I'll be eternally grateful for taking over.

**Comment by Sciencmine** [comment]
I myself suggest using [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions), right in the bar under the repo name. It is free, supports using community written action, and multi-platform-ed.

**Comment by bcssov** [comment]
Not really, Irony's pub and deploy are a bit on the more complex side of things than Github actions can offer at the moment.
