### ISSUE TITLE
Conflict Resolver: animation in "Material Light" theme too long

### ISSUE THREAD

**Issue by Baerbeisser** [bcssov/IronyModManager#484]
**Is your feature request related to a problem? Please describe.**
If you have a lot of simple "copy this", "move to bottom", etc. edits (e.g. traits files, sigh), that animation breaks the flow on every.single.line.
I just noticed after starting this report that this is a theme specific issue. 🤦

**Describe the solution you'd like**
* Please make the animation shorter, workflow animations generally shouldn't be longer than 0.4s, better 0.3s.
* * Or, alternatively, remove animation in conflict resolver only.
* Option in settings to disable animations alltogether, if possible.

**Comment by bcssov** [comment]
You are kinda right the ripple effect is kinda distracting, it's also resource intensive. I don't know why the theme makers made it like that and with little configurable options so the best course of action was just to kill it for all listboxes.
