### ISSUE TITLE
Ability to shift+click/ctrl+click to select multiple mods in modlist

### ISSUE THREAD

**Issue by Baerbeisser** [bcssov/IronyModManager#485]
**Is your feature request related to a problem? Please describe.**
Moving multiple mods at once is a often needed feature in 20+ modlists.

**Describe alternatives you've considered**
This works in conflict resolver but not in modlist: for a reason?

**Comment by bcssov** [comment]
> This works in conflict resolver but not in modlist: for a reason?

Maybe because it's a pain to implement one on a framework that was barely documented. Oh, and a duplicate closing #12

**Comment by Baerbeisser** [comment]
What framework, btw?

**Comment by bcssov** [comment]
Avalonia
