### ISSUE TITLE
Error received when clicking apply on a mod collection to which no changes have been made

### ISSUE THREAD

**Issue by Spacewolf4** [bcssov/IronyModManager#488]
**Describe the bug**
For some reason, clicking apply on a mod collection (when I right-clicked to check for new mods, but did not change the collection otherwise, before clicking apply) throws up an error message.

**To Reproduce**
1. Right-click mod list on left of screen.
2. Select Check for New Mods from context menu (in my case, this was habit, not because there actually were any)
3. Click apply button for collection on right of screen.
4. Error message appears.

**Expected behavior**
Apply collection as normal.

**Screenshots**
![Screenshot 2024-02-10 114438](https://github.com/bcssov/IronyModManager/assets/138301634/57d45b61-098f-49d7-815b-ae1f2e2e179e)

**Logs**
[2024-02-10_Error.log](https://github.com/bcssov/IronyModManager/files/14229913/2024-02-10_Error.log)

**Version:**
 - OS: Windows 11 Home 23H2, build 22631.3085, Windows Feature Experience Pack 1000.22684.1000.0
 - Irony Version 1.25.161

**Additional context**
None that I know of as of right now

**Comment by bcssov** [comment]
One of the jsons in documents\paradox interactive\stellaris is corrupt. It could be dlc_load.json, game_data or mod_registry. Delete one or all of them.

**Comment by bcssov** [comment]
Irony is not the one corrupting them. It has to be something else, whether you manually edit them or other software.
