### ISSUE TITLE
Sort Collection using Natural Sort

### ISSUE THREAD

**Issue by jippi** [bcssov/IronyModManager#490]
**Is your feature request related to a problem? Please describe.**
I always name my collections by `v3.11 (v1)`  (format is `v${StellarisVersion} (v${VersionOfThisCollection})` .

Today the collection list is sorted alphabetically, meaning `v3.6 (v2)` is shown after `v3.11 (v1)` - it makes it quite hard to navigate the list, as the naturally increasing version numbers of the game are mixed in with each other, rather than being sorted "correctly".

**Describe the solution you'd like**
I would love to see the lists in the UI sorted using [Natural sorting](https://en.wikipedia.org/wiki/Natural_sort_order) instead.

That would change the following example.

* v3.10
* v3.11
* v3.8
* v.39

To be sorted in a more natural, in line with what folks would expect

* v3.8
* v3.9
* v3.10
* v3.11

**Describe alternatives you've considered**
N/A

**Additional context**
[Discord Chat](https://discord.com/channels/378985949373399040/692727670408085525/1213833760320004166)

**Comment by bcssov** [comment]
Done

**Comment by jippi** [comment]
Thanks! Super fast turn-around, really appreciate it ❤️
