### ISSUE TITLE
"Save Error" When attempting to apply Stellaris modlist

### ISSUE THREAD

**Issue by SaberFin** [bcssov/IronyModManager#491]
**Describe the bug**
When attempting to apply the modlist a save error occurs. The conflict solver button also doesn't do anything, although that is likely because of the former issue.

**To Reproduce**
1.  Select a few mods
2.  Press Apply
3.  See Error

**Expected behavior**
The mods to be applied and the conflict solver to open.

**Screenshots**
<img width="744" alt="image" src="https://github.com/bcssov/IronyModManager/assets/52113895/d3aef60e-f760-4b71-b063-4d3e6bbf064f">

**Logs**

[2024-03-11_Error.log](https://github.com/bcssov/IronyModManager/files/14565271/2024-03-11_Error.log)

**Version:**
 - OS: Windows 11
 - Irony Version v1.25.161

**Additional context**
Does not occur with Paradox Launcher
Any help is appreciated

**Comment by bcssov** [comment]
The paradox sqlite databases are corrupt, delete them in docs\paradox\stellaris folder.

**Comment by bcssov** [comment]
Make sure you have a collection selected. Make sure there are mods in the collection. Make sure you actually toggle on the submenu options there.
