### ISSUE TITLE
Irony not making a playset in the Paradox Launcher

### ISSUE THREAD

**Issue by Adriannaird** [bcssov/IronyModManager#492]
**Describe the bug**
When I click "apply," the playset "IronyModManager" does not appear on the launcher. I have deleted and reinstalled both the launcher and game twice now.

**To Reproduce**
1. Launch Irony 
2. Click "apply"

**Expected behavior**
A playset named "IronyModManager" should be there as an available playset on the Paradox Launcher.

**Version:**
 - OS: Windows 11
 - Irony Version 1.25.161

**Comment by bcssov** [comment]
Seems like misconfiguration on your end. What could be happening:
* You got paradox launcher running at the same time as Irony. 
Solution: Shutdown paradox launcher and hit apply.
* You got irony not pointing towards the right data directory.
Solution: Check in options that irony points towards [documents]\paradox interactive\stellaris. There should not be anything behind the stellaris folder.

**Comment by Adriannaird** [comment]
Ah ty, I switched computers and thought I fucked something with the downloading, tysm!

**Comment by bcssov** [comment]
You open the options popup and update data directory path.

**Comment by Adriannaird** [comment]
TYSM THAT FIXED IT
