### ISSUE TITLE
Not allowing me to apply mods

### ISSUE THREAD

**Issue by Generalamaisng** [bcssov/IronyModManager#496]
I have been trying to get my mods compiled with Irony, but I have been having trouble. Whenever I hit "Apply" in the manager, It gives me an error. I was hoping someone could assist in diagnosing the problem.

[2024-03-17_Error.log](https://github.com/bcssov/IronyModManager/files/14629958/2024-03-17_Error.log)

**Comment by bcssov** [comment]
System.UnauthorizedAccessException: Access to the path '...\Paradox Interactive\Stellaris\dlc_load.json' is denied.
It either antivirus or the file is opened in some text editor.

**Comment by Generalamaisng** [comment]
Managed to get it working! Thank you!
