### ISSUE TITLE
Cannot apply mods nor launch game via manager

### ISSUE THREAD

**Issue by feilislzx** [bcssov/IronyModManager#498]
Issue 1:The checkboxes of the mods in the list cannot be clicked.
![issue1](https://github.com/bcssov/IronyModManager/assets/60915028/0df95711-fae0-41ed-8bd7-c1879a58cdc4)

Issue 2: The 3 buttons ("Apply","Launch Game","Conflict Solver") at the bottom are greyed out(disabled),cannot be clicked.
![issue2](https://github.com/bcssov/IronyModManager/assets/60915028/766dd18e-f5dd-451e-86cb-72e3ff170367)

It worked fine on Paradox Launcher
PS: Is this a bug or something? I've installed win11 recently,is this a compatibility issue related to the OS version? Because it worked fine on windows 10

Can anyone help? Lots of thanks!

**Comment by bcssov** [comment]
It seems user error.

1. Mods disabled means they are invalid, they probably don't exist on the specified location
2. Actions disabled means there is no mod collection.

**Comment by bcssov** [comment]
And the rest you just skipped reading?

https://github.com/bcssov/IronyModManager/assets/5864390/11b7b8dc-4f07-4c71-ad3b-0161423ab1e6

See a flashing button? It indicates something important.
