### ISSUE TITLE
Irony blocked after update

### ISSUE THREAD

**Issue by Generalamaisng** [bcssov/IronyModManager#499]
I managed to get Irony working last week after giving it exemptions with my antivirus. But, when I downloaded the latest update for Irony today, my antivirus wouldn't let me apply changes to my modpacks. I have tried my best to get it to work again, but I am out of ideas.

[2024-03-21_Error.log](https://github.com/bcssov/IronyModManager/files/14714931/2024-03-21_Error.log)

**Comment by bcssov** [comment]
Irony is blocked access here Documents\Paradox Interactive\Stellaris\dlc_load.json 

I can't help with Antivirus blocking access to stuff. Give irony exemption to the stellaris folder not mod folder maybe.

People who use norton reported that the data protector is the culprit.
