### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by bcssov** [bcssov/IronyModManager#50]
Currently Avalonia is borked in that regard, moving to unstable build should fix it but it's a daunting task at the moment.

**Comment by slippycheeze** [comment]
I'm pretty sure this is the same thing I just ran into, where the `l_chinese` localization conflicts with itself in the same mod.  Stellaris [More Events Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=727000451) alone demonstrates this for me.

**Comment by bcssov** [comment]
No, this is nothing related with the game. Irony, Avalonia, has issues rendering chinese\japanese\korean characters on the UI. This is Irony UI issue not game issue.

As for conflicts, sadly this is because localization has duplicates or something.

**Comment by bcssov** [comment]
Switched to noto fonts
Added support for locales to specify which inbuilt font to use
