### ISSUE TITLE
CK3 - Trying to boot a modset with IMM crashes the game on load.

### ISSUE THREAD

**Issue by Siveen** [bcssov/IronyModManager#503]
**Describe the bug**
When trying to boot a modset for Crusader Kings III, the game crashes. This specifically occurs with Warcraft: Guardians of Azeroth and needs testing with other combinations of mods.

**To Reproduce**
1. Create a Modset in IMM for CK3.
2. Add Mods to the Playset.
3. Try to Launch the Game via IMM
4. Game will load for 5 seconds, then crash with a Paradox Crash Reporter popup.

**Expected behavior**
The game boots to the main menu.

**Logs**
[exception.txt](https://github.com/bcssov/IronyModManager/files/15155560/exception.txt)
[debug.log](https://github.com/bcssov/IronyModManager/files/15155562/debug.log)
[error.log](https://github.com/bcssov/IronyModManager/files/15155563/error.log)
[2024-01-31_Fatal.log](https://github.com/bcssov/IronyModManager/files/15155575/2024-01-31_Fatal.log)

**Version:**
 - OS: Windows 10 Home 22H2
 - Irony Version: 1.26.173

**Additional context**
After talking to the Developers of GoA, they think that IMM might load every mod I am subscribed to rather than just the ones selected (see [this](https://discord.com/channels/317351018050355200/1234617491083362374) ticket on their [discord server](https://discord.gg/xtKGkP3E) ).

**Comment by bcssov** [comment]
The assumption that something is wrong with mod loading is accurate, though the assumption that Irony is trying to load all mods is wrong. 

This seems like a misconfiguration error on your end (a user error). Ensure that Irony data directory is set towards Docs\Paradox Interactive\Crusader Kings 3 directory.

**Comment by Siveen** [comment]
![image](https://github.com/bcssov/IronyModManager/assets/59781998/e8f370b7-ba43-4a6b-ae05-451f3ed460fc)
It is.

**Comment by bcssov** [comment]
See if you're using a different documents folder (onedrive) or something. 

What you enable in Irony is how Irony tells the game to load. That's it. Check your dlc_load.json if the load order is correct and if it is... it's beyond my capacity to influence anything else. Try using paradox launcher and see how that goes.

Based on previous experience this has all the signs of a mod issue, now I can't tell you which.

**Comment by Siveen** [comment]
> See if you're using a different documents folder (onedrive) or something.

No I'm not. It's the same C:\Users\Username\Documents\ path that has been the standard for quite a while for Windows.

> Try using paradox launcher and see how that goes.

It works just fine using the Paradox Launcher, which is why I'm approaching IMM.

dlc_load.json looks accurate

**Comment by bcssov** [comment]
Then this isn't really related to Irony. There's one thing you can check... check descriptor.mod from the mod and the one generated by irony in mod folder (you can post them here too). If they have same contents then this really isn't an Irony issue.

**Comment by Siveen** [comment]
[ugc_2949767945.txt](https://github.com/bcssov/IronyModManager/files/15215393/ugc_2949767945.txt)
[descriptor.txt](https://github.com/bcssov/IronyModManager/files/15215403/descriptor.txt)

Had to change the file extensions away from .mod because Github is being Github.

**Comment by bcssov** [comment]
These are not the same, Irony if operating properly will always ensure to refresh a mod file if one of the elements inside the descriptor.mod (inside the mod folder) needs a refresh.

See below
![Image2](https://github.com/bcssov/IronyModManager/assets/5864390/a1b23b23-e358-43f0-99ed-c45cf75437ba)

One explanation is that your AV might be preventing Irony from actually writing or overwriting files. The rest is up to you to find out why. But I can guarantee you that Irony's behavior is to refresh ugc_whatever.mod file.

**Comment by Siveen** [comment]
I'm using Windows Defender and it hasn't piped up about it. Furthermore these aren't issues cropping up with Stellaris or Hearts of Iron IV. The permissions are the same for all three folder structures, so there shouldn't be any R/W issues (and if there were wouldn't they be logged in IMMs error log?)

**Comment by bcssov** [comment]
Irony is operating as expected and I see no issues on its end. This is either:
1. Game issue
2. Mod issue
