### ISSUE TITLE
Update dialog boxes unpickable in options window due to lack of scroll.

### ISSUE THREAD

**Issue by Spacewolf4** [bcssov/IronyModManager#506]
**Describe the bug**
UI of options screen with update-install exceeds screen size.

**To Reproduce**
1. Load IMM
2. Open options window
3. Options window exceeds bounda as seen in attached screenshot with no ability to scroll to reach buttons.
4. 

**Expected behavior**
Options window needs to scroll so user can reach action buttons.

**Screenshots**
![irony mod manager weirdness](https://github.com/bcssov/IronyModManager/assets/138301634/35c076ca-2bd9-4a21-81b1-386938170a2e)

**Version:**
Windows 11 23H2
 - Irony Version 1.26.176

**Additional context**
Has seemed to be a thing throughout 1,26, and appeared with that.

**Comment by bcssov** [comment]
Minimal expected resolution is 1080 height. You are either using resolution upscaling or a lower resolution. I am closing this issue since the options screen will be redesigned at a future data.

**Comment by bcssov** [comment]
I am copying this from one of the support staff on irony discord (Makharya):
> on windows there is a settings only for text
![image](https://github.com/bcssov/IronyModManager/assets/5864390/ee81edc2-70a3-4e7a-8777-b64e6620186a)
> on top of the scale
![image](https://github.com/bcssov/IronyModManager/assets/5864390/4025d833-1ae3-4bc6-9533-047a73294fd4)
