### ISSUE TITLE
Merged mods doesn't work on another PC properly

### ISSUE THREAD

**Issue by Branemor** [bcssov/IronyModManager#508]
Vic3. I merged about ten different mods in one because of different checksum issue in MP.  Everything works properly on my PC but when my mate starts the game with that same merged mod it almost doesn't work. The game starts smoothly, checksum issue solved, but half of mods' features don't work or don't work correctly and game crashes constantly. I would presume that the problem is mod conflict, but everything is completely fine on my PC. 

**Version:**
 - OS: Windows 11
 - Irony Version 1.26.181

**Comment by bcssov** [comment]
I'm guessing a DLC might be missing. It's a mod or game issue something I am not qualified to help with (I do not own Vicky).

**Comment by Branemor** [comment]
I have a full licence version, while my mate... well let's say he owns the original game, but dlcs are indicated as purchased, could this be an issue?

> I'm guessing a DLC might be missing. It's a mod or game issue something I am not qualified to help with (I do not own Vicky).

**Comment by bcssov** [comment]
If he doesn't own all the DLCs as you do and he is playing SP only, not MP, this will cause problems in other PDX games, such as Stellaris. I am assuming the same is true for Victoria. For other stuff questions, I recommend you contact paradox support. This goes beyond Irony support.
