### ISSUE TITLE
Stellaris Mod Collection not being applied

### ISSUE THREAD

**Issue by RobbieWood-Aethersys** [bcssov/IronyModManager#509]
**Describe the bug**
For Stellaris, when applying a Collection (subset of installed mods) Irony indicates that the collection is applied, but clicking Launch launches the game without said collection being applied. I can tell, because a Star Trek mod not in the collection changes the loading screens, which immediately appear upon launching.

**To Reproduce**
1. Install several mods
2. Create a collection containing only some of those mods. Mine was called "3.12".
3. Click Apply
4. Click Launch Game

**Expected behavior**
Stellaris to launch with only the mods in the selected collection applied.

**Screenshots**
None, really.

**Logs**
It didn't crash, and the Error logs are entirely made up of issues with the mods themselves, as several mods not in the collection are out of date.

**Version:**
 - OS: Windows 10
 - Irony Version v1.26.182

**Additional context**
I'd originally thought incorrect mods being applied was Steam not downloading them correctly, so I went through the whole rigmarole of purging and redownloading them. Looking in the Paradox launcher, there's only one old collection in there called "initial preset" - I can't remember if that's something I created ages ago, or auto-generated. Exporting from Irony into the Paradox Launcher seems to work fine, and the game runs fine when the correct collection is applied in the Paradox launcher.

**Comment by RobbieWood-Aethersys** [comment]
Whoops, opened this on my work account on my lunch break. Apologies!

**Comment by bcssov** [comment]
I will leave this closed. This is almost always a game issue or irony misconfiguration:
1. Game hates non ascii characters in path therefore it refuses to load mods from user directories which might contain cyrilic alphabet for example
2. Local mods might not get loaded from a path which exceeds certain length (believe it's 160 on windows)
3. Irony data directory does not point towards c:\users\username\docs\paradox interactive\stellaris (this should be without the mod part)
