### ISSUE TITLE
"Value cannot be null" crash

### ISSUE THREAD

**Issue by Midaychi** [bcssov/IronyModManager#51]
starting at v1.0.60-beta and onward on windows 10 x64 (Previous versions work fine), starting the program up and selecting stellaris will not load up any mods and will instead throw a log to the log file about how the value cannot be null. Closing the launcher and then relaunching will result in a crash loop that can only be fixed by deleting the Database.json.
[2020-04-30_Error.log](https://github.com/bcssov/IronyModManager/files/4557911/2020-04-30_Error.log)

**Comment by bcssov** [comment]
This update just moved stuff around so the issue for you was probably present in earlier versions too.

GOG user? You are manually installing mods? If so please see #33.

**Comment by bcssov** [comment]
Next beta release will check for validity of descriptor mod files and prompt you to delete them instead of just crashing.
