### ISSUE TITLE
Flatpak 

### ISSUE THREAD

**Issue by Sanceilaks** [bcssov/IronyModManager#519]
It would be convenient to be able to download the app using flatpak

**Comment by bcssov** [comment]
For this I'd probably need help. I am not a linux user primarily, and any additional sources are maintained by other people, for example the arch linux package: https://aur.archlinux.org/packages/irony-mod-manager-bin

What little I do know from experience is that flatpak causes headaches to users who install flatpak steam. As irony not being able to communicate with steam using steam uri protocol and such.
