### ISSUE TITLE
Fails to launch or install

### ISSUE THREAD

**Issue by FierceEncounter** [bcssov/IronyModManager#522]
**Describe the bug**
I downloaded the Irony mod manager for Windows 64 bit, extracted the file and attempted to launch the ironymodmanager.exe and nothing happened at all. It is failing to launch. 

**To Reproduce**
1. Download the Irony mod manager windows 64 bit file
2. Extract the file
3. Launch the ironymodmanager.exe
4. Nothing happened

**Expected behavior**
I expected Irony mod manager to launch

**Screenshots**

**Logs**
N/A

**Version:**
 - OS: Windows 11
 - Irony Version 1.26.191

**Additional context**

**Comment by bcssov** [comment]
Sounds like your AV is blocking irony. Whitelist it.
