### ISSUE TITLE
Creating Patch for Stellaris Mod causes game load crash

### ISSUE THREAD

**Issue by lmSleepless** [bcssov/IronyModManager#523]
**Describe the bug**
When using "Hydra's More Civics" (https://steamcommunity.com/sharedfiles/filedetails/?id=3248725702), I get crashing when starting a new game. However, it only happens if I have created the patch mod, either in default or advanced mode. This will happen in any modlist that has this mod, even if it is the only mod. If I delete or disable the patch mod, new game will not crash.

**To Reproduce**
1. Install and activate mod (https://steamcommunity.com/sharedfiles/filedetails/?id=3248725702)
2. Create patch mod
3. Launch game
4. Start New game. Crash occurs after picking species, confirming galaxy settings. Seems to be during or after galaxy gen progress bar.

**Expected behavior**
Game should start.

**Logs**
Not sure if you want me to paste zip of crash dump. Let me know if you want it.

**Version:**
 - OS: Windows 10
 - Irony Version - 1.26.191
 - Stellaris - 3.13.2

**Additional context**

**Comment by bcssov** [comment]
Seems like authorities now allow authority "merging" or something via "advanced_authority_swap". Wonder when they added that... anyway fixed. Thanks for the report.
