### ISSUE TITLE
Mod manager get stuck at loading mod data indefinitely

### ISSUE THREAD

**Issue by MaraJadeLives** [bcssov/IronyModManager#524]
**Describe the bug**
Irony gets stuck loading mod data.

**To Reproduce**
1. Open Irony from desktop shortcut
2. Wait.

**Expected behavior**
Irony would load my mods, so I could play my modded Stellaris game. 

**Logs**
I don't know where to find logs, despite looking a little.

**Version:**
 - OS: Windows 10
 - Irony Version 1.26.191
 - Surface Pro 4 with 4 GB of RAM (in case RAM was an issue)

**Additional context**
It doesn't always happen. Like #152 but not running as admin. I tried opening, then closing STEAM, and repeatedly trying to open Irony.

**Comment by bcssov** [comment]
This seems like a hardware issue. Irony is attempting to build a live database of all installed mods in realtime performing disk IO...

Surface Pro is relatively an old machine. I think your best bet is with paradox launcher.

**Comment by MaraJadeLives** [comment]
> This seems like a hardware issue. Irony is attempting to build a live database of all installed mods in realtime performing disk IO...
> 
> Surface Pro is relatively an old machine. I think your best bet is with paradox launcher.

Good to know why it does it intermittently on this. It likely also explains why my modded  game crashes every so often. Sorry that I didn't see your comment until just now.
