### ISSUE TITLE
Fatal Error while conflict resolving Stellaris: Gigastructural Engineering

### ISSUE THREAD

**Issue by lmSleepless** [bcssov/IronyModManager#528]
**Describe the bug**
With latest version of Irony, getting a Irony crash when attempting to conflict resolve if Gigastructural Engineering is in the list. This will happen even if the only mod in the list is Gigastructural Engineering. I imagine this might be an issue with Giga, but I suspect it shouldn't crash Irony even if it is. 

I should note, it did conflict resolve without crashing with previous version and it doesn't look like Giga has changed at the time that I'm writing this.

Error message from irony attached in text doc as its a bit fat.
[Error message.txt](https://github.com/user-attachments/files/17577284/Error.message.txt)

**To Reproduce**
1. Put Gigastructural engineering into mod list
2. Conflict Resolver Default
3. Crash after some processing

**Expected behavior**
Not crashing. 

**Screenshots**
![image](https://github.com/user-attachments/assets/5b01b989-2712-4ac7-a66f-65c99ce06f57)

**Logs**
If the application crashed add error logs related to the crash.

**Version:**
 - OS: Windows 10
 - Irony Version: 1.26.197

**Additional context**

**Comment by Silentoe127** [comment]
**Describe the bug**
I'm in the middle of troubleshooting this exact issue myself. Almost exactly the same, except it occurs on other mods as well as Gigastructures (haven't tested all, but so far Giga and ACOT). There are other mods that do NOT crash. So it is mod specific. 

So far I've tried restarting the computer, and reinstalling Irony. No dice. 

**Screenshots**
No screenshots, but if a [youtube video](https://youtu.be/CUqklA74ums) helps?


**Logs**
[2024-10-30_Fatal.log](https://github.com/user-attachments/files/17578142/2024-10-30_Fatal.log)

**Version:**
 - OS: Windows 11
 - Irony Version 1.26.197
