### ISSUE TITLE
Fake error

### ISSUE THREAD

**Issue by WarLedy** [bcssov/IronyModManager#529]
**Describe the bug**
Fake error in file

**To Reproduce**
This error was on the latest and penultimate versions, it shows that the closing bracket in "portrait_groups = {
" is not needed, although in older files everything is the same, but it does not see the error.

**Screenshots**
![2024-11-03_02-05-20](https://github.com/user-attachments/assets/7f005e1f-5c40-483e-beeb-6099f8dc9846)

**Logs**
"
portrait_groups = {
	asari = {
		default = asari_1
		game_setup = { #will run with a limited country scope. species and government is set but the country does not actually exist
			add = {
				portraits = {
					asari_1				
				}
			}
		
			#set = {
			#	trigger = { ... }
			#	portraits = { ... }
			#	#using "set =" instead of "add" will first clear any portraits already added
			}
		}		
		
		#species scope
		species = { #generic portrait for a species
			add = {
				portraits = {
					asari_1
				}
			}
		}		
		
		#pop scope
		pop = { #for a specific pop
			add = {
				portraits = {
					asari_1
				}
			}
		}
		
		#leader scope
		leader = { #scientists, generals, admirals, governor
			add = {
				portraits = {
					asari_1
				}
			}
		}

			
		#leader scope 
		ruler = {
			add = {
				portraits = {
					asari_1
				}
			}
		}		
	}
}
"
It seems that the last closing parenthesis is redundant

**Version:**
 - OS: win 10
 - Irony Version last

**Comment by WarLedy** [comment]
[asari_portraits.txt](https://github.com/user-attachments/files/17608429/asari_portraits.txt)

**Comment by bcssov** [comment]
Not a fake error, CWTools is accurate.

Take a closer look at this segment which is not completely commented out and you have an extra pair of curly braces ln 72
```
			#set = {
			#	trigger = { ... }
			#	portraits = { ... }
			#	#using "set =" instead of "add" will first clear any portraits already added
			}
```
