### ISSUE TITLE
Bug : Parsing error

### ISSUE THREAD

**Issue by calniotrey** [bcssov/IronyModManager#53]
I just found a parsing bug while patching a collection.
Step to replicate : download [SLEX](https://steamcommunity.com/sharedfiles/filedetails/?id=2054717582), add in a collection and patch. Look at the Invalid section.
Screenshot : 
![image](https://user-images.githubusercontent.com/25230468/80869165-0d5b5700-8c9f-11ea-982b-1f5a1555e0b3.png)

The code flagged as invalid works.

Version of Irony : 1.0.79-beta

**Comment by bcssov** [comment]
There's nothing that I can do. This is a message from CWTools that I'm propagating. The issue has been reported on CWTools issue tracker [here](https://github.com/tboby/cwtools/issues/26)

**Comment by calniotrey** [comment]
Thanks a lot !
