### ISSUE TITLE
v1.0.81-beta - Winx64 - Will not load if mod has been unsubscribed from

### ISSUE THREAD

**Issue by TactlessNinja** [bcssov/IronyModManager#54]
Unknown if this is just on my end due to an earlier issue (detailed below), but if I deselected a mod on the loaded list I found I could not delete and reload. So I unsubscribed via Steam, tried loading IMM up and it wouldn't appear. I had to go to a previous version which then notified me the mod was missing and if I wanted to remove the descriptor. I did so, loaded up the latest IMM version and it worked normally.

I found I had this issue before earlier on in the day when it would appear a Steam curator or whatever removed their mod from Steam, so the mod disappeared off my list without me even knowing and IMM wouldn't load up. It was only when I went back a version did I get the notification of a missing mod.

I.E. If a mod is unsubscribed from, this version has an issue with loading up.

**Comment by bcssov** [comment]
This version had nothing different from the version when descriptor check had been added. Will be difficult to reproduce given that no versions you used were specified aside from the latest one and the fact the code did not change from 1.0.79. It might have something to do if an invalid mod is located in the collections mods section. Will test if I can repro this case.

**Comment by bcssov** [comment]
Visual studio decided to exclude app icons from build process, very annoying. Fixed version will be up. Look for 1.0.83+.
