### ISSUE TITLE
Feature request: Edit inline in conflict resolver

### ISSUE THREAD

**Issue by adriangaro** [bcssov/IronyModManager#66]
Editing inline the conflict resolver would be very useful since in some cases the diffs dont align as they should and it is very bothersome to have to click edit, paste the whole other file, select the section you need, paste where it was supposed to go and then going back to the diff viewer.

May not be related to this, but can there be added the possibility to copy the selection in the diff viewer? Ctrl-C doesn't work and Copy Text copies the whole definition not the selection.

**Comment by bcssov** [comment]
Yeah unfortunately no diff will allign pdx script properly. 

You'd be the 3rd or 4th person asking for this or why is it like this. My reasoning is simple to prevent any newbie errors in a free form editor. My design choice is based on the only known editor for Stellaris to do diff merging and that is abandoned Stellaris mod manager which worked on a similar principle. I've been monitoring reports on this however and been thinking to include an advanced mode of sorts. Though this requires some additional coding on my end.
