### ISSUE TITLE
Irony not pruning invalid filename characters when exporting collections

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#70]
Given that you can't have question marks in files I'm guessing that was the cause of this crash.

In the meantime I'll go edit the JSON files to remove said question mark ;P

Edit: Uh, so after posting this I realised I was dumb and can edit the file name in the save dialogue, i just didn't stop to think that there'd be a question mark in the suggested file name given it sanitises most other places.

[2020-05-16_Error.log](https://github.com/bcssov/IronyModManager/files/4637877/2020-05-16_Error.log)

**Comment by bcssov** [comment]
Or you could not simply use strange characters in collection names which 99% of the users won't

**Comment by LordOfLA** [comment]
How well would it handle letters outside the 26 of the modern Latin Alphabet as a collection/filename? This instance was down to me being dumb but could there be cases where a user with a non English native language could run into similar issues?
