### ISSUE TITLE
Query/Bug? Mod lower down the list contains empty file named same as mod above it. Irony does not treat this is overwritten.

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#72]
Mods: Ethics & Civics Alternative - https://steamcommunity.com/sharedfiles/filedetails/?id=1790861374
Relytor's Empire Governance - https://steamcommunity.com/sharedfiles/filedetails/?id=1984230854

Both contain common\governments\ethic_rebuild_governments.txt, the latter mod has it blanked to override the former. However Irony still shows the former as winning via LIOS. I'm not sure it should do that?

**Comment by bcssov** [comment]
To you it might be a bug to me it's a scenario which I never expected. Irony sees an empty file and ignores it or to be more precise nothing is returned from parsers. Will put on 1.1 sometime in the future once I get back into Stellaris again.

**Comment by bcssov** [comment]
That opened Pandora's box and got complicated really fast. Such as what if overwriting empty mod file doesn't declare all jobs that mod that is being overwritten has. Should all be covered now.
