### ISSUE TITLE
Conflict solver - Mode

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#73]
Further to the discussion of this on the Stellaris modding den discord, it'd be rather useful if Irony could re-write any existing dependency tags based on collection sort order, so that mods like Plentiful Traditions with its random entries can't break things.

**Comment by bcssov** [comment]
No, dependency tags are mod developer tool one which Irony will not touch.

**Comment by bcssov** [comment]
I will go with the advanced conflict solver toggle instead.
