### ISSUE TITLE
Small wording clarity tweak suggestion

### ISSUE THREAD

**Issue by BlackGoatPC** [bcssov/IronyModManager#82]
One small suggestion I have is a text tweak for clarity for the "Open in Associated App" feature.

Specifically, I'm talking about in the mods list when you right-click a mod to open the popup menu, you get the option "Open in Associated App". At first, I had no idea what this meant and so I ignored and avoided using the feature, not realizing that selecting this option would open the mod files location on my system (in windows via file explorer) which is a very useful feature for making quick local edits without having to search for the exact mod folder manually! 

I would suggest a change in this right-click menu option's text to say "Open Mod Files Location" or simply "Open Folder" (Rimpy mod manager for Rimworld uses this wording for the same feature). 

Thanks for the project, it's great and gets better with every release!

**Comment by bcssov** [comment]
That's a pretty reasonable suggestion, I was looking for the correct wording but it never got to me. I'll have it updated in the next alpha.
