### ISSUE TITLE
wishlist: better visibility of conflicts in conflict solver -- brainstorming inside

### ISSUE THREAD

**Issue by slippycheeze** [bcssov/IronyModManager#96]
It'd be nice if the conflict solver showed the number of remaining conflicts to be resolved, or maybe just jumped to the first category with them automatically.

Right now it's hard to tell if there are any conflicts at all, or not, when adding a new mod.  Which could just be I'm unfamiliar with the tool, but if I hit the button it right now shows nothing to tell me if there are things in the "Conflicted Objects" list -- just not yet selected.

**Comment by bcssov** [comment]
Nice idea, easy to do. But need to prioritize the new launcher update thingie tasks so for next big version.
