### ISSUE TITLE
shortcut to ignore category

### ISSUE THREAD

**Issue by slippycheeze** [bcssov/IronyModManager#98]
I'd be fine ignoring all the localisation categories except english; it'd be convenient to have a shortcut to do that.

**Comment by bcssov** [comment]
Check out gitignore like ignore rules, I think this covers what you recommended? 
https://github.com/bcssov/IronyModManager/wiki/Ignore-Rules
Let me know if I seem to be missing something and we can discuss proposed extension syntax.

**Comment by LordOfLA** [comment]
My current ignore rules for conflict solver:

flags\\backgrounds
gfx\\event_pictures
gfx\\interface
gfx\\loadingscreens
gfx\\map
gfx\\models
!gfx\\models\\planets
gfx\\portraits\\city_sets
gfx\\projectiles
gfx\\ui_overhaul_qhd
localisation\\spanish
localisation\\simp_chinese
localisation\\russian
localisation\\german
localisation\\french
localisation\\polish
localisation\\braz_por

**Comment by bcssov** [comment]
I suppose this is you just proposing settings for slippy?

**Comment by LordOfLA** [comment]
Yup

**Comment by slippycheeze** [comment]
Sorry, have not had a chance to try this yet.  Will confirm when I do.

**Comment by bcssov** [comment]
Closing.
